---
permalink: concepts/concept_solidfire_concepts_data_protection.html 
sidebar: sidebar 
keywords: what is, element, solidfire, replication, clone, snapshot, protection domain, double helix 
summary: 資料保護功能包括遠端複製、磁碟區快照、磁碟區複製、保護網域以及採用雙螺旋技術的高可用性。 
---
= 資料保護
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
資料保護功能包括遠端複製、磁碟區快照、磁碟區複製、保護網域以及採用雙螺旋技術的高可用性。

元素儲存資料保護包括以下概念：

* <<遠端複製類型>>
* <<用於資料保護的磁碟區快照>>
* <<卷克隆>>
* <<Element儲存的備份和復原流程概述>>
* <<保護域>>
* <<custom_pd,自訂保護域>>
* <<雙螺旋高可用性>>




== 遠端複製類型

遠端資料複製可以採取以下幾種形式：

* <<集群間的同步和非同步複製>>
* <<僅快照複製>>
* <<使用SnapMirror在 Element 和ONTAP叢集之間進行複製>>


更多資訊請參見 https://www.netapp.com/pdf.html?item=/media/10607-tr4741pdf.pdf["TR-4741： NetApp Element軟體遠端複製"^]。



=== 集群間的同步和非同步複製

對於運行NetApp Element軟體的集群，即時複製可以快速建立磁碟區資料的遠端副本。

您可以將一個儲存叢集與最多四個其他儲存叢集配對。您可以同步或非同步地從叢集對中的任一叢集複製磁碟區數據，以實現故障轉移和故障復原場景。



==== 同步複製

同步複製會將資料從來源集群持續複製到目標集群，但會受到延遲、丟包、抖動和頻寬的影響。

同步複製適用於以下情況：

* 在短距離內複製多個系統
* 災難復原站點的地理位置應與來源站點相近
* 時間敏感型應用與資料庫保護
* 業務連續性應用程式要求在主站點宕機時，備用站點能夠充當主站點。




==== 非同步複製

非同步複製會持續地將資料從來源集群複製到目標集群，而無需等待目標集群的確認。在非同步複製過程中，寫入作業會在來源叢集上提交後，會向客戶端（應用程式）發出確認通知。

異步複製適用於以下情況：

* 災難復原站點距離源頭很遠，而且應用程式無法容忍網路延遲。
* 連接源集群和目標集群的網路頻寬有限。




=== 僅快照複製

僅快照資料保護會在特定時間點將已變更的資料複製到遠端叢集。只有在來源叢集上建立的快照才會被複製。來自來源磁碟區的活動寫入操作不會發生。

您可以設定快照複製的頻率。

快照複製不會影響非同步複製或同步複製。



=== 使用SnapMirror在 Element 和ONTAP叢集之間進行複製

透過NetApp SnapMirror技術，您可以將使用NetApp Element軟體拍攝的快照複製到ONTAP ，以用於災難復原。在SnapMirror關係中，Element 是一個端點， ONTAP是另一個端點。

SnapMirror是NetApp 的快照複製技術，可實現災難恢復，專為從主儲存故障轉移到地理位置偏遠的輔助儲存而設計。 SnapMirror技術會在輔助儲存中建立工作資料的副本或鏡像，以便在主網站發生故障時繼續提供資料。資料在磁碟區層級上進行鏡像。

主記憶體中的來源磁碟區與輔助記憶體中的目標磁碟區之間的關係稱為資料保護關係。集群被稱為磁碟區所在的端點，包含複製資料的磁碟區必須相互連接。對等關係使叢集和磁碟區能夠安全地交換資料。

SnapMirror可在NetApp ONTAP控制器上原生運行，並整合到 Element 中，Element 可在NetApp HCI和SolidFire叢集上運行。控制SnapMirror的邏輯位於ONTAP軟體中；因此，所有SnapMirror關係都必須至少涉及一個ONTAP系統來執行協調工作。使用者主要透過 Element UI 管理 Element 和ONTAP叢集之間的關係；但是，有些管理任務位於NetApp ONTAP系統管理器中。用戶還可以透過 CLI 和 API 管理SnapMirror ，這兩種方式在ONTAP和 Element 中均可使用。

看 https://fieldportal.netapp.com/content/616239["TR-4651： NetApp SolidFire SnapMirror架構與配置"^]（需要登入）

您必須使用 Element 軟體在叢集層級手動啟用SnapMirror功能。  SnapMirror功能預設為停用狀態，且在新安裝或升級過程中不會自動啟用。

啟用SnapMirror後，您可以從 Element 軟體中的「資料保護」標籤建立SnapMirror關係。

NetApp Element軟體 10.1 及更高版本支援SnapMirror功能，可複製並復原ONTAP系統的快照。

運行 Element 10.1 及更高版本的系統包含可以直接與運行 9.3 或更高版本的ONTAP系統上的SnapMirror通訊的程式碼。 Element API 提供了在叢集、磁碟區和快照上啟用SnapMirror功能的方法。此外，Element UI 還包含管理 Element 軟體和ONTAP系統之間SnapMirror關係的功能。

從 Element 10.3 和ONTAP 9.4 系統開始，您可以在特定用例中將ONTAP來源磁碟區複製到 Element 卷，但功能有限。

有關詳細信息，請參閱 link:../storage/element-replication-index.html["NetApp Element軟體與ONTAP (ONTAP CLI) 之間的複製"]。



== 用於資料保護的磁碟區快照

磁碟區快照是磁碟區在特定時間點的副本，您可以稍後使用該副本將磁碟區還原到該特定時間點。

雖然快照與磁碟區複製類似，但快照只是卷元資料的副本，因此您無法掛載或寫入它們。建立磁碟區快照也只需要少量系統資源和空間，因此快照建立速度比複製更快。

您可以將快照複製到遠端集群，並將其用作磁碟區的備份副本。這樣，您就可以使用複製快照將磁碟區回滾到特定時間點；您也可以從複製快照建立磁碟區的複製。

您可以將 Element 叢集中的快照備份到外部物件存儲，或備份到另一個 Element 叢集。將快照備份到外部物件儲存時，必須與該物件儲存建立允許讀取/寫入作業的連線。

您可以對單一磁碟區或多個磁碟區進行快照以保護資料。



== 卷克隆

單一磁碟區或多個磁碟區的複製是資料在特定時間點的副本。複製磁碟區時，系統會建立磁碟區的快照，然後建立快照所引用的資料的副本。

這是一個非同步過程，該過程所需的時間取決於您要複製的磁碟區的大小和當前的叢集負載。

叢集一次最多支援每個磁碟區運行兩個克隆請求，並且一次最多支援八個活動卷克隆操作。超出這些限制的請求將被排隊，稍後再處理。



== Element儲存的備份和復原流程概述

您可以將磁碟區備份和還原到其他SolidFire存儲，以及與 Amazon S3 或 OpenStack Swift 相容的輔助物件儲存。

您可以將磁碟區備份到以下位置：

* SolidFire儲存集群
* 亞馬遜 S3 對象存儲
* OpenStack Swift 物件存儲


從 OpenStack Swift 或 Amazon S3 還原磁碟區時，需要原始備份過程中的清單資訊。如果您要還原備份在SolidFire儲存系統上的捲，則不需要清單資訊。



== 保護域

保護域是指將一個或多個節點組合在一起，使得其中任何部分甚至全部故障，都能維持資料可用性。保護域使儲存叢集能夠從機箱（機箱親和性）或整個網域（機箱群組）的遺失中自動復原。

您可以使用NetApp Element Plugin for vCenter Server 中的NetApp Element配置擴充點手動啟用保護網域監控。您可以根據節點域或機箱域選擇保護域閾值。您也可以使用 Element API 或 Web UI 啟用保護域監控。

保護域佈局將每個節點指派到一個特定的保護域。

支援兩種不同的保護域佈局，稱為保護域層級。

* 在節點級別，每個節點都有自己的保護域。
* 在機箱級別，只有共用相同機箱的節點才處於相同保護域。
+
** 當節點新增至叢集時，機箱層級佈局會根據硬體自動確定。
** 在每個節點都位於獨立機箱中的叢集中，這兩個層級的功能是相同的。




建立新叢集時，如果您使用的是位於共用機箱中的儲存節點，則可能需要考慮使用保護域功能來設計機箱級故障保護。



== 自訂保護域

您可以定義一個自訂保護域佈局，使其與您的特定機箱和節點佈局相匹配，其中每個節點都與一個且僅一個自訂保護域相關聯。預設情況下，每個節點都分配到同一個預設自訂保護域。

如果未指派任何自訂保護域：

* 叢集運作不受影響。
* 自訂等級既不寬容也不靈活。


為叢集配置自訂保護域時，有三個可能的保護級別，您可以在 Element Web UI 儀表板中查看這些級別：

* 未受保護：儲存叢集未受到保護，無法抵禦其某個自訂保護域的故障。若要解決此問題，請在叢集中新增額外的儲存容量，或重新配置叢集的自訂保護域，以保護叢集免受可能的資料遺失。
* 容錯性：儲存叢集具有足夠的可用容量，以防止其自訂保護域之一發生故障後資料遺失。
* 容錯能力強：儲存叢集具有足夠的可用容量，可以在其某個自訂保護域發生故障後進行自我修復。修復過程完成後，即使其他域發生故障，叢集也能免受資料遺失的影響。


如果分配了多個自訂保護域，則每個子系統會將重複項指派給不同的自訂保護域。如果無法做到這一點，則退而求其次，將重複項分配到不同的節點。每個子系統（例如，箱子、切片、協議端點提供者和集合）獨立地執行此操作。

您可以使用 Element UI 來link:../storage/task_data_protection_configure_custom_protection_domains.html["配置自訂保護域"]或者，您可以使用以下 API 方法：

* link:../api/reference_element_api_getprotectiondomainlayout.html["取得保護域佈局"]- 顯示每個節點所在的機箱和自訂保護域。
* link:../api/reference_element_api_setprotectiondomainlayout.html["設定保護域佈局"]- 允許為每個節點指派自訂保護域。




== 雙螺旋高可用性

雙螺旋資料保護是一種複製方法，它將至少兩個冗餘資料副本分佈在系統內的所有磁碟機上。  「無 RAID」方法使系統能夠承受儲存系統所有層級上的多個並發故障，並快速修復。
