---
permalink: concepts/concept_intro_clusters.html 
sidebar: sidebar 
keywords: element, solidfire, cluster, what is, authoritative  cluster, rule of thirds, stranded capacity, storage efficiency, storage cluster quorum 
summary: 叢集是SolidFire儲存系統的核心，由多個節點組成。要實現SolidFire儲存效率，叢集中必須至少有四個節點。叢集在網路上表現為單一的邏輯群組，然後可以像區塊儲存一樣進行存取。 
---
= 叢集
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
叢集是SolidFire儲存系統的核心，由多個節點組成。要實現SolidFire儲存效率，叢集中必須至少有四個節點。叢集在網路上表現為單一的邏輯群組，然後可以像區塊儲存一樣進行存取。

建立新叢集會將一個節點初始化為叢集的通訊所有者，並為叢集中的每個節點建立網路通訊。此過程僅對每個新叢集執行一次。您可以使用 Element UI 或 API 建立叢集。

您可以透過新增額外的節點來擴展叢集。新增節點時，服務不會中斷，叢集會自動利用新節點的效能和容量。

管理員和主機可以使用虛擬 IP 位址存取叢集。叢集中的任何節點都可以託管虛擬 IP 位址。管理虛擬 IP (MVIP) 可透過 1GbE 連線實現叢集管理，而儲存虛擬 IP (SVIP) 可透過 10GbE 連線實現主機對儲存的存取。這些虛擬 IP 位址能夠確保連線穩定，無論SolidFire叢集的大小或組成為何。如果承載虛擬 IP 位址的節點發生故障，叢集中的另一個節點將開始承載該虛擬 IP 位址。


NOTE: 從 Element 版本 11.0 開始，節點可以設定 IPv4、IPv6 或兩者的位址作為其管理網路。這適用於儲存節點和管理節點，但管理節點 11.3 及更高版本除外，此版本不支援 IPv6。建立叢集時，MVIP 只能使用單一 IPv4 或 IPv6 位址，並且必須在所有節點上配置對應的位址類型。

.關於集群的更多信息
* <<權威儲存叢集>>
* <<三分法>>
* <<擱淺產能>>
* <<儲存效率>>
* <<儲存叢集仲裁>>




== 權威儲存叢集

權威儲存叢集是NetApp Hybrid Cloud Control 用於驗證使用者身分的儲存叢集。

如果您的管理節點只有一個儲存集群，那麼它就是權威集群。如果您的管理節點有兩個或多個儲存集群，則其中一個集群將被指定為權威集群，並且只有該集群中的使用者才能登入NetApp Hybrid Cloud Control。要找出哪個集群是權威集群，可以使用以下方法： `GET /mnode/about` API。回應中包含 IP 位址 `token_url`此欄位是權威儲存叢集的管理虛擬 IP 位址 (MVIP)。如果您嘗試以不在權威叢集上的使用者身分登入NetApp Hybrid Cloud Control，則登入嘗試將會失敗。

NetApp Hybrid Cloud Control 的許多功能旨在與多個儲存叢集配合使用，但驗證和授權有其限制。身份驗證和授權方面的限制是，即使用戶不是其他儲存叢集上的用戶，權威叢集中的用戶也可以對與NetApp Hybrid Cloud Control 關聯的其他叢集執行操作。

在開始管理多個儲存叢集之前，您應該確保在權威叢集上定義的使用者在所有其他儲存叢集上都具有相同的權限。您可以從以下位置管理用戶link:../storage/concept_system_manage_manage_cluster_administrator_users.html["Element軟體使用者介面"]。

看link:../mnode/task_mnode_manage_storage_cluster_assets.html["建立和管理儲存叢集資產"]有關使用管理節點儲存叢集資產的詳細資訊。



== 三分法

在NetApp SolidFire儲存叢集中混合使用儲存節點類型時，任何單一儲存節點的容量都無法超過整個儲存叢集容量的 33%。



== 擱淺產能

如果新新增的節點佔叢集總容量的 50% 以上，則該節點的部分容量將停用（「閒置」），以使其符合容量規則。在增加更多儲存容量之前，這種情況將持續下去。如果新增一個非常大的節點，並且該節點也違反容量規則，則先前被困的節點將不再被困，而新新增的節點將變為被困。為避免這種情況發生，容量應該始終成對添加。當節點發生孤立狀態時，會拋出對應的叢集故障。



== 儲存效率

Netapp SolidFire儲存叢集利用重複資料刪除、壓縮和精簡配置來減少儲存磁碟區所需的實體儲存空間。

* *壓縮*
+
壓縮透過將資料塊組合成壓縮組來減少磁碟區所需的實體儲存空間，每個壓縮組都作為一個單獨的區塊儲存。

* *去重*
+
資料去重透過丟棄重複的資料塊來減少磁碟區所需的實體儲存空間。

* *精簡配置*
+
精簡配置磁碟區或 LUN 是指沒有預先預留儲存空間的磁碟區或 LUN。相反，儲存空間是根據需要動態分配的。當磁碟區或 LUN 中的資料被刪除時，可用空間將會釋放回儲存系統。





== 儲存叢集仲裁

Element 軟體從選定的節點建立一個儲存集群，該集群維護一個集群配置的複製資料庫。為了維持叢集的彈性，叢集整合至少需要三個節點參與。
