---
permalink: concepts/concept_solidfire_concepts_nodes.html 
sidebar: sidebar 
keywords: what is, node, management node, storage node, fibre channel, state, pending, active 
summary: 節點是組成叢集的硬件，可以作為區塊儲存或運算資源進行存取。 
---
= 節點
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
節點是硬體或虛擬資源，它們被分組到一個叢集中，以提供區塊儲存和運算能力。

NetApp Element軟體定義了叢集中的各種節點角色。節點角色類型如下：

* <<管理節點>>
* <<儲存節點>>
* <<光纖通道節點>>


<<節點運行狀態,節點狀態>>因聚類關聯而異。



== 管理節點

管理節點是一台虛擬機，用於升級和提供系統服務，包括監控和遙測、管理叢集資產和設定、運行系統測試和實用程序，以及啟用NetApp支援以進行故障排除。link:../concepts/concept_intro_management_node.html["了解更多"]



== 儲存節點

SolidFire儲存節點是一個伺服器，其中包含一組驅動器，這些驅動器透過 Bond10G 網路介面相互通訊。節點中的磁碟機包含用於資料儲存和資料管理的區塊空間和元資料空間。每個節點都包含NetApp Element軟體的出廠鏡像。

儲存節點具有以下特點：

* 每個節點都有一個唯一的名稱。如果管理員未指定節點名稱，則預設為 SF-XXXX，其中 XXXX 是系統產生的四個隨機字元。
* 每個節點都有自己的高效能非揮發性隨機存取記憶體（NVRAM）寫入緩存，以提高整體系統效能並降低寫入延遲。
* 每個節點都連接到兩個網絡，儲存網路和管理網絡，每個網路都有兩個獨立的鏈路，以實現冗餘和提高效能。每個節點在每個網路上都需要一個IP位址。
* 您可以建立一個包含新儲存節點的集群，或向現有集群新增儲存節點，以提高儲存容量和效能。
* 您可以隨時向叢集中新增或刪除節點，而不會中斷服務。




== 光纖通道節點

SolidFire光纖通道節點提供與光纖通道交換器的連接，您可以將光纖通道用戶端連接到該交換器。光纖通道節點可作為光纖通道和 iSCSI 協定之間的協定轉換器；這可讓您將光纖通道連接新增至任何新的或現有的SolidFire叢集。

光纖通道節點具有以下特點：

* 光纖通道交換器管理光纖網路狀態，提供最佳化的互連。
* 兩個連接埠之間的流量僅透過交換器傳輸；不會傳輸到任何其他連接埠。
* 單一連接埠故障是孤立的，不會影響其他連接埠的運作。
* 在一個網路結構中，多對連接埠可以同時進行通訊。




== 節點運行狀態

根據配置層級的不同，節點可以處於幾種狀態之一。

* *可用的*
+
該節點沒有關聯的叢集名稱，也尚未成為叢集的一部分。

* *待辦的*
+
節點已配置完畢，可以加入指定的叢集。

+
訪問該節點無需身份驗證。

* *待啟動*
+
系統正在節點上安裝相容的 Element 軟體。完成後，節點將變為活動狀態。

* *積極的*
+
該節點正在參與叢集。

+
修改節點需要進行身份驗證。



在這些狀態下，有些欄位是唯讀的。



== 查找更多信息

* https://docs.netapp.com/us-en/element-software/index.html["SolidFire和 Element 軟體文檔"]
* https://docs.netapp.com/us-en/vcp/index.html["NetApp Element vCenter Server 插件"^]

