---
permalink: storage/concept_data_manage_vvol_work_virtual_volumes.html 
sidebar: sidebar 
keywords: virtual volume, configure vvols, use UI to manage 
summary: 您可以使用 Element UI 查看虛擬磁碟區及其關聯的儲存容器、協定端點、綁定和主機的資訊並執行相關任務。 
---
= 使用虛擬卷
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 Element UI 查看虛擬磁碟區及其關聯的儲存容器、協定端點、綁定和主機的資訊並執行相關任務。

NetApp Element軟體儲存系統出廠時預設停用虛擬磁碟區 (VVols) 功能。您必須透過 Element UI 手動啟用 vSphere VVol 功能，此操作為一次性任務。

啟用 VVol 功能後，使用者介面中會出現一個 VVols 選項卡，提供與 VVols 相關的監控和有限的管理選項。此外，一個名為 VASA Provider 的儲存端軟體元件可作為 vSphere 的儲存感知服務。大多數 VVols 命令（例如 VVol 建立、複製和編輯）由 vCenter Server 或 ESXi 主機發起，並由 VASA Provider 轉換為 Element 軟體儲存系統的 Element API。可以使用 Element UI 發起建立、刪除和管理儲存容器以及刪除虛擬磁碟區的命令。

使用 Element 軟體儲存系統的虛擬磁碟區功能所需的大部分設定都在 vSphere 中完成。請參閱《VMware vSphere Virtual Volumes for SolidFire Storage Configuration Guide》以在 vCenter 中註冊 VASA Provider、建立和管理 VVol 資料儲存以及根據策略管理儲存。


NOTE: 對於 Element 12.5 及更早版本，請勿向單一 vCenter 執行個體註冊多個NetApp Element VASA 提供者。如果新增了第二個NetApp Element VASA 提供程序，則所有 VVOL 資料儲存都將無法存取。


NOTE: 如果您已將 VASA 提供者註冊至 vCenter，則可透過升級修補程式取得多個 vCenter 的 VASA 支援。若要安裝，請從以下位置下載 VASA39 .tar.gz 檔案： https://mysupport.netapp.com/products/element_software/VASA39/index.html["NetApp軟體下載"]前往現場並按照清單上的說明進行操作。 NetApp Element VASA 提供者使用NetApp憑證。透過此補丁，vCenter 可以直接使用未經修改的證書，以支援多個 vCenter 用於 VASA 和 VVols。請勿修改證書。  VASA 不支援自訂 SSL 憑證。



== 查找更多信息

* xref:task_data_manage_vvol_enable_virtual_volumes.adoc[啟用虛擬磁碟區]
* xref:task_data_manage_vvol_view_virtual_volume_details.adoc[查看虛擬卷詳情]
* xref:task_data_manage_vvol_delete_a_virtual_volume.adoc[刪除虛擬卷]
* xref:concept_data_manage_vvol_manage_storage_containers.adoc[建立一個儲存容器]
* xref:concept_data_manage_vvol_manage_storage_containers.adoc[編輯儲存容器]
* xref:concept_data_manage_vvol_manage_storage_containers.adoc[刪除儲存容器]
* xref:concept_data_manage_vvol_protocol_endpoints.adoc[協定端點]
* xref:concept_data_manage_vvol_bindings.adoc[綁定]
* xref:reference_data_manage_vvol_host_details.adoc[房東詳情]

