---
permalink: storage/concept_monitor_understand_cluster_fullness_levels.html 
sidebar: sidebar 
keywords: cluster fullness levels, understanding, fullness levels 
summary: 執行 Element 軟體的叢集會在叢集容量不足時產生叢集故障，以警告儲存管理員。叢集填滿程度分為三個級別，所有這些級別都會顯示在NetApp Element UI 中：警告、錯誤和嚴重。 
---
= 了解集群填充程度
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
執行 Element 軟體的叢集會在叢集容量不足時產生叢集故障，以警告儲存管理員。叢集填滿程度分為三個級別，所有這些級別都會顯示在NetApp Element UI 中：警告、錯誤和嚴重。

系統使用 BlockClusterFull 錯誤代碼來警告叢集區塊儲存已滿。您可以在 Element UI 的「警報」標籤中查看叢集滿載嚴重程度。

以下列表包含有關 BlockClusterFull 嚴重程度的資訊：

* *警告*
+
這是一個客戶可設定的警告，當叢集的區塊容量接近錯誤嚴重等級時，該警告會顯示。預設情況下，此等級設定為比錯誤等級低 3%，可透過 Element UI 和 API 進行調整。您必須盡快增加容量或釋放容量。

* *錯誤*
+
當叢集處於這種狀態時，如果一個節點遺失，叢集中將沒有足夠的容量來重建雙螺旋資料保護。當叢集處於此狀態時，所有新磁碟區的建立、複製和快照操作都會被封鎖。任何叢集都不應處於這種安全或建議的狀態。您必須增加容量或立即釋放容量。

* *批判的*
+
出現此嚴重錯誤是因為叢集資源已 100% 使用。它處於唯讀狀態，無法與叢集建立新的 iSCSI 連線。達到這個階段後，您必須立即釋放或增加更多容量。



系統使用 MetadataClusterFull 錯誤代碼來警告叢集元資料儲存空間已滿。您可以在 Element UI 的「報告」標籤的「概覽」頁面上的「叢集容量」部分查看叢集元資料儲存已滿情況。

以下列表包含有關 MetadataClusterFull 嚴重程度的資訊：

* *警告*
+
這是一個客戶可設定的警告，當叢集的元資料容量接近錯誤嚴重等級時，該警告會顯示。預設情況下，此等級設定為比錯誤等級低 3%，可透過 Element API 進行調整。您必須盡快增加容量或釋放容量。

* *錯誤*
+
當叢集處於這種狀態時，如果一個節點遺失，叢集中將沒有足夠的容量來重建雙螺旋資料保護。當叢集處於此狀態時，所有新磁碟區的建立、複製和快照操作都會被封鎖。任何叢集都不應處於這種安全或建議的狀態。您必須增加容量或立即釋放容量。

* *批判的*
+
出現此嚴重錯誤是因為叢集資源已 100% 使用。它處於唯讀狀態，無法與叢集建立新的 iSCSI 連線。達到這個階段後，您必須立即釋放或增加更多容量。




NOTE: 以下內容適用於雙節點叢集閾值：

* 元資料完整性錯誤率比臨界值低 20%。
* 區塊容量不足錯誤是指比臨界容量少 1 個區塊驅動器（包括閒置容量）；這表示比臨界容量少了 2 個區塊磁碟機的容量。

