---
permalink: storage/concept_troubleshoot_basic_mdss_drive_troubleshooting.html 
sidebar: sidebar 
keywords: mdss drives, troubleshoot, multi-drive slice service 
summary: 如果一個或兩個元資料磁碟機發生故障，您可以透過將元資料（或切片）磁碟機重新新增至叢集來還原它們。如果節點上已啟用 MDSS 功能，則可以在NetApp Element UI 中執行復原操作。 
---
= MDSS驅動器基本故障排除
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果一個或兩個元資料磁碟機發生故障，您可以透過將元資料（或切片）磁碟機重新新增至叢集來還原它們。如果節點上已啟用 MDSS 功能，則可以在NetApp Element UI 中執行復原操作。

如果節點中的一個或兩個元資料磁碟機發生故障，切片服務將關閉，並且來自兩個磁碟機的資料將備份到節點中的不同磁碟機。

以下場景概述了可能出現的故障情況，並提供了糾正問題的基本建議：



== 系統切片驅動器故障

* 在這種情況下，插槽 2 經過驗證後恢復為可用狀態。
* 必須先重新安裝系統切片驅動器，才能恢復切片服務。
* 當系統分割區驅動器可用時，您應該更換系統分割區驅動器，同時新增該磁碟機和插槽 2 磁碟機。



NOTE: 你不能單獨將硬碟加入插槽 2 作為元資料硬碟。必須同時將兩個硬碟加入節點中。



== 插槽 2 故障

* 在這種情況下，系統切片驅動器經過驗證後恢復到可用狀態。
* 當插槽 2 可用時，應將插槽 2 更換為備用硬碟，同時新增系統切片硬碟和插槽 2 硬碟。




== 系統切片驅動器和插槽 2 故障

* 您應該將系統分割區磁碟機和插槽 2 都更換為備用磁碟機。當兩個硬碟都可用時，同時新增系統切片硬碟和插槽 2 硬碟。




== 操作順序

* 以備用硬碟取代故障的硬體硬碟（如果兩個硬碟都發生故障，則兩個硬碟都需更換）。
* 當磁碟機重新載入完畢且處於可用狀態時，將其重新新增至叢集中。




== 驗證操作

* 確認插槽 0（或內部）和插槽 2 中的磁碟機在「活動磁碟機」清單中被辨識為元資料磁碟機。
* 確認所有切片平衡已完成（至少 30 分鐘內事件日誌中沒有進一步移動切片的訊息）。




== 更多資訊

xref:task_troubleshoot_add_mdss_drives.adoc[新增 MDSS 驅動器]
