---
permalink: storage/concept_data_manage_vvol_manage_storage_containers.html 
sidebar: sidebar 
keywords: storage container, storage containers, about storage containers, cluster, vvols, create, view details, chap, edit, delete 
summary: 儲存容器是在執行 Element 軟體的叢集上建立的 vSphere 資料儲存表示。 
---
= 管理儲存容器
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
儲存容器是在執行 Element 軟體的叢集上建立的 vSphere 資料儲存表示。

建立儲存容器並將其與NetApp Element帳戶關聯。在 Element 儲存體上建立的儲存容器在 vCenter 和 ESXi 中顯示為 vSphere 資料儲存體。儲存容器不會在 Element 儲存空間上分配任何空間。它們的作用只是將虛擬磁碟區在邏輯上關聯起來。

每個叢集最多支援四個儲存容器。要啟用 VVols 功能，至少需要一個儲存容器。



== 建立一個儲存容器

您可以在 Element UI 中建立儲存容器，並在 vCenter 中發現它們。要開始配置 VVol 支援的虛擬機，您必須至少建立一個儲存容器。

開始之前，請在叢集的 Element UI 中啟用 VVols 功能。

.步驟
. 選擇 *VVols* > *儲存容器*。
. 點擊「建立儲存容器」按鈕。
. 在「建立新儲存容器」對話方塊中輸入儲存容器資訊：
+
.. 請輸入儲存容器的名稱。
.. 配置 CHAP 的發起方金鑰和目標金鑰。
+

TIP: 將 CHAP 設定欄位留空以自動產生密鑰。

.. 點擊「建立儲存容器」按鈕。


. 確認新儲存容器出現在「儲存容器」子選項卡的清單中。
+

NOTE: 由於NetApp Element帳戶 ID 會自動建立並指派給儲存容器，因此無需手動建立帳戶。





== 查看儲存容器詳情

在 VVols 標籤的「儲存容器」頁面上，您可以查看叢集上所有活動儲存容器的資訊。

* *帳號 ID*：與儲存容器關聯的NetApp Element帳號的 ID。
* *名稱*：儲存容器的名稱。
* *狀態*：儲存容器的狀態。可能的值：
+
** 活動狀態：儲存容器正在使用中。
** 已鎖定：儲存容器已鎖定。


* *PE 類型*：協定端點類型（SCSI 是 Element 軟體唯一可用的協定）。
* *儲存容器 ID*：虛擬磁碟區儲存容器的 UUID。
* *活動虛擬卷*：與儲存容器相關的活動虛擬卷的數量。




== 查看單一儲存容器的詳細信息

您可以透過在 VVols 標籤的「儲存容器」頁面上選擇單一儲存容器來查看其儲存容器資訊。

* *帳號 ID*：與儲存容器關聯的NetApp Element帳號的 ID。
* *名稱*：儲存容器的名稱。
* *狀態*：儲存容器的狀態。可能的值：
+
** 活動狀態：儲存容器正在使用中。
** 已鎖定：儲存容器已鎖定。


* *CHAP發起者秘密*：發起者獨有的CHAP秘密。
* *CHAP目標秘密*：針對目標的獨特CHAP秘密。
* *儲存容器 ID*：虛擬磁碟區儲存容器的 UUID。
* *協定端點類型*：指示協定端點類型（SCSI 是唯一可用的協定）。




== 編輯儲存容器

您可以在 Element UI 中修改儲存容器的 CHAP 驗證。

. 選擇 *VVols* > *儲存容器*。
. 點選要編輯的儲存容器旁的「操作」圖示。
. 在出現的選單中，選擇“編輯”。
. 在 CHAP 設定中，編輯用於驗證的發起方金鑰和目標金鑰憑證。
+

TIP: 如果您不變更 CHAP 設定憑證，則它們將保持不變。如果將憑證欄位留空，系統會自動產生新的金鑰。

. 點選「儲存變更」。




== 刪除儲存容器

您可以從 Element 使用者介面刪除儲存容器。

.你需要什麼
確保所有虛擬機器都已從 VVol 資料儲存中刪除。

.步驟
. 選擇 *VVols* > *儲存容器*。
. 點選要刪除的儲存容器旁的「操作」圖示。
. 在出現的選單中，選擇“刪除”。
. 確認操作。
. 刷新「儲存容器」子標籤中的儲存容器列表，以確認儲存容器已被刪除。

