---
permalink: storage/concept_system_manage_manage_cluster_administrator_users.html 
sidebar: sidebar 
keywords: element, solidfire, cluster admin, account, create, change, configure, administrator access, edit permissions, change passwords 
summary: 您可以管理SolidFire儲存系統的叢集管理員帳戶。可用的叢集管理員管理功能包括建立、刪除和編輯叢集管理員帳戶，變更叢集管理員密碼，以及設定 LDAP 設定以管理系統使用者存取權限。 
---
= 管理叢集管理員使用者帳戶
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以管理SolidFire儲存系統的叢集管理員帳戶，方法是建立、刪除和編輯叢集管理員帳戶，變更叢集管理員密碼，以及設定 LDAP 設定以管理系統使用者的存取權限。



== 儲存叢集管理員帳戶類型

在執行NetApp Element軟體的儲存叢集中，可以存在兩種類型的管理員帳戶：主叢集管理員帳戶和叢集管理員帳戶。

* *主集群管理員帳戶*
+
此管理員帳戶是在建立叢集時建立的。此帳戶是叢集中具有最高存取權限的主要管理帳戶。該帳號類似於 Linux 系統中的 root 使用者。您可以變更此管理員帳戶的密碼。

* *群集管理員帳戶*
+
您可以授予叢集管理員帳戶有限的管理權限，使其能夠在叢集內執行特定任務。指派給每個叢集管理員帳戶的憑證用於驗證儲存系統中的 API 和 Element UI 請求。




NOTE: 要透過每個節點的 UI 存取叢集中的活動節點，需要本機（非 LDAP）叢集管理員帳戶。存取尚未加入叢集的節點不需要帳戶憑證。



== 查看集群管理員詳細信息

. 若要建立叢集範圍（非 LDAP）的叢集管理員帳戶，請執行下列操作：
+
.. 點選“使用者”>“集群管理員”。


. 在「使用者」標籤的「叢集管理員」頁面上，您可以查看以下資訊。
+
** *ID*：指派給群集管理員帳戶的順序編號。
** *使用者名稱*：建立叢集管理員帳戶時賦予該帳戶的名稱。
** *存取權限*：指派給使用者帳號的使用者權限。可能的值：
+
*** 讀
*** 報道
*** 節點
*** 驅動
*** 卷
*** 帳戶
*** 集群管理員
*** 行政人員
*** 支援管理員




+
[NOTE]
====
所有權限均對管理員存取類型可用。

透過 API 可以存取 Element UI 中沒有的某些存取類型。

====
+
** *類型*：叢集管理員的類型。可能的值：
+
*** 簇
*** LDAP


** *屬性*：如果群集管理員帳戶是使用 Element API 建立的，則此列顯示使用該方法設定的任何名稱-值對。
+
看link:../api/concept_element_api_about_the_api.html["NetApp Element軟體 API 參考"]。







== 建立叢集管理員帳戶

您可以建立新的叢集管理員帳戶，並授予其權限以允許或限制對儲存系統特定區域的存取。設定叢集管理員帳戶權限時，系統會授予您未指派給叢集管理員的任何權限的唯讀權限。

如果要建立 LDAP 叢集管理員帳戶，請確保在開始之前已在叢集上設定 LDAP。

link:concept_system_manage_manage_ldap.html["使用 Element 使用者介面啟用 LDAP 身份驗證"]

之後您可以變更叢集管理員帳戶的報表、節點、磁碟機、磁碟區、帳戶和叢集級存取權限。啟用權限後，系統會為該等級指派寫入權限。系統會授予管理員使用者唯讀權限，僅對您未選擇的等級有效。

之後您也可以刪除系統管理員建立的任何叢集管理員使用者帳戶。您無法刪除建立叢集時建立的主集群管理員帳戶。

. 若要建立叢集範圍（非 LDAP）的叢集管理員帳戶，請執行下列操作：
+
.. 點選“使用者”>“集群管理員”。
.. 點選「建立集群管理員」。
.. 選擇*叢集*使用者類型。
.. 輸入帳號和密碼，並確認密碼。
.. 選擇要套用於帳戶的使用者權限。
.. 選取此複選框即表示您同意最終使用者許可協議。
.. 點選「建立集群管理員」。


. 若要在 LDAP 目錄中建立叢集管理員帳戶，請執行下列操作：
+
.. 點選“集群”>“LDAP”。
.. 請確保已啟用 LDAP 身份驗證。
.. 點擊“測試用戶身份驗證”，複製顯示的用戶或用戶所屬群組之一的專有名稱，以便稍後貼上。
.. 點選“使用者”>“集群管理員”。
.. 點選「建立集群管理員」。
.. 選擇 LDAP 使用者類型。
.. 在「專有名稱」欄位中，依照文字方塊中的範例輸入使用者或群組的完整專有名稱。或者，從你之前複製的專有名稱中貼上。
+
如果專有名稱屬於某個群組，則 LDAP 伺服器上該群組的任何成員使用者都將擁有此管理員帳戶的權限。

+
若要新增 LDAP 叢集管理員使用者或群組，使用者名稱的通用格式為「`LDAP:<完整可分辨名稱>`」。

.. 選擇要套用於帳戶的使用者權限。
.. 選取此複選框即表示您同意最終使用者許可協議。
.. 點選「建立集群管理員」。






== 編輯集群管理員權限

您可以變更叢集管理員帳戶的報表、節點、磁碟機、磁碟區、帳戶和叢集層級存取權限。啟用權限後，系統會為該等級指派寫入權限。系統會授予管理員使用者唯讀權限，僅對您未選擇的等級有效。

. 點選“使用者”>“集群管理員”。
. 按一下要編輯的叢集管理員旁邊的「操作」圖示。
. 按一下“*編輯*”。
. 選擇要套用於帳戶的使用者權限。
. 點選「儲存變更」。




== 更改叢集管理員帳戶的密碼

您可以使用 Element UI 變更叢集管理員密碼。

. 點選“使用者”>“集群管理員”。
. 按一下要編輯的叢集管理員旁邊的「操作」圖示。
. 按一下“*編輯*”。
. 在「更改密碼」欄位中，輸入新密碼並確認。
. 點選「儲存變更」。


.相關資訊
* link:../api/reference_element_api_app_b_access_control.html["了解 Element API 可用的存取類型"]
* link:concept_system_manage_manage_ldap.html["使用 Element 使用者介面啟用 LDAP 身份驗證"]
* link:concept_system_manage_manage_ldap.html["禁用 LDAP"]
* https://docs.netapp.com/us-en/vcp/index.html["NetApp Element vCenter Server 插件"^]

