---
permalink: storage/reference_monitor_cluster_fault_codes.html 
sidebar: sidebar 
keywords: cluster fault codes, alerts, error codes, view 
summary: 系統透過產生故障碼來報告錯誤或可能感興趣的狀態，該故障碼列在「警報」頁面上。這些代碼可以幫助您確定係統的哪個組件收到了警報以及警報產生的原因。 
---
= 叢集故障碼
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
系統透過產生故障碼來報告錯誤或可能感興趣的狀態，該故障碼列在「警報」頁面上。這些代碼可以幫助您確定係統的哪個組件收到了警報以及警報產生的原因。

以下列表概述了不同類型的程式碼：

* *authenticationServiceFault*
+
一個或多個叢集節點上的身份驗證服務未如預期運作。

+
請聯絡NetApp支援部門尋求協助。

* *可用虛擬網路IP位址少*
+
IP位址區塊中的虛擬網路位址數量較少。

+
若要解決此故障，請在虛擬網路位址區塊中新增更多 IP 位址。

* *blockClusterFull*
+
沒有足夠的可用區塊儲存空間來應對單一節點的故障。有關叢集填充程度的詳細信息，請參閱 GetClusterFullThreshold API 方法。此集群故障表示存在以下情況之一：

+
** stage3Low（警告）：已超過使用者定義的閾值。調整叢集已滿設定或新增更多節點。
** stage4Critical（錯誤）：沒有足夠的空間從 1 個節點故障中恢復。不允許建立磁碟區、快照和克隆。
** stage5完全消耗（嚴重）1；不允許寫入或建立新的iSCSI連線。現有 iSCSI 連線將保持不變。在叢集增加更多容量之前，寫入操作將會失敗。


+
若要解決此故障，請清除或刪除磁碟區，或為儲存叢集新增另一個儲存節點。

* *blocksDegraded*
+
由於故障，資料塊不再完全複製。

+
|===


| 嚴重程度 | 描述 


 a| 
警告
 a| 
只有兩份完整的資料塊副本可供存取。



 a| 
錯誤
 a| 
只能存取到資料塊的完整副本。



 a| 
批判的
 a| 
無法取得完整的資料塊副本。

|===
+
*注意：*此警告狀態只會在三螺旋系統中出現。

+
若要解決此故障，請恢復任何離線節點或封鎖服務，或聯絡NetApp支援尋求協助。

* *blockServiceTooFull*
+
一個區塊服務佔用了過多的空間。

+
若要解決此故障，請增加已配置容量。

* *阻止服務不健康*
+
偵測到某個阻塞服務運作狀況不佳：

+
** 嚴重程度 = 警告：不採取任何措施。此警告期將在 cTimeUntilBSIsKilledMSec=330000 毫秒後到期。
** 嚴重性 = 錯誤：系統正在自動停用資料並將其資料重新複製到其他正常磁碟機。
** 嚴重性 = 嚴重：多個節點上的區塊服務發生故障，故障數量大於或等於複製計數（雙螺旋為 2）。資料不可用，箱體同步將無法完成。
+
檢查網路連線問題和硬體錯誤。如果特定硬體組件發生故障，則會出現其他故障。當阻塞服務恢復正常或服務停用後，故障將會清除。



* *BmcSelfTest失敗*
+
基板管理控制器（BMC）自我檢測失敗。

+
請聯絡NetApp支援部門尋求協助。

+
在升級到 Element 12.5 或更高版本期間， `BmcSelfTestFailed`如果節點上的BMC已發生故障，或節點的BMC在升級過程中發生故障，則不會產生故障。升級過程中自檢失敗的 BMC 將發出警告 `BmcSelfTestFailed`整個叢集升級完成後出現警告故障。

* *時鐘偏差超過故障閾值*
+
叢集主節點與提供令牌的節點之間的時間偏差超過了建議的閾值。儲存叢集無法自動修正節點間的時間偏差。

+
若要解決此故障，請使用網路內部的 NTP 伺服器，而不是安裝預設伺服器。如果您使用的是內部 NTP 伺服器，請聯絡NetApp支援部門尋求協助。

* *集群無法同步*
+
空間不足，離線區塊儲存磁碟機上的資料無法同步到仍在活動的磁碟機。

+
若要解決此故障，請增加儲存空間。

* *集群已滿*
+
儲存叢集中已無可用儲存空間。

+
若要解決此故障，請增加儲存空間。

* *叢集IOPS配置過高*
+
集群IOPS配置過高。所有最小 QoS IOPS 總和大於群集的預期 IOPS。無法同時為所有捲維持最低服務品質要求。

+
若要解決此問題，請降低磁碟區的最小 QoS IOPS 設定。

* *CPU熱事件閾值*
+
一個或多個 CPU 上的 CPU 熱事件數量超過了設定的閾值。

+
如果在十分鐘內未偵測到新的 CPU 過熱事件，則警告將自動解除。

* *停用驅動器安全失敗*
+
叢集未配置為啟用磁碟機安全性（靜態加密），但至少有一個磁碟機啟用了磁碟機安全，這表示停用這些磁碟機上的磁碟機安全性失敗了。此故障被記錄為「警告」等級。

+
要解決此故障，請檢查故障詳細信息，找出無法停用驅動器安全功能的原因。可能的原因有：

+
** 無法取得加密金鑰，請調查金鑰存取或外部金鑰伺服器方面的問題。
** 驅動器上的停用操作失敗，請確定是否可能取得了錯誤的密鑰。


+
如果以上兩種情況都不是故障原因，則可能需要更換硬碟。

+
即使提供了正確的身份驗證金鑰，如果磁碟機無法成功停用安全功能，您也可以嘗試還原該磁碟機。若要執行此操作，請將驅動器移至「可用」位置，從系統中移除驅動器，對驅動器執行安全性擦除，然後將其移回「活動」位置。

* *已斷開連接的集群對*
+
叢集對已斷開連接或配置錯誤。

+
檢查集群之間的網路連線。

* *已斷開連線的遠端節點*
+
遠端節點已斷開連接或配置錯誤。

+
檢查節點間的網路連線情況。

* *已斷線的SnapMirror端點*
+
遠端SnapMirror端點已中斷連線或設定錯誤。

+
檢查叢集與遠端 SnapMirrorEndpoint 之間的網路連線。

* *可駕車*
+
集群中有一個或多個驅動器可用。一般來說，所有叢集都應該新增所有驅動器，並且沒有驅動器處於可用狀態。如果此故障意外出現，請聯絡NetApp支援。

+
若要解決此故障，請將所有可用磁碟機新增至儲存叢集。

* *驅動器故障*
+
當一個或多個磁碟機發生故障時，叢集會傳回此故障，表示存在下列情況之一：

+
** 驅動器管理器無法存取該驅動器。
** 切片或區塊服務失敗次數過多，可能是由於磁碟機讀取或寫入失敗造成的，無法重新啟動。
** 硬碟遺失。
** 節點的主服務無法存取（節點中的所有磁碟機均被視為遺失/故障）。
** 硬碟已被鎖定，無法取得硬碟的身份驗證金鑰。
** 驅動器已鎖定，解鎖操作失敗。
+
要解決此問題：

** 檢查節點的網路連線情況。
** 更換硬碟。
** 請確保身份驗證金鑰可用。


* *驅動器健康故障*
+
硬碟未通過 SMART 健康檢查，因此，硬碟的功能降低。此故障的嚴重程度等級為「嚴重」：

+
** 序號為 <序號> 的驅動器，位於插槽：<節點插槽><驅動器插槽>，SMART 整體健康檢查未通過。


+
若要解決此故障，請更換驅動器。

* *驅動磨損故障*
+
硬碟剩餘壽命已低於閾值，但仍可正常運作。此故障有兩種嚴重程度等級：嚴重和警告。

+
** 序號為<序號>的驅動器位於插槽：<節點插槽><驅動器插槽>，磨損程度嚴重。
** 序號為<序號>的驅動器位於插槽：<節點插槽><驅動器插槽>，磨損儲備較低。
+
若要解決此故障，請盡快更換硬碟。



* *重複集群主候選對象*
+
偵測到多個儲存叢集主節點候選者。

+
請聯絡NetApp支援部門尋求協助。

* *啟用磁碟機安全性失敗*
+
叢集配置為需要磁碟機安全性（靜態加密），但至少有一個磁碟機無法啟用磁碟機安全性。此故障被記錄為「警告」等級。

+
要解決此故障，請檢查故障詳細信息，找出無法啟用驅動器安全功能的原因。可能的原因有：

+
** 無法取得加密金鑰，請調查金鑰存取或外部金鑰伺服器方面的問題。
** 驅動器啟用操作失敗，請確定是否可能取得了錯誤的密鑰。如果以上兩種情況都不是故障原因，則可能需要更換硬碟。


+
即使提供了正確的身份驗證金鑰，如果磁碟機無法成功啟用安全功能，您也可以嘗試還原該磁碟機。若要執行此操作，請將驅動器移至「可用」位置，從系統中移除驅動器，對驅動器執行安全性擦除，然後將其移回「活動」位置。

* *合奏退化*
+
一個或多個叢集節點的網路連接或電源已遺失。

+
若要解決此故障，請恢復網路連線或電源。

* *例外*
+
報告的故障並非例行故障。這些故障不會自動從故障佇列中清除。

+
請聯絡NetApp支援部門尋求協助。

* *空間已滿*
+
阻塞服務不回應資料寫入請求。這會導致切片服務沒有足夠的空間來儲存失敗的寫入操作。

+
若要解決此故障，請恢復區塊服務功能，以允許寫入正常繼續，並將故障空間從切片服務中刷新。

* *風扇感應器*
+
風扇感知器故障或缺失。

+
若要解決此故障，請更換任何故障硬體。

* *光纖通道存取降級*
+
一段時間內，光纖通道節點無法透過其儲存 IP 回應儲存叢集中的其他節點。在這種狀態下，節點將被視為無回應，並產生叢集故障。

+
檢查網路連線。

* *光纖通道存取不可用*
+
所有光纖通道節點均無響應。顯示節點 ID。

+
檢查網路連線。

* *光纖通道主動式IxL*
+
IxL Nexus 的數量已接近每個光纖通道節點 8000 個活動會話的支援上限。

+
** 最佳實踐限制為 5500。
** 警告限值為 7500。
** 最大限制（不強制執行）為 8192。


+
要解決此故障，請將 IxL Nexus 數量減少到 5500 以下的最佳實踐限制。

* *光纖通道配置*
+
此集群故障表示存在以下情況之一：

+
** PCI 插槽上意外地出現了一個光纖通道連接埠。
** 出現了一款意想不到的光纖通道 HBA 型號。
** 光纖通道 HBA 的韌體有問題。
** 光纖通道連接埠未上線。
** 配置光纖通道直通功能時一直有問題。


+
請聯絡NetApp支援部門尋求協助。

* *光纖通道IOPS*
+
叢集中光纖通道節點的總 IOPS 計數已接近 IOPS 限制。限制條件是：

+
** FC0025：每個光纖通道節點在 4K 區塊大小下 IOPS 限制為 450K。
** FCN001：每個光纖通道節點在 4K 區塊大小下，OPS 限制為 625K。


+
若要解決此故障，請在所有可用的光纖通道節點上平衡負載。

* *fibreChannelStaticIxL*
+
IxL Nexus 的數量已接近每個光纖通道節點支援的靜態會話數上限 16000。

+
** 最佳實踐限制為 11000。
** 警告限值為 15000。
** 最大限制（強制執行）為 16384。


+
要解決此故障，請將 IxL Nexus 數量減少到 11000 以下的最佳實踐限制。

* *fileSystemCapacityLow*
+
其中一個檔案系統空間不足。

+
若要解決此故障，請增加檔案系統的容量。

* *fileSystemIsReadOnly*
+
檔案系統已進入唯讀模式。

+
請聯絡NetApp支援部門尋求協助。

* *fips驅動器不符*
+
將非 FIPS 磁碟機實體插入支援 FIPS 的儲存節點中，或將 FIPS 磁碟機實體插入非 FIPS 儲存節點。每個節點產生一個故障報告，列出所有受影響的驅動器。

+
若要解決此故障，請移除或更換有問題的不匹配的硬碟。

* *fipsDrivesOutOfCompliance*
+
系統偵測到啟用 FIPS 磁碟機功能後，靜態資料加密功能會停用。當啟用 FIPS 磁碟機功能且儲存叢集中存在非 FIPS 磁碟機或節點時，也會產生此故障。

+
若要解決此故障，請啟用靜態資料加密或從儲存叢集移除非 FIPS 硬體。

* *fips自我檢測失敗*
+
FIPS 子系統在自我檢測過程中偵測到故障。

+
請聯絡NetApp支援部門尋求協助。

* *硬體配置不符*
+
此集群故障表示存在以下情況之一：

+
** 配置與節點定義不符。
** 此類型的節點使用了不正確的驅動器容量。
** 偵測到不支援的驅動器。一個可能的原因是已安裝的 Element 版本無法識別此磁碟機。建議更新此節點上的 Element 軟體。
** 驅動器韌體不匹配。
** 驅動器加密功能狀態與節點不符。


+
請聯絡NetApp支援部門尋求協助。

* *idPCertificateExpiration*
+
叢集的服務提供者 SSL 憑證（用於第三方身分提供者 (IdP)）即將到期或已到期。此故障根據緊急程度採用以下嚴重程度：

+
|===


| 嚴重程度 | 描述 


 a| 
警告
 a| 
證書有效期限為30天。



 a| 
錯誤
 a| 
證書有效期限為7天。



 a| 
批判的
 a| 
證書將在3天內過期或已過期。

|===
+
若要解決此故障，請在 SSL 憑證過期前更新它。使用 UpdateIdpConfiguration API 方法 `refreshCertificateExpirationTime=true`提供更新後的SSL憑證。

* *不一致的鍵結模式*
+
VLAN 設備上的綁定模式缺失。此故障將顯示預期的鍵合模式和目前使用的鍵合模式。



* *不一致的Mtus*
+
此集群故障表示存在以下情況之一：

+
** Bond1G 不匹配：在 Bond1G 介面上偵測到不一致的 MTU。
** Bond10G 不匹配：在 Bond10G 介面上偵測到不一致的 MTU。


+
此故障會顯示相關節點以及關聯的 MTU 值。

* *路由規則不一致*
+
此介面的路由規則不一致。

* *子網路遮罩不一致*
+
VLAN 設備上的網路遮罩與內部記錄的 VLAN 網路遮罩不符。此故障會顯示預期的網路遮罩和目前使用的網路遮罩。

* *錯誤的BondPortCount*
+
綁定連接埠的數量不正確。

* *無效的已配置光纖通道節點計數*
+
兩個預期的光纖通道節點連接中，有一個連接效能下降。當僅連接一個光纖通道節點時，就會發生此故障。

+
若要解決此故障，請檢查叢集網路連線和網路佈線，並檢查是否有故障服務。如果沒有網路或服務問題，請聯絡NetApp支援部門更換光纖通道節點。

* *irqBalanceFailed*
+
嘗試平衡中斷時發生異常。

+
請聯絡NetApp支援部門尋求協助。

* *kmip證書故障*
+
** 根證書頒發機構（CA）證書即將到期。
+
要解決此故障，請從根 CA 取得一個有效期至少還有 30 天的新證書，並使用 ModifyKeyServerKmip 提供更新後的根 CA 證書。

** 客戶端憑證即將到期。
+
若要解決此故障，請使用 GetClientCertificateSigningRequest 建立一個新的 CSR，對其進行簽名，確保新的到期日期至少還有 30 天，然後使用 ModifyKeyServerKmip 將即將到期的 KMIP 用戶端憑證取代為新憑證。

** 根憑證授權單位（CA）憑證已過期。
+
要解決此故障，請從根 CA 取得一個有效期至少還有 30 天的新證書，並使用 ModifyKeyServerKmip 提供更新後的根 CA 證書。

** 用戶端憑證已過期。
+
若要解決此故障，請使用 GetClientCertificateSigningRequest 建立一個新的 CSR，對其進行簽名，確保新的到期日期至少還有 30 天，然後使用 ModifyKeyServerKmip 將過期的 KMIP 用戶端憑證取代為新憑證。

** 根憑證授權單位（CA）憑證錯誤。
+
若要解決此故障，請檢查是否提供了正確的證書，如有必要，請從根 CA 重新取得證書。使用 ModifyKeyServerKmip 安裝正確的 KMIP 用戶端憑證。

** 客戶端證書錯誤。
+
若要解決此故障，請檢查是否已安裝正確的 KMIP 用戶端憑證。客戶端憑證的根 CA 應該安裝在 EKS 上。使用 ModifyKeyServerKmip 安裝正確的 KMIP 用戶端憑證。



* *kmipServerFault*
+
** 連線失敗
+
若要解決此故障，請檢查外部金鑰伺服器是否正常運作且可透過網路存取。使用 TestKeyServerKimp 和 TestKeyProviderKmip 測試您的連線。

** 身份驗證失敗
+
若要解決此故障，請檢查是否使用了正確的根 CA 和 KMIP 用戶端憑證，以及私鑰和 KMIP 用戶端憑證是否相符。

** 伺服器錯誤
+
若要解決此故障，請檢查錯誤詳情。根據傳回的錯誤訊息，可能需要對外部金鑰伺服器進行故障排除。



* *記憶體Ecc閾值*
+
偵測到大量可修正或不可修正的ECC錯誤。此故障根據緊急程度採用以下嚴重程度：

+
|===


| 事件 | 嚴重程度 | 描述 


 a| 
單一 DIMM cErrorCount 達到 cDimmCorrectableErrWarnThreshold。
 a| 
警告
 a| 
DIMM 記憶體插槽上超過閾值的可修正 ECC 記憶體錯誤：<處理器> <DIMM 插槽>



 a| 
單一 DIMM 的 cErrorCount 會一直高於 cDimmCorrectableErrWarnThreshold，直到 DIMM 的 cErrorFaultTimer 逾時為止。
 a| 
錯誤
 a| 
DIMM 記憶體條上超過閾值的可修正 ECC 記憶體錯誤：<處理器> <DIMM>



 a| 
記憶體控制器報告 cErrorCount 高於 cMemCtlrCorrectableErrWarnThreshold，並且指定了 cMemCtlrCorrectableErrWarnDuration。
 a| 
警告
 a| 
記憶體控制器上超過閾值的可修正ECC記憶體錯誤：<處理器> <記憶體控制器>



 a| 
記憶體控制器報告的 cErrorCount 超過 cMemCtlrCorrectableErrWarnThreshold，直到記憶體控制器的 cErrorFaultTimer 逾時為止。
 a| 
錯誤
 a| 
DIMM 記憶體條上超過閾值的可修正 ECC 記憶體錯誤：<處理器> <DIMM>



 a| 
單一 DIMM 報告的 uErrorCount 大於零，但小於 cDimmUncorrectableErrFaultThreshold。
 a| 
警告
 a| 
DIMM 記憶體上偵測到無法修正的 ECC 記憶體錯誤：<處理器> <DIMM 插槽>



 a| 
單一 DIMM 報告的 uErrorCount 至少為 cDimmUncorrectableErrFaultThreshold。
 a| 
錯誤
 a| 
DIMM 記憶體上偵測到無法修正的 ECC 記憶體錯誤：<處理器> <DIMM 插槽>



 a| 
記憶體控制器報告的 uErrorCount 大於零，但小於 cMemCtlrUncorrectableErrFaultThreshold。
 a| 
警告
 a| 
記憶體控制器上偵測到不可修正的 ECC 記憶體錯誤：<處理器> <記憶體控制器>



 a| 
記憶體控制器報告的 uErrorCount 至少為 cMemCtlrUncorrectableErrFaultThreshold。
 a| 
錯誤
 a| 
記憶體控制器上偵測到不可修正的 ECC 記憶體錯誤：<處理器> <記憶體控制器>

|===
+
若要解決此故障，請聯絡NetApp支援部門尋求協助。

* *記憶體使用閾值*
+
記憶體使用量高於正常水平。此故障根據緊急程度採用以下嚴重程度：

+

NOTE: 有關故障類型的更多詳細信息，請參閱錯誤故障中的“詳細信息”標題。

+
|===


| 嚴重程度 | 描述 


 a| 
警告
 a| 
系統記憶體不足。



 a| 
錯誤
 a| 
系統記憶體嚴重不足。



 a| 
批判的
 a| 
系統記憶體已完全耗盡。

|===
+
若要解決此故障，請聯絡NetApp支援部門尋求協助。

* *metadataClusterFull*
+
可用的元資料儲存空間不足以應付單一節點的遺失。有關叢集填充程度的詳細信息，請參閱 GetClusterFullThreshold API 方法。此集群故障表示存在以下情況之一：

+
** stage3Low（警告）：已超過使用者定義的閾值。調整叢集已滿設定或新增更多節點。
** stage4Critical（錯誤）：沒有足夠的空間從 1 個節點故障中恢復。不允許建立磁碟區、快照和克隆。
** stage5完全消耗（嚴重）1；不允許寫入或建立新的iSCSI連線。現有 iSCSI 連線將保持不變。在叢集增加更多容量之前，寫入操作將會失敗。清除或刪除數據，或新增更多節點。


+
若要解決此故障，請清除或刪除磁碟區，或為儲存叢集新增另一個儲存節點。

* *mtuCheckFailure*
+
網路設備的 MTU 大小配置不正確。

+
若要解決此故障，請確保所有網路介面和交換器連接埠都配置為巨型訊框（MTU 最大可達 9000 位元組）。

* *網路配置*
+
此集群故障表示存在以下情況之一：

+
** 未找到預期的接口。
** 存在重複接口。
** 已設定的介面已關閉。
** 需要重啟網路。


+
請聯絡NetApp支援部門尋求協助。

* *無可用虛擬網路IP位址*
+
此IP位址區塊中沒有可用的虛擬網路位址。

+
** virtualNetworkID # TAG(\###) 沒有可用的儲存 IP 位址。無法向叢集新增其他節點。


+
若要解決此故障，請在虛擬網路位址區塊中新增更多 IP 位址。

* *nodeHardwareFault（網路介面<名稱>已關閉或網路線已拔出）*
+
網路介面故障或網路線被拔出。

+
若要解決此故障，請檢查節點或多個節點的網路連線。

* *nodeHardwareFault（驅動器加密功能狀態與節點中插槽 <節點插槽><驅動器插槽> 內的驅動器的加密功能狀態不符）*
+
硬碟的加密功能與其安裝的儲存節點不符。

* *nodeHardwareFault（此節點類型的<驅動器類型>驅動器容量<實際容量>不正確 - 預期容量>）*
+
儲存節點中包含一個容量與該節點不符的磁碟機。

* *nodeHardwareFault（在插槽<節點插槽><驅動器插槽>中偵測到不支援的驅動器；驅動器統計資訊和健康資訊將無法使用）*
+
儲存節點中包含它不支援的磁碟機。

* *nodeHardwareFault（插槽 <node slot><drive slot> 中的磁碟機應使用韌體版本 <expected version>，但目前使用的是不支援的版本 <actual version>）*
+
儲存節點中包含一個運作不受支援的韌體版本的磁碟機。

* *節點維護模式*
+
一個節點已置於維護模式。此故障根據緊急程度採用以下嚴重程度：

+
|===


| 嚴重程度 | 描述 


 a| 
警告
 a| 
表示該節點仍處於維護模式。



 a| 
錯誤
 a| 
表示維護模式未能停用，很可能是備用電源故障或處於活動狀態所致。

|===
+
若要解決此故障，請在維護完成後停用維護模式。如果錯誤等級故障仍然存在，請聯絡NetApp支援部門尋求協助。

* *nodeOffline*
+
Element軟體無法與指定節點通訊。檢查網路連線。

* *未使用LACP債券模式*
+
LACP 綁定模式未配置。

+
若要解決此故障，請在部署儲存節點時使用 LACP 綁定；如果未啟用或正確配置 LACP，用戶端可能會遇到效能問題。

* *ntp伺服器不可達*
+
儲存叢集無法與指定的 NTP 伺服器通訊。

+
若要解決此故障，請檢查 NTP 伺服器、網路和防火牆的設定。

* *ntpTimeNotInSync*
+
儲存叢集時間與指定的 NTP 伺服器時間相差過大。儲存叢集無法自動修正這種差異。

+
若要解決此故障，請使用網路內部的 NTP 伺服器，而不是安裝預設伺服器。如果您使用的是內部 NTP 伺服器且問題仍然存在，請聯絡NetApp支援部門尋求協助。

* *nvramDeviceStatus*
+
NVRAM設備發生錯誤、正在發生故障或已發生故障。此故障的嚴重程度如下：

+
|===


| 嚴重程度 | 描述 


 a| 
警告
 a| 
硬體偵測到警告。這種情況可能是暫時的，例如溫度警告。

** nvmLifetimeError
** nvmLifetimeStatus
** 能源來源生命週期狀態
** 能源來源溫度狀態
** 警告閾值已超出




 a| 
錯誤
 a| 
硬體偵測到錯誤或嚴重狀態。叢集主控嘗試將切片磁碟機從運作中移除（這將產生一個磁碟機移除事件）。如果輔助分割區服務不可用，則不會移除磁碟機。除了警告等級的錯誤之外，還傳回了以下錯誤：

** NVRAM設備掛載點不存在。
** NVRAM設備分割區不存在。
** NVRAM設備分割區存在，但未掛載。




 a| 
批判的
 a| 
硬體偵測到錯誤或嚴重狀態。叢集主控嘗試將切片磁碟機從運作中移除（這將產生一個磁碟機移除事件）。如果輔助分割區服務不可用，則不會移除磁碟機。

** 持久性喪失
** armStatusSaveNArmed
** csaveStatusError


|===
+
更換節點中任何故障的硬體。如果此方法無法解決問題，請聯絡NetApp支援部門尋求協助。

* *電源錯誤*
+
此集群故障表示存在以下情況之一：

+
** 電源缺失。
** 電源故障。
** 電源輸入缺失或超出範圍。


+
若要解決此故障，請確認所有節點均已提供冗餘電源。請聯絡NetApp支援團隊尋求協助。

* *預留空間已滿*
+
叢集的整體配置容量已滿。

+
若要解決此故障，請新增更多已配置空間，或刪除並清除磁碟區。

* *遠端複製非同步延遲超過限制*
+
配置的非同步複製延遲已超過設定值。檢查集群間的網路連線。

* *遠端副本集群已滿*
+
由於目標儲存叢集已滿，磁碟區已暫停遠端複製。

+
若要解決此故障，請釋放目標儲存叢集上的一些空間。

* *remoteRepSnapshotClusterFull*
+
由於目標儲存叢集已滿，磁碟區已暫停快照的遠端複製。

+
若要解決此故障，請釋放目標儲存叢集上的一些空間。

* *遠端副本快照超出限制*
+
由於目標儲存叢集磁碟區已超出其快照限制，因此磁碟區已暫停遠端快照複製。

+
若要解決此故障，請增加目標儲存叢集上的快照限制。

* *scheduleActionError*
+
一項或多項預定活動已運行，但失敗了。

+
如果計劃的活動再次運行並成功，或者計劃的活動被刪除，或者活動被暫停並恢復，則故障將被清除。

* *感測器讀取失敗*
+
感測器無法與基板管理控制器（BMC）通訊。

+
請聯絡NetApp支援部門尋求協助。

* *服務未運作*
+
所需服務未運作。

+
請聯絡NetApp支援部門尋求協助。

* *sliceServiceTooFull*
+
切片服務的預置容量過少。

+
若要解決此故障，請增加已配置容量。

* *sliceServiceUnhealthy*
+
系統偵測到某個切片服務運作狀況不佳，正在自動停用。

+
** 嚴重程度 = 警告：不採取任何措施。此警告期將在 6 分鐘後結束。
** 嚴重性 = 錯誤：系統正在自動停用資料並將其資料重新複製到其他正常磁碟機。


+
檢查網路連線問題和硬體錯誤。如果特定硬體組件發生故障，則會出現其他故障。當切片服務可存取或服務已停用時，故障將清除。

* *已啟用 SSH*
+
SSH 服務已在儲存叢集中的一個或多個節點上啟用。

+
若要解決此故障，請停用對應節點上的 SSH 服務，或聯絡NetApp支援尋求協助。

* *ssl憑證過期時間*
+
與此節點關聯的 SSL 憑證即將過期或已過期。此故障根據緊急程度採用以下嚴重程度：

+
|===


| 嚴重程度 | 描述 


 a| 
警告
 a| 
證書有效期限為30天。



 a| 
錯誤
 a| 
證書有效期限為7天。



 a| 
批判的
 a| 
證書將在3天內過期或已過期。

|===
+
若要解決此故障，請更新 SSL 憑證。如有需要，請聯絡NetApp支援部門尋求協助。

* *擱淺容量*
+
單一節點佔用了儲存叢集一半以上的容量。

+
為了保持資料冗餘，系統會降低最大節點的容量，使其部分資料區塊容量閒置（未使用）。

+
若要解決此故障，請為現有儲存節點新增更多磁碟機或為叢集新增儲存節點。

* *溫度感測器*
+
溫度感測器顯示溫度高於正常值。此故障可能與電源錯誤或風扇感測器故障同時觸發。

+
若要解決此故障，請檢查儲存叢集附近是否有氣流阻塞。如有需要，請聯絡NetApp支援部門尋求協助。

* *升級*
+
升級工作已持續超過24小時。

+
若要解決此故障，請恢復升級或聯絡NetApp支援尋求協助。

* *無回應服務*
+
服務已停止回應。

+
請聯絡NetApp支援部門尋求協助。

* *虛擬網路配置*
+
此集群故障表示存在以下情況之一：

+
** 接口不存在。
** 介面中存在錯誤的命名空間。
** 子網路遮罩不正確。
** IP位址錯誤。
** 接口未啟動並運行。
** 節點上存在多餘的介面。


+
請聯絡NetApp支援部門尋求協助。

* *音量降低*
+
輔助卷尚未完成複製和同步。同步完成後，該訊息將被清除。

* *捲線離線*
+
儲存叢集中的一個或多個磁碟區處於離線狀態。同時也會出現 *volumeDegraded* 故障。

+
請聯絡NetApp支援部門尋求協助。


