---
permalink: storage/reference_monitor_event_types.html 
sidebar: sidebar 
keywords: event types, monitor, event log 
summary: 此系統會報告多種類型的事件；每個事件都是系統已完成的一項操作。事件可以是例行、正常的事件，也可以是需要管理員注意的事件。事件日誌頁面上的「事件類型」欄位指示事件發生在系統的哪個部分。 
---
= 事件類型
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
此系統會報告多種類型的事件；每個事件都是系統已完成的一項操作。事件可以是例行、正常的事件，也可以是需要管理員注意的事件。事件日誌頁面上的「事件類型」欄位指示事件發生在系統的哪個部分。


NOTE: 系統不會在事件日誌中記錄只讀 API 命令。

以下列表描述了事件日誌中出現的事件類型：

* *apiEvent*
+
使用者透過 API 或 Web UI 發起的、修改設定的事件。

* *binAssignmentsEvent*
+
與資料箱分配相關的事件。箱子本質上是保存資料的容器，它們在叢集中相互映射。

* *binSyncEvent*
+
與資料在區塊服務之間重新分配相關的系統事件。

* *bsCheckEvent*
+
與區塊服務檢查相關的系統事件。

* *bsKillEvent*
+
與區塊服務終止相關的系統事件。

* *批次操作事件*
+
與整個磁碟區執行的操作相關的事件，例如備份、還原、快照或複製。

* *克隆事件*
+
與卷克隆相關的事件。

* *集群主事件*
+
叢集初始化時或叢集配置變更時（例如新增或刪除節點）出現的事件。

* [[csum_event]]*cSumEvent*
+
與端對端校驗和驗證過程中偵測到校驗和不符相關的事件。

+
偵測到校驗和不匹配的服務將在產生此事件後自動停止，並且不會重新啟動。

* *資料事件*
+
與讀寫資料相關的事件。

* *dbEvent*
+
與叢集中整合節點維護的全域資料庫相關的事件。

* *driveEvent*
+
與驅動操作相關的事件。

* *encryptionAtRestEvent*
+
與集群加密過程相關的事件。

* *合奏活動*
+
與集合中節點數量增加或減少相關的事件。

* *光纖通道事件*
+
與節點配置和連接相關的事件。

* *gcEvent*
+
與進程相關的事件每 60 分鐘運行一次，以回收區塊磁碟機上的儲存空間。這個過程也稱為垃圾回收。

* *ieEvent*
+
內部系統錯誤。

* *安裝事件*
+
自動軟體安裝事件。軟體正在自動安裝到待處理的節點上。

* *iSCSI事件*
+
與系統中的 iSCSI 問題相關的事件。

* *limitEvent*
+
與帳戶或叢集中的磁碟區或虛擬磁碟區數量接近允許的最大值相關的事件。

* *維護模式事件*
+
與節點維護模式相關的事件，例如停用節點。

* [[network_event]]*networkEvent*
+
與每個實體網路介面卡 (NIC) 介面的網路錯誤報告相關的事件。

+
當 10 分鐘監控間隔內，任何介面的錯誤計數超過預設閾值 1000 時，就會觸發這些事件。這些事件適用於網路錯誤，例如接收遺失、循環冗餘校驗 (CRC) 錯誤、長度錯誤、溢位錯誤和訊框錯誤。

* *平台硬體事件*
+
與硬體設備上偵測到的問題相關的事件。

* *遠端叢集事件*
+
與遠端集群配對相關的事件。

* *調度器事件*
+
與計劃快照相關的事件。

* *服務事件*
+
與系統服務狀態相關的事件。

* *切片事件*
+
與 Slice 伺服器相關的事件，例如刪除元資料磁碟機或磁碟區。

+
切片重新分配事件有三種類型，其中包含有關磁碟區分配到的服務的資訊：

+
** 翻轉：將主要服務更改為新的主要服務
+
[listing]
----
sliceID oldPrimaryServiceID->newPrimaryServiceID
----
** 遷移：將輔助服務變更為新的輔助服務
+
[listing]
----
sliceID {oldSecondaryServiceID(s)}->{newSecondaryServiceID(s)}
----
** 修剪：從一組服務中移除一個卷
+
[listing]
----
sliceID {oldSecondaryServiceID(s)}
----


* *snmpTrapEvent*
+
與 SNMP 陷阱相關的事件。

* *statEvent*
+
與系統統計相關的事件。

* *tsEvent*
+
與系統傳遞服務相關的事件。

* *意外異常*
+
與意外系統異常相關的事件。

* *ureEvent*
+
與從儲存設備讀取資料時發生的不可恢復的讀取錯誤相關的事件。

* *vasaProviderEvent*
+
與 VASA（vSphere APIs for Storage Awareness）提供者相關的事件。


