---
permalink: storage/task_data_manage_vol_access_group_add_a_single_initiator.html 
sidebar: sidebar 
keywords: initiator, add to volume access group, access groups, add single initiator, create initiator 
summary: 您可以將發起程式新增至現有的磁碟區存取群組。 
---
= 將單一啟動器新增至磁碟區存取群組
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以將發起程式新增至現有的磁碟區存取群組。

將啟動器新增至磁碟區存取群組後，該啟動器將有權存取該磁碟區存取群組中的所有磁碟區。


TIP: 您可以透過點擊「操作」圖標，然後在活動卷清單中選擇卷的「查看詳細資料」來找到每個卷的發起者。

如果使用基於發起方的 CHAP，則可以為磁碟區存取群組中的單一發起方新增 CHAP 憑證，從而提供更高的安全性。這樣，您就可以將此選項套用到已存在的磁碟區存取群組。

.步驟
. 點選“管理”>“訪問群組”。
. 點選要編輯的訪問群組的「操作」圖示。
. 按一下“*編輯*”。
. 若要將光纖通道啟動程序新增至磁碟區存取群組，請執行下列步驟：
+
.. 在「新增發起程序」下，從「未綁定光纖通道發起程序」清單中選擇一個現有的光纖通道啟動程序。
.. 點選*新增FC發起者*。
+

NOTE: 在此步驟中，您可以點擊“建立發起者”鏈接，輸入發起者名稱，然後點擊“建立”，即可建立發起者。建立發起程序後，系統會自動將其新增至 *發起程序* 清單。

+
格式範例如下：



+
[listing]
----
5f:47:ac:c0:5c:74:d4:02
----
. 若要將 iSCSI 發起程序新增至磁碟區存取群組，請在「新增發起程序」下，從「發起程序」清單中選擇現有發起程序。
+

NOTE: 在此步驟中，您可以點擊“建立發起者”鏈接，輸入發起者名稱，然後點擊“建立”，即可建立發起者。建立發起程序後，系統會自動將其新增至 *發起程序* 清單。

+
發起者 IQN 的可接受格式如下：iqn.yyyy-mm，其中 y 和 m 為數字，後面跟著文本，該文本必須僅包含數字、小寫字母字符、句點 (.)、冒號 (:) 或破折號 (-)。

+
格式範例如下：

+
[listing]
----
iqn.2010-01.com.solidfire:c2r9.fc0.2100000e1e09bb8b
----
+

TIP: 您可以從「管理」>「磁碟區」>「活動卷」頁面找到每個磁碟區的發起方 IQN，方法是按一下「動作」圖標，然後選擇磁碟區的「檢視詳細資料」。

. 點選「儲存變更」。

