---
permalink: storage/task_replication_pair_volumes_using_a_pairing_key.html 
sidebar: sidebar 
keywords: volume pairings, pairing key, replication 
summary: 如果您沒有遠端叢集的叢集管理員憑證，則可以使用配對金鑰將一個磁碟區與遠端叢集上的另一個磁碟區配對。 
---
= 使用配對密鑰配對磁碟區
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您只有來源叢集的叢集管理員權限（您沒有遠端叢集的叢集管理員憑證），則可以使用配對金鑰將一個磁碟區與遠端叢集上的另一個磁碟區配對。

.你需要什麼
* 確保包含這些磁碟區的叢集已配對。
* 確保遠端叢集上有可用於配對的磁碟區。
+

NOTE: 配對過程完成後，您可以指定複製來源和目標。複製來源或目標可以是磁碟區對中的任何一個磁碟區。您應該建立一個不包含任何資料的目標卷，該目標卷具有與來源磁碟區完全相同的特徵，例如大小、磁碟區的區塊大小設定（512e 或 4k）和 QoS 配置。如果將現有磁碟區指定為複製目標，則該磁碟區上的資料將被覆寫。目標體積可以大於或等於源體積，但不能小於源體積。



.步驟
. 選擇“管理”>“卷”。
. 點選要配對的音量對應的「操作」圖示。
. 點選“配對”。
. 在「配對音量」對話方塊中，選擇「開始配對」。
. 選擇“我沒有”表示您沒有存取遠端叢集的權限。
. 從清單中選擇一種*複製模式*：
+
** *即時（非同步）*：寫入作業在來源叢集上提交後，會向客戶端發出確認。
** *即時（同步）*：寫入作業在來源叢集和目標叢集上都提交後，才會向客戶端發出確認。
** *僅限快照*：僅在來源叢集上建立的快照才會被複製。來自來源磁碟區的活動寫入不會被複製。


. 點選“產生密鑰”。
+

NOTE: 此操作會產生用於配對的文字鍵，並在本機叢集上建立一個未配置的磁碟區對。如果您未完成此操作，則需要手動刪除磁碟區對。

. 將配對金鑰複製到電腦剪貼簿。
. 使遠端叢集站點的叢集管理員能夠存取配對密鑰。
+

NOTE: 應妥善保管卷配對金鑰，不得以任何可能導致意外或不安全存取的方式使用。

+

IMPORTANT: 請勿修改配對密鑰中的任何字元。密鑰一旦被修改，就會失效。

. 在遠端叢集 Element UI 中，選擇「管理」>「磁碟區」。
. 點選要配對的音量對應的操作圖示。
. 點選“配對”。
. 在「配對音量」對話方塊中，選擇「完成配對」。
. 將另一個集群中的配對密鑰貼上到「配對密鑰」框中。
. 點選“完成配對”。
+
確認配對後，兩個集群將開始連接卷進行配對的過程。在配對過程中，您可以在「磁碟區對」視窗的「磁碟區狀態」欄位中看到訊息。音量對顯示 `PausedMisconfigured`直到分配了來源和目標卷對。

+
配對成功後，建議您重新整理捲筒表，從已配對磁碟區的「動作」清單中刪除「配對」選項。如果您不刷新表格，則「*配對*」選項仍可供選擇。如果您再次選擇「配對」選項，則會開啟一個新標籤頁，由於該音量已配對，系統會報告： `StartVolumePairing Failed: xVolumeAlreadyPaired` Element UI 頁面的「交易對數量」視窗中出現錯誤訊息。





== 查找更多信息

* xref:reference_replication_volume_pairing_messages.adoc[音量配對訊息]
* xref:reference_replication_volume_pairing_warnings.adoc[音量配對警告]
* xref:task_replication_assign_replication_source_and_target_to_paired_volumes.adoc[為配對卷分配複製來源和目標]

