---
permalink: storage/task_per_node_run_system_utilities.html 
sidebar: sidebar 
keywords: storage nodes, running system utilities, system utilities, network settings, testing changes, reboot the node, power cycle, shuts down the node 
summary: 您可以使用儲存節點的單節點 UI 來建立或刪除支援包、重設磁碟機的組態設定以及重新啟動網路或叢集服務。 
---
= 使用節點級用戶介面運行系統實用程式
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用儲存節點的單節點 UI 來建立或刪除支援包、重設磁碟機的組態設定以及重新啟動網路或叢集服務。

您已登入儲存節點的單節點使用者介面。

. 點選“系統實用工具”。
. 按一下要執行的系統實用程式對應的按鈕。
+
** *控制功率*
+
重啟、斷電或關閉節點。

+

IMPORTANT: 此操作會導致網路連線暫時中斷。

+
請指定以下參數：

+
*** 操作：選項包括重新啟動和停止（關機）。
*** 喚醒延遲：節點重新上線前的任何額外時間。


** *收集節點日誌*
+
在節點的 /tmp/bundles 目錄下建立一個支援包。

+
請指定以下參數：

+
*** 捆綁包名稱：每個建立的支援捆綁包的唯一名稱。如果沒有提供名稱，則使用“supportbundle”和節點名稱作為檔案名稱。
*** 額外參數：此參數將傳遞給 sf_make_support_bundle 腳本。此參數僅應在NetApp支援部門要求時使用。
*** 超時秒數：指定等待每個 ping 回應的秒數。


** *刪除節點日誌*
+
刪除節點上所有使用 *建立叢集支援包* 或 CreateSupportBundle API 方法建立的目前支援包。

** *重置驅動器*
+
初始化磁碟機並刪除磁碟機上目前儲存的所有資料。您可以將該磁碟機重新用於現有節點或升級後的節點。

+
請指定以下參數：

+
*** 磁碟機：要重設的裝置名稱清單（不是磁碟機 ID）。


** *重置網路配置*
+
協助解決單一節點的網路配置問題，並將單一節點的網路配置重設為出廠預設值。

** *重置節點*
+
將節點重設為出廠設定。在此操作過程中，所有資料將被刪除，但節點的網路設定將被保留。只有當節點未指派給叢集且處於可用狀態時，才能重設節點。

+

IMPORTANT: 使用此選項時，節點上的所有資料、軟體包（軟體升級）、配置和日誌檔案都將被刪除。

** *重新啟動網路連線*
+
重啟節點上的所有網路服務。

+

IMPORTANT: 此操作可能會導致網路連線暫時中斷。

** *重啟服務*
+
重啟節點上的 Element 軟體服務。

+

IMPORTANT: 此操作可能會導致節點服務暫時中斷。此操作應僅在NetApp支援人員的指導下執行。

+
請指定以下參數：

+
*** 服務：要重啟的服務名稱。
*** 操作：要對服務執行的操作。選項包括啟動、停止和重新啟動。





