---
permalink: storage/task_system_manage_nodes_adding_a_node_to_a_cluster.html 
sidebar: sidebar 
keywords: nodes, add, config, cluster, pending, pairs, capacity, rule 
summary: 當需要更多儲存空間時，或在建立叢集之後，您可以向叢集新增節點。節點首次上電時需要初始配置。節點配置完成後，它將出現在待處理節點清單中，您可以將其新增至叢集。 
---
= 向叢集新增節點
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
當需要更多儲存空間時，或在建立叢集之後，您可以向叢集新增節點。節點首次上電時需要初始配置。節點配置完成後，它將出現在待處理節點清單中，您可以將其新增至叢集。

叢集中每個節點上的軟體版本必須相容。在叢集新增節點時，叢集會根據需要在新節點上安裝叢集版本的NetApp Element軟體。

您可以為現有叢集新增容量較小或較大的節點。您可以為叢集新增更大容量的節點，以滿足容量成長的需求。在包含較小節點的叢集中新增較大節點時，必須成對新增。這樣就為 Double Helix 留出了足夠的空間，以便在較大的節點之一發生故障時能夠轉移資料。您可以為較大的節點叢集中新增較小的節點容量，以提高效能。


NOTE: 如果新新增的節點佔叢集總容量的 50% 以上，則該節點的部分容量將停用（「閒置」），以使其符合容量規則。在增加更多儲存空間之前，這種情況將持續下去。如果新增一個非常大的節點，並且該節點也違反容量規則，則先前被困的節點將不再被困，而新新增的節點將變為被困。為避免這種情況發生，容量應該始終成對添加。當節點發生故障時，會拋出 strandedCapacity 叢集故障。

https://www.youtube.com/embed/2smVHWkikXY?rel=0["NetApp影片：按需擴充：擴展SolidFire集群"^]

您可以為NetApp HCI設備新增節點。

.步驟
. 選擇“集群”>“節點”。
. 點選「待處理」查看待處理節點清單。
+
新增節點的過程完成後，它們將出現在「活動節點」清單中。在此之前，待處理節點會出現在待處理活動清單中。

+
當您將節點新增至叢集時， SolidFire會在待新增節點上安裝叢集的 Element 軟體版本。這可能需要幾分鐘。

. 執行下列操作之一：
+
** 若要新增單一節點，請按一下要新增的節點旁的「操作」圖示。
** 若要新增多個節點，請選取要新增的節點的複選框，然後選擇「批次操作」。 *注意：*如果您新增的節點的 Element 軟體版本與叢集上執行的版本不同，則叢集會非同步地將該節點更新為叢集主節點上執行的 Element 軟體版本。節點更新後，會自動加入到叢集中。在此非同步過程中，節點將處於 pendingActive 狀態。


. 按一下“*新增*”。
+
此節點出現在活動節點清單中。





== 查找更多信息

xref:concept_system_manage_nodes_node_versioning_and_compatibility.adoc[Node 版本控制和相容性]
