---
permalink: storage/task_data_protection_configure_custom_protection_domains.html 
sidebar: sidebar 
keywords:  
summary: 您可以配置自訂保護域來提高叢集的彈性。 
---
= 配置自訂保護域
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
對於包含兩個以上儲存節點的 Element 集群，您可以為每個節點配置自訂保護域。配置自訂保護域時，必須將叢集中的所有節點指派給一個域。


TIP: 分配保護域時，節點間會開始資料同步，在資料同步完成之前，某些叢集操作將無法使用。為叢集配置自訂保護域後，新增新的儲存節點時，必須先為該節點指派保護域並允許資料同步完成，才能為新節點新增磁碟機。參觀link:../concepts/concept_solidfire_concepts_data_protection.html#protection-domains["保護域文檔"]了解更多關於保護域的資訊。


NOTE: 若要讓自訂保護域方案對叢集有用，每個機箱內的所有儲存節點都必須指派到同一個自訂保護域。要實現這一點，您需要建立足夠的自訂保護域（最小的自訂保護域方案是三個網域）。最佳實踐是，為每個域配置相同數量的節點，並儘量確保分配給特定域的每個節點都是相同類型。

.步驟
. 點選“集群”>“節點”。
. 點選“配置保護域”。
+
在「配置自訂保護域」視窗中，您可以查看目前已配置的保護域（如果有）以及個別節點的保護域分配。

. 輸入新自訂保護域的名稱，然後按一下「建立」。
+
對您需要建立的所有新保護域重複此步驟。

. 對於「分配節點」列表中的每個節點，按一下「保護域」列中的下拉列表，然後選擇要指派給該節點的保護域。
+

CAUTION: 在套用變更之前，請確保您了解您的節點和機箱佈局、您配置的自訂保護域方案以及該方案對資料保護的影響。如果您套用了保護域方案，並且需要立即進行更改，則可能需要一段時間才能進行更改，因為應用程式配置後會發生資料同步。

. 點選“配置保護域”。


.結果
根據叢集規模的大小，域之間的資料同步可能需要一些時間。資料同步完成後，您可以在「叢集」>「節點」頁面上查看自訂保護域分配，Element Web UI 儀表板會在「自訂保護網域運作狀況」窗格中顯示叢集的保護狀態。

.可能出現的錯誤
以下是套用自訂保護域配置後可能會出現的一些錯誤：

|===


| 錯誤 | 描述 | 解決 


| 設定保護域佈局失敗：保護域佈局會導致節點 ID {9} 無法使用。預設名稱和非預設名稱不能同時使用。 | 節點未分配保護域。 | 為節點分配保護域。 


| 設定保護域佈局失敗：保護域類型「custom」拆分了保護域類型「chassis」。 | 多節點機箱中的每個節點都被指派一個與其他節點不同的保護域。 | 確保機箱內的所有節點都分配到相同的保護域。 
|===


== 查找更多信息

* link:../concepts/concept_solidfire_concepts_data_protection.html#custom_pd["自訂保護域"^]
* link:../api/concept_element_api_about_the_api.html["使用 Element API 管理存儲"^]

