---
permalink: storage/task_data_manage_volumes.html 
sidebar: sidebar 
keywords: element, solidfire, volume, create, edit, delete, purge, restore, clone, iscsi, fc clients 
summary: SolidFire系統使用磁碟區來設定儲存。磁碟區是可透過網路由 iSCSI 或光纖通道用戶端存取的區塊設備。 
---
= 管理磁碟區
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SolidFire系統使用磁碟區來設定儲存。磁碟區是可透過網路由 iSCSI 或光纖通道用戶端存取的區塊設備。

在「管理」標籤的「磁碟區」頁面上，您可以建立、修改、複製和刪除節點上的磁碟區。



== 創建卷

您可以建立磁碟區並將該磁碟區與指定的帳戶關聯。每卷書籍都必須與一個帳戶關聯。透過此關聯，該帳戶可以使用 CHAP 憑證透過 iSCSI 發起程序存取磁碟區。

建立磁碟區時可以指定 QoS 設定。

. 選擇“管理”>“卷”。
. 點擊“創建卷”。
. 在「建立新磁碟區」對話方塊中，輸入「磁碟區名稱」。
. 請輸入體積總大小。
+

NOTE: 預設磁碟區大小選擇單位為 GB。您可以建立以 GB 或 GiB 為單位大小的磁碟區：

+
** 1GB = 10億字節
** 1GiB = 1,073,741,824 位元組


. 選擇體積的*區塊大小*。
. 點擊「帳戶」下拉列表，然後選擇應該有權存取該卷的帳戶。
+
如果帳戶不存在，請點擊「建立帳戶」鏈接，輸入新帳戶名稱，然後點擊「建立」。帳戶已建立並與新磁碟區關聯。

+

NOTE: 如果帳戶數量超過 50 個，則清單不會顯示。開始輸入後，自動完成功能會顯示可供選擇的值。

. 若要設定*服務品質*，請執行下列其中一項：
+
.. 在「策略」下，您可以選擇現有的 QoS 策略（如果有）。
.. 在「自訂設定」下，設定 IOPS 的自訂最小值、最大值和突發值，或使用預設的 QoS 值。
+
最大 IOPS 或突發 IOPS 值大於 20,000 IOPS 的捲可能需要較高的佇列深度或多個會話才能在單一磁碟區上達到此 IOPS 水準。



. 點擊“創建卷”。




== 看成交量詳情

. 選擇“管理”>“卷”。
. 查看詳細資訊。
+
** *ID*：系統產生的磁碟區 ID。
** *名稱*：建立磁碟區時賦予該磁碟區的名稱。
** *帳戶*：指派給該磁碟區的帳戶名稱。
** *存取群組*：磁碟區所屬的磁碟區存取群組的名稱。
** *存取權限*：建立磁碟區時指派給該磁碟區的存取類型。可能的值：
+
*** 讀/寫：所有讀寫操作均被接受。
*** 唯讀：允許所有讀取操作；不允許寫入操作。
*** 已鎖定：僅允許管理員存取。
*** ReplicationTarget：指定為複製磁碟區對中的目標磁碟區。


** *已使用空間*：體積中已使用的空間百分比。
** *大小*：磁碟區的總大小（以 GB 為單位）。
** *主節點 ID*：此磁碟區的主節點。
** *輔助節點 ID*：此磁碟區的輔助節點清單。在過渡狀態下（例如次級節點發生變化時），可能存在多個值，但通常只有一個值。
** *QoS 節流*：辨識磁碟區是否因主儲存節點負載過高而受到節流。
** *QoS策略*：使用者定義的QoS策略的名稱和連結。
** *最小 IOPS*：保證該磁碟區的最小 IOPS 數。
** *最大 IOPS*：卷允許的最大 IOPS 數。
** *突發IOPS*：在短時間內允許達到的最大IOPS數量。預設值 = 15,000。
** *快照數*：為該磁碟區建立的快照數量。
** *屬性*：透過 API 方法以鍵/值對的形式指派給磁碟區的屬性。
** *512e*：指示磁碟區上是否啟用了 512e。可能的值：
+
*** 是的
*** 不


** *創建於*：卷的創建日期和時間。






== 查看單筆交易詳情

您可以查看各個磁碟區的效能統計資料。

. 選擇「報告」>「銷售表現」。
. 在音量清單中，按一下音量對應的「操作」圖示。
. 按一下“查看詳細資料”。
+
頁面底部出現一個托盤，其中包含有關該卷的一般資訊。

. 要查看有關銷量的更多詳細信息，請點擊*查看更多詳情*。
+
系統會顯示詳細資訊以及音量效能圖表。





== 編輯活動卷

您可以修改磁碟區屬性，例如 QoS 值、磁碟區大小以及計算位元組值的計量單位。您也可以修改用於複製的帳戶存取權或限制對磁碟區的存取。

當叢集上有足夠的空間且滿足以下條件時，您可以調整磁碟區的大小：

* 正常運轉條件。
* 報告稱出現容量錯誤或故障。
* 該卷正在被克隆。
* 音量正在重新同步。


.步驟
. 選擇“管理”>“卷”。
. 在「活動」視窗中，按一下要編輯的磁碟區的「操作」圖示。
. 按一下“*編輯*”。
. *可選：*更改磁碟區的總大小。
+
** 你可以增加體積，但不能減少體積。在一次調整大小的操作中，您只能調整一個磁碟區的大小。垃圾回收操作和軟體升級不會中斷調整大小操作。
** 如果要調整複製磁碟區的大小，應先增加指定為複製目標的磁碟區的大小。然後您可以調整來源磁碟區的大小。目標體積可以大於或等於源體積，但不能小於源體積。


+
預設磁碟區大小選擇單位為 GB。您可以建立以 GB 或 GiB 為單位大小的磁碟區：

+
** 1GB = 10億字節
** 1GiB = 1,073,741,824 位元組


. *可選：*請選擇以下不同的帳戶存取等級：
+
** 只讀
** 讀/寫
** 已鎖定
** 複製目標


. *可選：* 選擇應該有權存取該卷的帳戶。
+
如果帳戶不存在，請點擊「建立帳戶」鏈接，輸入新的帳戶名稱，然後點擊「建立」。帳戶已建立並與磁碟區關聯。

+

NOTE: 如果帳戶數量超過 50 個，則清單不會顯示。開始輸入後，自動完成功能會顯示可供選擇的值。

. *可選：*若要變更「服務品質」中的選擇，請執行下列其中一項操作：
+
.. 在「策略」下，您可以選擇現有的 QoS 策略（如果有）。
.. 在「自訂設定」下，設定 IOPS 的自訂最小值、最大值和突發值，或使用預設的 QoS 值。
+

NOTE: 如果您在磁碟區上使用 QoS 策略，您可以設定自訂 QoS 以移除 QoS 策略與該磁碟區的關聯。自訂 QoS 將覆蓋和調整磁碟區 QoS 設定的 QoS 策略值。

+

TIP: 變更 IOPS 值時，應以十或百為單位遞增。輸入值必須為有效的整數。

+

TIP: 配置卷，使其突發值極高。這樣一來，系統就能更快地處理偶爾出現的大塊順序工作負載，同時還能限製卷的持續 IOPS。



. 點選「儲存變更」。




== 刪除卷

您可以從 Element 儲存叢集中刪除一個或多個磁碟區。

系統不會立即清除已刪除的磁碟區；該磁碟區將保留約八小時。如果在系統清除磁碟區之前恢復該磁碟區，則該磁碟區將重新連線，且 iSCSI 連線將會復原。

如果用於建立快照的磁碟區已刪除，則其關聯的快照將變為非活動狀態。當刪除來源磁碟區時，關聯的非活動快照也會從系統中刪除。


IMPORTANT: 在安裝或升級過程中，會建立與管理服務關聯的持久性磁碟區並將其指派給新帳戶。如果您使用的是持久卷，請勿修改或刪除卷或其關聯的帳戶。

.步驟
. 選擇“管理”>“卷”。
. 若要刪除單一磁碟區，請執行下列步驟：
+
.. 點選要刪除的磁碟區對應的「操作」圖示。
.. 在出現的選單中，按一下「刪除」。
.. 確認操作。


+
系統會將磁碟區移至「磁碟區」頁面上的「已刪除」區域。

. 若要刪除多個卷，請執行下列步驟：
+
.. 在磁碟區清單中，選取要刪除的磁碟區旁的核取方塊。
.. 點擊“批量操作”。
.. 在出現的選單中，按一下「刪除」。
.. 確認操作。
+
系統會將磁碟區移至「磁碟區」頁面上的「已刪除」區域。







== 恢復已刪除的捲

如果系統中的某個磁碟區已被刪除但尚未清除，則可以將其還原。系統會在刪除磁碟區後約八小時自動清除該磁碟區。如果系統已清除該磁碟區，則無法復原。

. 選擇“管理”>“卷”。
. 點選「已刪除」標籤以查看已刪除磁碟區的清單。
. 按一下要復原的磁碟區對應的「操作」圖示。
. 在出現的選單中，按一下「恢復」。
. 確認操作。
+
該磁碟區被放入*活動*磁碟區清單中，並且與該磁碟區的 iSCSI 連線已復原。





== 清除卷

當一個磁碟區被清除時，它會從系統中永久刪除。該卷中的所有資料都遺失了。

系統會在刪除卷八小時後自動清除這些磁碟區。但是，如果您想在預定時間之前清除卷，您可以這樣做。

. 選擇“管理”>“卷”。
. 點擊“已刪除”按鈕。
. 執行下列步驟以清除單一磁碟區或多個磁碟區。
+
[cols="25,75"]
|===
| 選項 | 步驟 


 a| 
清除單一磁碟區
 a| 
.. 按一下要清除的磁碟區的「操作」圖示。
.. 點選“清除”。
.. 確認操作。




 a| 
清除多個卷
 a| 
.. 選擇要清除的磁碟區。
.. 點擊“批量操作”。
.. 在出現的選單中，選擇“清除”。
.. 確認操作。


|===




== 複製卷

您可以建立單一磁碟區或多個磁碟區的克隆，以建立資料在特定時間點的副本。複製磁碟區時，系統會建立磁碟區的快照，然後建立快照所引用的資料的副本。這是一個非同步過程，該過程所需的時間取決於您要複製的磁碟區的大小和當前的叢集負載。

叢集一次最多支援每個磁碟區運行兩個克隆請求，並且一次最多支援八個活動卷克隆操作。超出這些限制的請求將被排隊，稍後再處理。


NOTE: 不同的作業系統對複製卷的處理方式各不相同。 VMware ESXi 會將複製磁碟區視為磁碟區副本或快照磁碟區。該卷將是一個可用於建立新資料儲存的裝置。有關掛載克隆磁碟區和處理快照 LUN 的更多信息，請參閱 VMware 文件。 https://docs.vmware.com/en/VMware-vSphere/6.7/com.vmware.vsphere.storage.doc/GUID-EEFEB765-A41F-4B6D-917C-BB9ABB80FC80.html["掛載 VMFS 資料儲存副本"]和 https://docs.vmware.com/en/VMware-vSphere/6.7/com.vmware.vsphere.storage.doc/GUID-EBAB0D5A-3C77-4A9B-9884-3D4AD69E28DC.html["管理重複的 VMFS 資料存儲"]。


IMPORTANT: 在透過克隆到較小大小來截斷克隆卷之前，請確保已準備好分區，以便它們能夠適應較小的捲。

.步驟
. 選擇“管理”>“卷”。
. 若要複製單一磁碟區，請執行下列步驟：
+
.. 在「活動」頁面的磁碟區清單中，按一下要複製的磁碟區的「操作」圖示。
.. 在出現的選單中，按一下“克隆”。
.. 在「克隆卷」視窗中，輸入新克隆卷的捲名。
.. 使用“容量大小”微調框和清單選擇容量的大小和測量單位。
+

NOTE: 預設磁碟區大小選擇單位為 GB。您可以建立以 GB 或 GiB 為單位大小的磁碟區：

+
*** 1GB = 10億字節
*** 1GiB = 1,073,741,824 位元組


.. 選擇新克隆卷的存取類型。
.. 從「帳戶」清單中選擇要與新複製卷關聯的帳戶。
+

NOTE: 您可以在此步驟中建立帳戶，方法是按一下「建立帳戶」鏈接，輸入帳戶名稱，然後按一下「建立」。建立帳戶後，系統會自動將其新增至「帳戶」清單。



. 若要克隆多個卷，請執行以下步驟：
+
.. 在「活動」頁面的磁碟區清單中，選取要複製的任何磁碟區旁的核取方塊。
.. 點擊“批量操作”。
.. 在出現的選單中，選擇“克隆”。
.. 在「複製多個磁碟區」對話方塊中，在「新磁碟區名稱前綴」欄位中輸​​入複製卷的前綴。
.. 從「帳戶」清單中選擇要與複製卷關聯的帳戶。
.. 選擇克隆卷的存取類型。


. 點選“開始克隆”。
+

NOTE: 增加克隆的體積大小，會在新體積的末端產生額外的可用空間。根據您對磁碟區的使用方式，您可能需要擴展分割區或在可用空間中建立新分割區才能充分利用它。





== 更多資訊

* https://docs.netapp.com/us-en/element-software/index.html["SolidFire和 Element 軟體文檔"]
* https://docs.netapp.com/us-en/vcp/index.html["NetApp Element vCenter Server 插件"^]

