---
permalink: storage/task_replication_pair_volumes_using_a_volume_id.html 
sidebar: sidebar 
keywords: volume pairings, volume id, replication 
summary: 如果您擁有遠端叢集的叢集管理員憑證，則可以將一個磁碟區與遠端叢集上的另一個磁碟區配對。 
---
= 使用卷 ID 配對卷
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您擁有要配對的磁碟區所在的兩個叢集的叢集管理員存取權限，則可以將一個磁碟區與遠端叢集上的另一個磁碟區配對。此方法使用遠端叢集上磁碟區的磁碟區 ID 來發起連線。

.你需要什麼
* 確保包含這些磁碟區的叢集已配對。
* 在遠端叢集上建立一個新磁碟區。
+

NOTE: 配對過程完成後，您可以指定複製來源和目標。複製來源或目標可以是磁碟區對中的任何一個磁碟區。您應該建立一個不包含任何資料的目標卷，該目標卷具有與來源磁碟區完全相同的特徵，例如大小、磁碟區的區塊大小設定（512e 或 4k）和 QoS 配置。如果將現有磁碟區指定為複製目標，則該磁碟區上的資料將被覆寫。目標體積可以大於或等於源體積，但不能小於源體積。

* 知道目標卷的ID。


.步驟
. 選擇“管理”>“卷”。
. 點選要配對的音量對應的「操作」圖示。
. 點選“配對”。
. 在「配對音量」對話方塊中，選擇「開始配對」。
. 選擇“我願意”表示您有權存取遠端叢集。
. 從清單中選擇一種*複製模式*：
+
** *即時（非同步）*：寫入作業在來源叢集上提交後，會向客戶端發出確認。
** *即時（同步）*：寫入作業在來源叢集和目標叢集上都提交後，才會向客戶端發出確認。
** *僅限快照*：僅在來源叢集上建立的快照才會被複製。來自來源磁碟區的活動寫入不會被複製。


. 從清單中選擇一個遠端叢集。
. 選擇遠端磁碟區 ID。
. 點擊“開始配對”。
+
系統開啟一個網頁瀏覽器標籤頁，連接到遠端叢集的 Element UI。您可能需要使用叢集管理員憑證登入遠端叢集。

. 在遠端叢集的 Element UI 中，選擇「完成配對」。
. 請在「確認音量配對」中確認詳細資訊。
. 點選“完成配對”。
+
確認配對後，兩個集群將開始連接卷進行配對的過程。在配對過程中，您可以在「磁碟區對」視窗的「磁碟區狀態」欄位中看到訊息。音量對顯示 `PausedMisconfigured`直到分配了來源和目標卷對。

+
配對成功後，建議您重新整理捲筒表，從已配對磁碟區的「動作」清單中刪除「配對」選項。如果您不刷新表格，則「*配對*」選項仍可供選擇。如果您再次選擇「配對」選項，則會開啟一個新標籤頁，由於該音量已配對，系統會報告： `StartVolumePairing Failed: xVolumeAlreadyPaired` Element UI 頁面的「交易對數量」視窗中出現錯誤訊息。





== 查找更多信息

* xref:reference_replication_volume_pairing_messages.adoc[音量配對訊息]
* xref:reference_replication_volume_pairing_warnings.adoc[音量配對警告]
* xref:task_replication_assign_replication_source_and_target_to_paired_volumes.adoc[為配對卷分配複製來源和目標]

