---
permalink: storage/task_data_manage_accounts_work_with_accounts_task.html 
sidebar: sidebar 
keywords: element, solidfire, accounts, create, delete, change, chap, view, edit 
summary: 在SolidFire儲存系統中，租戶可以使用帳戶使用戶端能夠連接到節點上的磁碟區。帳戶包含存取指派給它的磁碟區所需的 CHAP 驗證。建立磁碟區時，會將其指派給特定帳戶。 
---
= 使用 CHAP 處理帳戶
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在SolidFire儲存系統中，租用戶可以使用帳戶使用戶端能夠連接到叢集上的磁碟區。帳戶包含存取指派給它的磁碟區所需的質詢握手身分驗證協定 (CHAP) 驗證。建立磁碟區時，會將其指派給特定帳戶。

一個帳戶最多可以分配兩千卷，但一卷只能屬於一個帳戶。



== CHAP演算法

從 Element 12.7 開始，支援符合 FIPS 標準的 CHAP 安全演算法 SHA1、SHA-256 和 SHA3-256。當主機 iSCSI 發起程式與 Element iSCSI 目標建立 iSCSI 會話時，它會要求要使用的 CHAP 演算法清單。 Element iSCSI 目標從主機 iSCSI 發起程序請求的清單中選擇它支援的第一個演算法。要確認 Element iSCSI 目標選擇最安全的演算法，必須配置主機 iSCSI 發起程序發送演算法列表，該列表按安全性從高到低排序，例如 SHA3-256 或 SHA1 或 MD5。當主機 iSCSI 發起程序未請求 SHA 演算法時，Element iSCSI 目標選擇 MD5，假設主機提出的演算法清單中包含 MD5。您可能需要更新主機 iSCSI 發起程序配置，以啟用安全演算法的支援。

在 Element 12.7 或更高版本升級期間，如果您已將主機 iSCSI 發起程序配置更新為發送包含 SHA 演算法清單的會話請求，則在儲存節點重新啟動時，新的安全性演算法將被激活，並且新的或重新連接的 iSCSI 會話將使用最安全的協定建立。在升級過程中，所有現有的 iSCSI 會話都將從 MD5 轉換為 SHA。如果您不更新主機 iSCSI 發起程序設定以要求 SHA，則現有的 iSCSI 會話將繼續使用 MD5。稍後，在您更新主機 iSCSI 發起程序 CHAP 演算法之後，iSCSI 會話應根據導致 iSCSI 會話重新連接的維護活動，逐漸從 MD5 過渡到 SHA。

例如，Red Hat Enterprise Linux (RHEL) 8.3 中的預設主機 iSCSI 發起程式具有下列特性： `node.session.auth.chap_algs = SHA3-256,SHA256,SHA1,MD5`此設定被註解掉，導致 iSCSI 發起程序僅使用 MD5。取消主機上此設定的註解並重新啟動 iSCSI 發起程序，即可觸發該主機上的 iSCSI 會話開始使用 SHA3-256。

如果需要，您可以使用 https://docs.netapp.com/us-en/element-software/api/reference_element_api_listiscsisessions.html["列出 ISCSI 會話"]API 方法，用於查看每個會話所使用的 CHAP 演算法。



== 建立一個帳戶

您可以建立帳戶以允許存取磁碟區。

系統中的每個帳戶名稱都必須是唯一的。

. 選擇“管理”>“帳戶”。
. 點選「建立帳戶」。
. 請輸入*使用者名稱*。
. 在「CHAP 設定」部分，輸入以下資訊：
+

NOTE: 將憑證欄位留空，即可自動產生任一密碼。

+
** CHAP節點會話認證的*發起方金鑰*。
** CHAP節點會話認證的目標金鑰。


. 點選「建立帳戶」。




== 查看帳戶詳情

您可以以圖形格式查看各個帳戶的業績活動。

圖表資訊提供帳戶的 I/O 和吞吐量資訊。平均活動水準和峰值活動水準以 10 秒的報告週期為增量顯示。這些統計資料包括分配給該帳戶的所有交易量的活動。

. 選擇“管理”>“帳戶”。
. 點選帳戶的「操作」圖示。
. 按一下“查看詳細資料”。


以下是一些細節：

* *狀態*：帳戶的狀態。可能的值：
+
** 活躍帳戶：一個活躍的帳戶。
** 已鎖定：一個已鎖定的帳戶。
** 已刪除：已刪除並清除的帳戶。


* *活動卷數*：分配給帳戶的活動卷數。
* *壓縮率*：分配給該帳戶的捲的壓縮效率得分。
* *重複資料刪除*：指派給該帳戶的磁碟區的重複資料刪除效率分數。
* *精簡配置*：指派給帳戶的磁碟區的精簡配置效率評分。
* *整體效率*：分配給該帳戶的業務量的整體效率得分。




== 編輯帳戶

您可以編輯帳戶以變更狀態、變更 CHAP 金鑰或修改帳戶名稱。

修改帳戶中的 CHAP 設定或從存取群組中刪除發起程式或磁碟區可能會導致發起程式意外失去對磁碟區的存取權。為驗證磁碟區存取不會意外遺失，請務必登出受帳戶或存取群組變更影響的 iSCSI 會話，並在完成對啟動器設定和叢集設定的任何變更後，驗證啟動器是否可以重新連線至磁碟區。


IMPORTANT: 與管理服務關聯的持久性磁碟區會被指派給在安裝或升級期間建立的新帳戶。如果您使用的是持久卷，請勿修改或刪除其關聯的帳戶。

. 選擇“管理”>“帳戶”。
. 點選帳戶的「操作」圖示。
. 在出現的選單中，選擇“編輯”。
. *可選：* 編輯 *使用者名稱*。
. *可選：*按一下「狀態」下拉列表，然後選擇其他狀態。
+

IMPORTANT: 將狀態變更為 *已鎖定* 將終止與該帳戶的所有 iSCSI 連接，且該帳戶將無法再存取。與該帳戶關聯的磁碟區已維護；但是，這些磁碟區無法透過 iSCSI 發現。

. *可選：*在 *CHAP 設定* 下，編輯用於節點會話驗證的 *發起方金鑰* 和 *目標金鑰* 憑證。
+

NOTE: 如果您不更改 *CHAP 設定* 憑證，則它們將保持不變。如果將憑證欄位留空，系統將產生新密碼。

. 點選「儲存變更」。




== 刪除帳戶

不再需要帳戶時，您可以將其刪除。

在刪除帳戶之前，請刪除並清除與該帳戶關聯的所有磁碟區。


IMPORTANT: 與管理服務關聯的持久性磁碟區會被指派給在安裝或升級期間建立的新帳戶。如果您使用的是持久卷，請勿修改或刪除其關聯的帳戶。

. 選擇“管理”>“帳戶”。
. 點選要刪除的帳戶旁的「操作」圖示。
. 在出現的選單中，選擇“刪除”。
. 確認操作。




== 查找更多信息

* https://docs.netapp.com/us-en/element-software/index.html["SolidFire和 Element 軟體文檔"]
* https://docs.netapp.com/us-en/vcp/index.html["NetApp Element vCenter Server 插件"^]

