---
permalink: storage/task_replication_assign_replication_source_and_target_to_paired_volumes.html 
sidebar: sidebar 
keywords: volume pairings, paired volumes, replication source, assign 
summary: 磁碟區配對完成後，必須指定來源磁碟區及其複製目標磁碟區。複製來源或目標可以是磁碟區對中的任何一個磁碟區。如果來源磁碟區不可用，您也可以使用此程序將傳送至來源磁碟區的資料重新導向至遠端目標磁碟區。 
---
= 為配對卷分配複製來源和目標
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
磁碟區配對完成後，必須指定來源磁碟區及其複製目標磁碟區。複製來源或目標可以是磁碟區對中的任何一個磁碟區。如果來源磁碟區不可用，您也可以使用此程序將傳送至來源磁碟區的資料重新導向至遠端目標磁碟區。

.你需要什麼
您可以存取包含來源磁碟區和目標磁碟區的叢集。

.步驟
. 準備來源磁碟區：
+
.. 從包含要指定為來源的磁碟區的叢集中，選擇「管理」>「磁碟區」。
.. 點擊要指定為音源的音量旁邊的“操作”圖標，然後點擊“編輯”。
.. 在「存取」下拉清單中，選擇「讀取/寫入」。
+

IMPORTANT: 如果要反轉來源和目標分配，此操作將導致磁碟區對顯示下列訊息，直到分配新的複製目標為止： `PausedMisconfigured`

+
更改存取權限會暫停磁碟區複製，並導致資料傳輸停止。請務必協調好兩個站點上的這些變更。

.. 點選「儲存變更」。


. 準備目標體積：
+
.. 從包含要指定為目標的磁碟區的叢集中，選擇「管理」>「磁碟區」。
.. 按一下要指定為目標的磁碟區的「操作」圖標，然後按一下「編輯」。
.. 在「存取」下拉清單中，選擇「複製目標」。
+

IMPORTANT: 如果將現有磁碟區指定為複製目標，則該磁碟區上的資料將被覆寫。您應該使用一個不包含任何資料的新目標卷，該目標卷具有與來源卷完全相同的特徵，例如大小、512e 設定和 QoS 配置。目標體積可以大於或等於源體積，但不能小於源體積。

.. 點選「儲存變更」。






== 查找更多信息

* xref:task_replication_pair_volumes_using_a_volume_id.adoc[使用卷 ID 配對卷]
* xref:task_replication_pair_volumes_using_a_pairing_key.adoc[使用配對密鑰配對磁碟區]

