---
permalink: storage/task_data_manage_vol_access_group_create_a_volume_access_group.html 
sidebar: sidebar 
keywords: volume access group, create, initiators 
summary: 您可以透過將發起程式對應到磁碟區集合來建立磁碟區存取群組，從而實現安全存取。然後，您可以使用帳戶 CHAP 發起程式金鑰和目標金鑰授予對群組中磁碟區的存取權。 
---
= 建立卷宗訪問群組
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以透過將發起程式對應到磁碟區集合來建立磁碟區存取群組，從而實現安全存取。然後，您可以使用帳戶 CHAP 發起程式金鑰和目標金鑰授予對群組中磁碟區的存取權。

如果使用基於發起方的 CHAP，則可以為磁碟區存取群組中的單一發起方新增 CHAP 憑證，從而提供更高的安全性。這樣，您就可以將此選項套用到已存在的磁碟區存取群組。

.步驟
. 點選“管理”>“訪問群組”。
. 點選「建立訪問群組」。
. 在「名稱」欄位中輸​​入磁碟區存取群組的名稱。
. 可以透過以下方式之一將發起程序新增至磁碟區存取群組：
+
[cols="25,75"]
|===
| 選項 | 描述 


 a| 
新增光纖通道發起程序
 a| 
.. 在「新增發起程序」下，從「未綁定光纖通道發起程序」清單中選擇一個現有的光纖通道啟動程序。
.. 點選*新增FC發起者*。
+

NOTE: 在此步驟中，您可以點擊“建立發起者”鏈接，輸入發起者名稱，然後點擊“建立”，即可建立發起者。建立發起程序後，系統會自動將其新增至發起程序清單。



格式範例如下：

[listing]
----
5f:47:ac:c0:5c:74:d4:02
----


 a| 
新增 iSCSI 發起程序
 a| 
在「新增發起方」下，從發起方清單中選擇一個現有的發起方。 *注意：* 您可以在此步驟中建立發起者，方法是按一下「建立發起者」鏈接，輸入發起者名稱，然後按一下「建立」。建立發起程序後，系統會自動將其新增至發起程序清單。

格式範例如下：

[listing]
----
iqn.2010-01.com.solidfire:c2r9.fc0.2100000e1e09bb8b
----

TIP: 您可以透過在「管理」>「磁碟區」>「活動」清單中選擇磁碟區的「操作」功能表中的「檢視詳細資料」來尋找每個磁碟區的發起者 IQN。

修改發起程序時，可以將 requiredCHAP 屬性切換為 True，這樣就可以設定目標發起程式金鑰。有關詳細信息，請參閱 ModifyInitiator API 方法的 API 資訊。

link:../api/concept_element_api_about_the_api.html["使用 Element API 管理存儲"]

|===
. *可選：*根據需要添加更多啟動器。
. 在「新增卷」下，從「磁碟區」清單中選擇一個磁碟區。
+
該磁碟區出現在「已附加磁碟區」清單中。

. *可選：*根據需要添加更多卷。
. 點選「建立訪問群組」。




== 查找更多信息

xref:task_data_manage_vol_access_group_add_volumes.adoc[將磁碟區新增至存取群組]
