---
permalink: storage/task_snapmirror_performing_failback_when_source_volume_no_longer_exists.html 
sidebar: sidebar 
keywords: element, ui, failback, perform, source, volume, snapmirror, dr, disaster, recovery 
summary: 您可以使用NetApp Element UI 重新同步原始來源磁碟區並進行故障復原。本節適用於原始來源磁碟區遺失但原始群集仍然完好無損的情況。有關如何還原到新叢集的說明，請參閱NetApp支援網站上的文件。 
---
= 當來源磁碟區不存在時，執行故障復原。
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用NetApp Element UI 重新同步原始來源磁碟區並進行故障復原。本節適用於原始來源磁碟區遺失但原始群集仍然完好無損的情況。有關如何還原到新叢集的說明，請參閱NetApp支援網站上的文件。

.你需要什麼
* Element 捲和ONTAP磁碟區之間的複製關係已中斷。
* 《元素》卷已完全遺失。
* 原始卷名顯示為“未找到”。


.步驟
. 在 Element UI 中，找到您為了執行故障轉移而斷開的關係。
+
*最佳實踐：* 記下SnapMirror政策和原始破裂關係的日程安排詳情。重建關係時需要這些資訊。

. 點擊“操作”圖標，然後點擊“反向同步”。
. 確認操作。
+

NOTE: 反向重新同步操作會建立一個新的關係，其中原始來源磁碟區和目標磁碟區的角色互換（這將導致兩個關係，因為原始關係仍然存在）。由於原始卷已不存在，系統將建立一個新的 Element 卷，其磁碟區名稱和磁碟區大小與原始來源磁碟區相同。新磁碟區被指派了名為 sm-recovery 的預設 QoS 策略，並與名為 sm-recovery 的預設帳戶關聯。您需要手動編輯SnapMirror所建立的所有磁碟區的帳戶和 QoS 策略，以取代已銷毀的原始來源磁碟區。

+
作為反向重新同步操作的一部分，最新快照中的資料傳輸到新磁碟區。您可以繼續存取目標端的活動磁碟區並向其寫入數據，但您需要中斷所有主機與活動磁碟區的連接，並在稍後的步驟中恢復原始主關係之前執行SnapMirror更新。完成反向同步後，請確保目標端磁碟區上沒有活動會話連接，並且最新資料位於原始主磁碟區上，然後繼續執行以下步驟以完成故障復原並重新啟動原始主磁碟區：

. 按一下在反向重新同步操作期間建立的反向關係的「操作」圖標，然後按一下「斷開」。
. 按一下原始關係的「操作」圖示（其中來源磁碟區不存在），然後按一下「刪除」。
. 點擊您在步驟 4 中斷開的反向關係的 *操作* 圖標，然後點擊 *反向重新同步*。
. 這將來源和目標互換，從而得到與原始關係具有相同磁碟區來源和磁碟區目標的關係。
. 點擊“操作”圖標，然後點擊“編輯”，即可使用您記下的原始 QoS 策略和計劃設定更新此關係。
. 現在可以安全地刪除您在步驟 6 中反向同步的反向關係了。




== 查找更多信息

xref:concept_snapmirror_failback_scenarios.adoc[SnapMirror故障恢復場景]
