---
permalink: storage/task-element-replication-reactivate-original-source-volume.html 
sidebar: sidebar 
keywords: ontap,cli, reactivate, original, source, volume 
summary: 當您不再需要從目標位置提供資料時，您可以重新建立來源磁碟區和目標磁碟區之間的原始資料保護關係。 
---
= 重新啟動原始來源音量
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
當您不再需要從目標位置提供資料時，您可以重新建立來源磁碟區和目標磁碟區之間的原始資料保護關係。

.關於此任務
以下步驟假設原始源體積中的基線完好無損。如果基準不完整，則必須先建立並初始化從中提供資料的磁碟區與原始來源磁碟區之間的關係，然後再執行該程序。

您必須在表單中指定元素來源路徑。 `<hostip:>/lun/<name>`其中“`lun`”是實際的字串“`lun`”， `name`是元素卷的名稱。

從ONTAP 9.4 開始，當您從ONTAP目標提供資料時所建立的 LUN 快照副本會在 Element 來源重新啟動時自動複製。

複製規則如下：

* 僅支援 iSCSI LUN。
* 一次只能將ONTAP磁碟區中的單一 LUN 複製到 Element 磁碟區。
* 您無法將ONTAP磁碟區中的 LUN 複製到多個 Element 磁碟區。


.步驟
. 刪除原始資料保護關係：
+
`snapmirror delete -source-path <SVM:volume>|<cluster://SVM/volume> -destination-path <hostip:>/lun/<name> -policy <policy>`

+
有關完整的命令語法，請參閱手冊頁。

+
以下範例刪除了原始來源磁碟區之間的關係， `0005` IP 位址為 10.0.0.11，以及您正在從中提供資料的捲， `volA_dst`在 `svm_backup`：

+
[listing]
----
cluster_dst::> snapmirror delete -source-path 10.0.0.11:/lun/0005 -policy MirrorLatest -destination-path svm_backup:volA_dst
----
. 顛覆原有的資料保護關係：
+
`snapmirror resync -source-path <SVM:volume>|<cluster://SVM/volume> -destination-path <hostip:>/lun/<name> -policy <policy>`

+
有關完整的命令語法，請參閱手冊頁。

+
雖然重新同步不需要基線傳輸，但可能會很耗時。您可能需要在非尖峰時段執行重新同步操作。

+
以下範例顛倒了原始來源卷之間的關係， `0005` IP 位址為 10.0.0.11，以及您正在從中提供資料的捲， `volA_dst`在 `svm_backup`：

+
[listing]
----
cluster_dst::> snapmirror resync -source-path svm_backup:volA_dst -destination-path 10.0.0.11:/lun/0005 -policy MirrorLatest
----
. 更新反向關係：
+
`snapmirror update -source-path <SVM:volume>|<cluster://SVM/volume> -destination-path <hostip:>/lun/<name>`

+
有關完整的命令語法，請參閱手冊頁。

+
[NOTE]
====
如果來源和目標上不存在通用快照副本，則該命令會失敗。使用 `snapmirror initialize`重新初始化關係。

====
+
以下範例更新了您正在從中提供資料的磁碟區之間的關係： `volA_dst`在 `svm_backup`以及原始資料卷， `0005` IP位址為10.0.0.11：

+
[listing]
----
cluster_dst::> snapmirror update -source-path svm_backup:volA_dst -destination-path 10.0.0.11:/lun/0005
----
. 停止反向關係的預定轉帳：
+
`snapmirror quiesce -source-path <SVM:volume>|<cluster://SVM/volume> -destination-path <hostip:>/lun/<name>`

+
有關完整的命令語法，請參閱手冊頁。

+
以下範例會停止您正在從中提供資料的磁碟區之間的計劃傳輸： `volA_dst`在 `svm_backup`以及原始資料卷， `0005` IP位址為10.0.0.11：

+
[listing]
----
cluster_dst::> snapmirror quiesce -source-path svm_backup:volA_dst -destination-path 10.0.0.11:/lun/0005
----
. 停止反向轉帳：
+
`snapmirror abort -source-path <SVM:volume>|<cluster://SVM/volume> -destination-path <hostip:>/lun/<name>`

+
有關完整的命令語法，請參閱手冊頁。

+
以下範例停止您正在從中提供資料的磁碟區之間的正在進行的傳輸： `volA_dst`在 `svm_backup`以及原始資料卷， `0005` IP位址為10.0.0.11：

+
[listing]
----
cluster_dst::> snapmirror abort -source-path svm_backup:volA_dst -destination-path 10.0.0.11:/lun/0005
----
. 打破這種顛倒的關係：
+
`snapmirror break -source-path <SVM:volume>|<cluster://SVM/volume> -destination-path <hostip:>/lun/<name>`

+
有關完整的命令語法，請參閱手冊頁。

+
以下範例打破了您正在提供資料的捲之間的關係， `volA_dst`在 `svm_backup`以及原始資料卷， `0005` IP位址為10.0.0.11：

+
[listing]
----
cluster_dst::> snapmirror break -source-path svm_backup:volA_dst -destination-path 10.0.0.11:/lun/0005
----
. 刪除反向資料保護關係：
+
`snapmirror delete -source-path <SVM:volume>|<cluster://SVM/volume> -destination-path <hostip:>/lun/<name> -policy <policy>`

+
有關完整的命令語法，請參閱手冊頁。

+
以下範例刪除了原始來源磁碟區之間的反向關係， `0005` IP 位址為 10.0.0.11，以及您正在從中提供資料的捲， `volA_dst`在 `svm_backup`：

+
[listing]
----
cluster_src::> snapmirror delete -source-path svm_backup:volA_dst -destination-path 10.0.0.11:/lun/0005 -policy MirrorLatest
----
. 重建原有的資料保護關係：
+
`snapmirror resync -source-path <hostip:>/lun/<name> -destination-path <SVM:volume>|<cluster://SVM/volume>`

+
有關完整的命令語法，請參閱手冊頁。

+
以下範例重新建立了原始來源磁碟區之間的關係， `0005` IP 位址為 10.0.0.11，原始目標磁碟區為： `volA_dst`在 `svm_backup`：

+
[listing]
----
cluster_dst::> snapmirror resync -source-path 10.0.0.11:/lun/0005 -destination-path svm_backup:volA_dst
----


.完成後
使用 `snapmirror show`命令用於驗證SnapMirror關係是否已建立。有關完整的命令語法，請參閱手冊頁。
