---
permalink: storage/task_post_deploy_credential_change_ipmi_password.html 
sidebar: sidebar 
keywords: ipmi, password, intelligent platform management interface, netapp, element, h410s, h610s 
summary: '只要您擁有對節點的遠端 IPMI 存取權限，即可變更預設的智慧型平台管理介面 (IPMI) 管理員密碼。如果安裝有任何更新，您可能需要執行此操作。' 
---
= 更改節點的預設 IPMI 密碼
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
只要您擁有對節點的遠端 IPMI 存取權限，即可變更預設的智慧型平台管理介面 (IPMI) 管理員密碼。如果安裝有任何更新，您可能需要執行此操作。

有關配置節點 IPM 存取權限的詳細信息，請參閱link:https://docs.netapp.com/us-en/hci/docs/hci_prereqs_final_prep.html["為每個節點配置 IPMI"^]。

您可以變更下列節點的 IPM 密碼：

* H410S節點
* H610S節點




== 更改 H410S 節點的預設 IPMI 密碼

配置 IPMI 網路連接埠後，應立即變更每個儲存節點上 IPMI 管理員帳戶的預設密碼。

.你需要什麼
您應該為每個儲存節點配置 IPMI IP 位址。

.步驟
. 在能夠存取 IPMI 網路的電腦上開啟網頁瀏覽器，並瀏覽至節點的 IPMI IP 位址。
. 請輸入使用者名稱 `ADMIN`和密碼 `ADMIN`在登入提示符號中。
. 登入後，點選「配置」標籤。
. 點選“用戶”。
. 選擇 `ADMIN`使用者並點選*修改使用者*。
. 選取“更改密碼”複選框。
. 請在「密碼」和「確認密碼」欄位中輸​​入新密碼。
. 點擊“修改”，然後點擊“確定”。
. 對其他所有使用預設 IPMI 密碼的 H410S 節點重複此程序。




== 更改 H610S 節點的預設 IPMI 密碼

配置 IPMI 網路連接埠後，應立即變更每個儲存節點上 IPMI 管理員帳戶的預設密碼。

.你需要什麼
您應該為每個儲存節點配置 IPMI IP 位址。

.步驟
. 在能夠存取 IPMI 網路的電腦上開啟網頁瀏覽器，並瀏覽至節點的 IPMI IP 位址。
. 請輸入使用者名稱 `root`和密碼 `calvin`在登入提示符號中。
. 登入後，點擊頁面左上角的選單導航圖標，打開側邊欄抽屜。
. 點選“設定”。
. 點選“用戶管理”。
. 從清單中選擇*管理員*使用者。
. 啟用“更改密碼”複選框。
. 請在「密碼」和「確認密碼」欄位中輸​​入新的、強密碼。
. 點擊頁面底部的「儲存」。
. 對其他所有使用預設 IPMI 密碼的 H610S 節點重複此程序。




== 查找更多信息

* https://docs.netapp.com/us-en/element-software/index.html["SolidFire和 Element 軟體文檔"]
* https://docs.netapp.com/us-en/vcp/index.html["NetApp Element vCenter Server 插件"^]

