---
permalink: storage/task_data_protection_create_a_snapshot_schedule.html 
sidebar: sidebar 
keywords: snapshot schedule, create, volumes, recurring schedule 
summary: 您可以排程對一個或多個磁碟區進行快照，使其依指定的時間間隔自動執行。 
---
= 建立快照計劃
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以排程對一個或多個磁碟區進行快照，使其依指定的時間間隔自動執行。

配置快照計劃時，您可以選擇基於星期幾或月份幾的時間間隔。您也可以建立重複計劃，並指定下次快照發生的日期、小時和分鐘。

如果您安排快照運行的時間段無法被 5 分鐘整除，則快照將在下一個能被 5 分鐘整除的時間段運行。例如，如果您安排快照在 UTC 時間 12:42:00 運行，它將在 UTC 時間 12:45:00 運行。您無法安排快照運行的間隔小於 5 分鐘。

從 Element 12.5 開始，您可以從使用者介面啟用序列建立並選擇以先進先出 (FIFO) 原則保留快照。

* *啟用序列建立*選項指定一次只複製一個快照。當先前的快照複製仍在進行中時，建立新快照會失敗。如果未選取該複選框，則允許在另一個快照複製仍在進行時建立快照。
* *FIFO* 選項增加了保留一致數量的最新快照的功能。選取該複選框後，快照將以先進先出 (FIFO) 的原則保留。當 FIFO 快照佇列達到最大深度後，插入新的 FIFO 快照時，最舊的 FIFO 快照將會被丟棄。


.步驟
. 選擇“資料保護”>“日程安排”。
. 選擇“建立日程”。
. 在「磁碟區 ID CSV」欄位中，輸入單一磁碟區 ID 或以逗號分隔的磁碟區 ID 列表，以包含在快照操作中。
. 請輸入新的課程表名稱。
. 選擇日程類型，並從提供的選項中設定日程。
. *可選：*選擇*重複計劃*可無限期重複快照計劃。
. *可選：*在「新快照名稱」欄位中輸​​入新快照的名稱。
+
如果將此欄位留空，系統將使用快照建立的時間和日期作為名稱。

. *可選：*選取「配對時在複製中包含快照」複選框，以確保在配對父卷時，快照被捕獲到複製中。
. *可選：*選取「啟用序列建立」複選框，以確保一次只複製一個快照。
. 若要設定快照的保留期限，請從下列選項中選擇：
+
** *可選：*選取 *FIFO（先進先出）*複選框，以保留一致數量的最新快照。
** 選擇「永久保留」可將快照無限期地保留在系統中。
** 選擇“設定保留期限”，然後使用日期微調框選擇系統保留快照的時間長度。


. 選擇“建立日程”。

