---
permalink: storage/task_per_node_run_system_tests.html 
sidebar: sidebar 
keywords: storage nodes, running system tests,s ystem tests, network settings, testing changes 
summary: 將網路設定變更提交至網路配置後，即可進行測試。您可以執行測試以確保儲存節點穩定，並且可以毫無問題地上線。 
---
= 使用節點級用戶介面運行系統測試。
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
將網路設定變更提交至網路配置後，即可進行測試。您可以執行測試以確保儲存節點穩定，並且可以毫無問題地上線。

您已登入儲存節點的單節點使用者介面。

. 點選“系統測試”。
. 按一下要執行的測試旁邊的「執行測試」或選擇「執行所有測試」。
+

NOTE: 運行所有測試操作可能很耗時，並且只能在NetApp支援人員的指導下進行。

+
** *測試連線整合*
+
測試並驗證與資料庫集合的連接性。預設情況下，測試使用節點所屬叢集的整合模型。或者，您可以提供不同的組件來測試連接性。

** *測試連接Mvip*
+
ping 指定的管理虛擬 IP (MVIP) 位址，然後向 MVIP 執行簡單的 API 呼叫以驗證連線性。預設情況下，測試使用節點所屬叢集的 MVIP。

** *測試連接Svip*
+
使用與網路介面卡上設定的最大傳輸單元 (MTU) 大小相符的 Internet 控制訊息協定 (ICMP) 封包來 ping 指定的儲存虛擬 IP (SVIP) 位址。然後它作為 iSCSI 發起程序連接到 SVIP。預設情況下，測試使用節點所屬叢集的 SVIP。

** *測試硬體配置*
+
測試所有硬體配置是否正確，驗證韌體版本是否正確，並確認所有驅動器均已安裝並正常運作。這與工廠測試相同。

+

NOTE: 此測試會佔用大量資源，僅應在NetApp支援部門要求時執行。

** *測試本地連線*
+
透過 ping 叢集 IP (CIP) 來測試與叢集中所有其他節點的連接性。只有當節點屬於活動叢集時，此測試才會顯示在該節點上。

** *測試定位集群*
+
驗證節點是否可以找到叢集配置中指定的叢集。

** *測試網路配置*
+
驗證配置的網路設定與系統上使用的網路設定是否相符。本測試並非旨在偵測節點在叢集中積極參與運行時發生的硬體故障。

** *測試 Ping*
+
對指定的主機列表進行 ping 操作；如果沒有指定主機，則動態建置叢集中所有已註冊節點的列表，並對每個節點進行 ping 操作以實現簡單的連接。

** *測試遠端連線*
+
透過 ping 叢集 IP (CIP) 來測試與遠端配對叢集中所有節點的連線性。只有當節點屬於活動叢集時，此測試才會顯示在該節點上。




