---
permalink: setup/concept_setup_configure_a_storage_node.html 
sidebar: sidebar 
keywords: configuring node,configure storage node,configuring using TUI,configuring using node UI 
summary: 必須先配置各個節點，然後才能將其新增至叢集。在機架單元中安裝節點並連接線纜並通電後，可以使用每個節點的 UI 或節點終端使用者介面配置節點網路設定。 
---
= 配置儲存節點
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
必須先配置各個節點，然後才能將其新增至叢集。在機架單元中安裝節點並連接電纜並通電後，可以使用每個節點的 UI 或節點終端使用者介面 (TUI) 設定節點網路設定。請確保您已具備節點所需的網路設定資訊後再繼續操作。

配置儲存節點有兩種方法：

* <<使用節點級使用者介面配置儲存節點。,每個節點的使用者介面>>使用節點級使用者介面 (`https://<node_management_IP>:442`）配置節點網路設定。
* <<使用 TUI 設定儲存節點,途易>>使用節點終端使用者介面（TUI）配置節點。


您無法將具有 DHCP 指派的 IP 位址的節點新增至叢集。您可以使用 DHCP IP 位址在每個節點的 UI、TUI 或 API 中對節點進行初始設定。在初始配置期間，您可以新增靜態 IP 位址訊息，以便將節點新增至叢集。

完成初始設定後，您可以使用節點的管理 IP 位址存取該節點。然後您可以更改節點設定、將其新增至集群，或使用該節點建立集群。您也可以使用 Element 軟體 API 方法來設定新節點。


NOTE: 從 Element 版本 11.0 開始，節點可以設定 IPv4、IPv6 或兩者的位址作為其管理網路。這適用於儲存節點和管理節點，但管理節點 11.3 及更高版本除外，此版本不支援 IPv6。建立叢集時，MVIP 只能使用單一 IPv4 或 IPv6 位址，並且必須在所有節點上配置對應的位址類型。



== 使用節點級使用者介面配置儲存節點。

您可以使用每個節點的使用者介面來配置節點。

.關於此任務
* 您可以將節點設定為具有 IPv4 位址或 IPv6 位址。
* 您需要 TUI 中顯示的 DHCP 位址才能存取節點。不能使用 DHCP 位址將節點新增至叢集。
+

IMPORTANT: 您應該為不同的子網路設定管理（Bond1G）和儲存（Bond10G）介面。如果 Bond1G 和 Bond10G 介面配置為相同子網路，則透過 Bond1G 介面傳送儲存流量時會導致路由問題。如果必須使用相同子網路進行管理和儲存流量，請手動設定管理流量以使用 Bond10G 介面。您可以使用每個節點的 UI 的「叢集設定」頁面對每個節點執行此操作。



.步驟
. 在瀏覽器視窗中，輸入節點的 DHCP IP 位址。
+
您必須新增擴充名 `:442` 訪問節點；例如， `https://172.25.103.6:442`。

+
「網路設定」標籤開啟後，首先顯示的是「Bond1G」部分。

. 進入1G管理網路設定。
. 按一下“應用變更”。
. 點選 *Bond10G* 顯示 10G 儲存網路設定。
. 輸入 10G 儲存網路設定。
. 按一下“應用變更”。
. 點選*集群設定*。
. 請輸入 10G 網路的主機名稱。
. 請輸入群集名稱。
+

IMPORTANT: 在建立叢集之前，必須將此名稱新增至所有節點的配置中。叢集中的所有節點必須具有相同的叢集名稱。群集名稱區分大小寫。

. 按一下“應用變更”。




== 使用 TUI 設定儲存節點

您可以使用終端使用者介面 (TUI) 對新節點進行初始設定。

您應該為不同的子網路設定 Bond1G（管理）和 Bond10G（儲存）介面。如果 Bond1G 和 Bond10G 介面配置為相同子網路，則透過 Bond1G 介面傳送儲存流量時會出現路由問題。如果必須使用相同子網路進行管理和儲存流量，請手動設定管理流量以使用 Bond10G 介面。您可以使用 Element UI 的「叢集」>「節點」頁面對每個節點執行此操作。

.步驟
. 將鍵盤和顯示器連接到節點，然後開啟節點電源。
+
NetApp儲存的 TUI 主選單出現在 tty1 終端機上。

+

NOTE: 如果節點無法連線到您的設定伺服器，TUI 將顯示錯誤訊息。檢查設定伺服器連線或網路連線以解決錯誤。

. 選擇“網路”>“網路配置”。
+

TIP: 若要瀏覽選單，請按向上或向下箭頭鍵。若要切換到另一個按鈕或從按鈕切換到字段，請按 *Tab* 鍵。若要在欄位之間導航，請使用向上或向下箭頭鍵。

. 選擇 *Bond1G（管理）* 或 *Bond10G（儲存）* 來配置節點的 1G 和 10G 網路設定。
. 對於「綁定模式」和「狀態」字段，按 *Tab* 選擇「幫助」按鈕，即可查看可用選項。
+
叢集中的所有節點必須具有相同的叢集名稱。群集名稱區分大小寫。如果網路上執行 DHCP 伺服器，並且有可用的 IP 位址，則 1GbE 位址會出現在位址欄位中。

. 按 *Tab* 鍵選擇 *OK* 按鈕並儲存變更。
+
此節點處於待定狀態，可以新增到現有叢集或新叢集中。





== 查找更多信息

* https://docs.netapp.com/us-en/element-software/index.html["SolidFire和 Element 軟體文檔"]
* https://docs.netapp.com/us-en/vcp/index.html["NetApp Element vCenter Server 插件"^]

