---
permalink: setup/task_setup_fc_create_a_new_cluster_with_fibre_channel_nodes.html 
sidebar: sidebar 
keywords:  
summary: 配置完各光纖通道節點後，即可建立新叢集。建立叢集時，系統會自動為您建立一個叢集管理員使用者帳戶。群集管理員有權管理所有群集屬性，並且可以建立其他群集管理員帳戶。 
---
= 建立包含光纖通道節點的新集群
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
配置完各光纖通道節點後，即可建立新叢集。建立叢集時，系統會自動為您建立一個叢集管理員使用者帳戶。群集管理員有權管理所有群集屬性，並且可以建立其他群集管理員帳戶。

在新節點配置期間，會為每個節點指派 1G 或 10G 管理 IP (MIP) 位址。您必須使用配置過程中建立的節點 IP 位址之一來開啟「建立新叢集」頁面。您使用的 IP 位址取決於您為叢集管理選擇的網路。

.你需要什麼
您已配置各光纖通道節點。

.步驟
. 在瀏覽器視窗中，輸入節點 MIP 位址。
. 在「建立新集群」中，輸入以下資訊：
+
** 管理 VIP：1GbE 或 10GbE 網路上的可路由虛擬 IP，用於網路管理任務。
** iSCSI（儲存）VIP：10GbE 網路上的虛擬 IP，用於儲存和 iSCSI 發現。
+

NOTE: 建立叢集後，無法變更 SVIP。

** 使用者名稱：用於對叢集進行身份驗證存取的主集群管理員使用者名稱。您必須儲存使用者名稱以備將來參考。
+

NOTE: 使用者名稱可以使用大寫字母、小寫字母、特殊字元和數字。

** 密碼：用於對叢集進行身份驗證存取的密碼。您必須儲存使用者名稱以備將來參考。雙向資料保護預設啟用。您無法變更此設定。


. 請閱讀最終用戶許可協議，然後點擊“我同意”。
. *可選*：在節點清單中，確保不應包含在叢集中的節點的複選框未被選取。
. 點選「建立集群」。
+
根據叢集中節點的數量，系統可能需要幾分鐘時間來建立叢集。在配置正確的網路上，一個由五個節點組成的小叢集應該在一分鐘內完成。叢集建立完成後，「建立新叢集」視窗將重定向到叢集的 MVIP URL 位址並顯示 Web UI。





== 查找更多信息

* https://docs.netapp.com/us-en/element-software/index.html["SolidFire和 Element 軟體文檔"]
* https://docs.netapp.com/us-en/vcp/index.html["NetApp Element vCenter Server 插件"^]

