---
permalink: api/reference_element_api_setconfig.html 
sidebar: sidebar 
keywords: config,configuration,set,setting,node,setconfig,network,cluster 
summary: 您可以使用 SetConfig 方法設定節點的網路和叢集資訊。此方法在一個 API 方法中包含了與 SetClusterConfig 和 SetNetworkConfig 方法相同的設定。此方法只需包含您想要變更的欄位即可。 
---
= 設定配置
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
你可以使用 `SetConfig`設定節點網路和叢集資訊的方法。此方法在一個 API 方法中包含了相同的設置，這兩種方法都可用。 `SetClusterConfig`和 `SetNetworkConfig`方法。此方法只需包含您想要變更的欄位即可。



== 範圍

警告：

更改節點上的綁定模式可能會導致網路連線暫時中斷。

此方法有以下輸入參數：

|===
| Name | 描述 | 類型 | 預設值 | 必需的 


 a| 
簇
 a| 
叢集訊息，用於標識儲存節點如何與其關聯的儲存叢集進行通訊。
 a| 
xref:reference_element_api_cluster.adoc[簇]
 a| 
沒有任何
 a| 
不



 a| 
網路
 a| 
節點的每個網路介面的網路連線類型和目前設定。
 a| 
xref:reference_element_api_network_all_interfaces.adoc[網路（所有介面）]
 a| 
沒有任何
 a| 
不

|===


== 傳回值

此方法傳回以下值：

|===
| Name | 描述 | 類型 


 a| 
配置
 a| 
節點的新配置和當前配置。此物件包含：

* xref:reference_element_api_cluster.adoc[簇]：集群訊息，用於標識儲存節點如何與其關聯的儲存集群進行通訊。
* xref:reference_element_api_network_all_interfaces.adoc[網路（所有介面）]：節點的每個網路介面的網路連線類型和目前設定。

 a| 
JSON 物件

|===


== 請求範例

該方法的請求類似於以下範例：

[listing]
----
{
	"method": "SetConfig",
	"params": {
		"cluster": {
			"name": "MyHostname"
		},
		"network": {
			"Bond10G": {
				"bond-mode": "ALB"
			}
		}
	}
}
----


== 回應範例

此方法的回應與 GetConfig 方法的回傳值相同。使用 SetConfig 時，可以看到物件顯示的所有欄位和更新後的值。



== 自版本以來的新版本

9.6



== 查找更多信息

* xref:reference_element_api_setclusterconfig.adoc[設定叢集配置]
* xref:reference_element_api_setnetworkconfig.adoc[設定網路配置]
* xref:reference_element_api_response_example_getconfig.adoc[GetConfig]

