---
permalink: api/reference_element_api_createkeyserverkmip.html 
sidebar: sidebar 
keywords: KMIP,key server,creating,create 
summary: '您可以使用 CreateKeyServerKmip 方法建立具有指定屬性的金鑰管理互通協定 (KMIP) 金鑰伺服器。創建過程中不會聯繫伺服器；使用此方法之前伺服器無需存在。對於叢集金鑰伺服器配置，您必須在 kmipKeyServerHostnames 參數中提供所有伺服器節點的主機名稱或 IP 位址。您可以使用 TestKeyServerKmip 方法測試金鑰伺服器。' 
---
= 建立金鑰伺服器Kmip
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
你可以使用 `CreateKeyServerKmip`建立具有指定屬性的金鑰管理互通協定 (KMIP) 金鑰伺服器的方法。創建過程中不會聯繫伺服器；使用此方法之前伺服器無需存在。對於叢集金鑰伺服器配置，您必須在 kmipKeyServerHostnames 參數中提供所有伺服器節點的主機名稱或 IP 位址。你可以使用 `TestKeyServerKmip`測試密鑰伺服器的方法。



== 參數

此方法有以下輸入參數：

|===
| Name | 描述 | 類型 | 預設值 | 必需的 


 a| 
kmipCa證書
 a| 
外部金鑰伺服器根 CA 的公鑰憑證。這將用於驗證外部金鑰伺服器在 TLS 通訊中提供的憑證。對於關鍵伺服器集群，如果各個伺服器使用不同的 CA，則提供包含所有 CA 根憑證的連接字串。
 a| 
細繩
 a| 
沒有任何
 a| 
是的



 a| 
kmipClientCertificate
 a| 
Solidfire KMIP 用戶端使用的 PEM 格式 Base64 編碼 PKCS#10 X.509 憑證。
 a| 
細繩
 a| 
沒有任何
 a| 
是的



 a| 
kmipKeyServerHostnames
 a| 
與此 KMIP 金鑰伺服器關聯的主機名稱或 IP 位址陣列。只有當關鍵伺服器處於叢集配置時，才需要提供多個主機名稱或 IP 位址。
 a| 
字串數組
 a| 
沒有任何
 a| 
是的



 a| 
kmipKeyServerName
 a| 
KMIP密鑰伺服器的名稱。此名稱僅用於顯示目的，無需唯一。
 a| 
細繩
 a| 
沒有任何
 a| 
是的



 a| 
kmipKeyServerPort
 a| 
與此 KMIP 金鑰伺服器關聯的連接埠號碼（通常為 5696）。
 a| 
整數
 a| 
沒有任何
 a| 
不

|===


== 傳回值

此方法具有以下傳回值：

|===


| Name | 描述 | 類型 


 a| 
kmip金鑰伺服器
 a| 
包含有關新建立的密鑰伺服器詳細資訊的物件。
 a| 
link:reference_element_api_keyserverkmip.html["金鑰伺服器Kmip"]

|===


== 請求範例

該方法的請求類似於以下範例：

[listing]
----
{
  "method": "CreateKeyServerKmip",
  "params": {
    "kmipCaCertificate": "MIICPDCCAaUCEDyRMcsf9tAbDpq40ES/E...",
    "kmipClientCertificate": "dKkkirWmnWXbj9T/UWZYB2oK0z5...",
    "kmipKeyServerHostnames" : ["server1.hostname.com", "server2.hostname.com"],
    "kmipKeyServerName" : "keyserverName",
    "kmipKeyServerPort" : 5696
  },
"id": 1
}
----


== 回應範例

此方法傳回類似以下範例的回應：

[listing]
----
{
   "id": 1,
   "result":
      {
        "kmipKeyServer": {
            "kmipCaCertificate":"MIICPDCCAaUCEDyRMcsf9tAbDpq40ES/E...",
            "kmipKeyServerHostnames":[
                "server1.hostname.com", "server2.hostname.com"
            ],
            "keyProviderID":1,
            "kmipKeyServerName":"keyserverName",
            "keyServerID":1
            "kmipKeyServerPort":1,
            "kmipClientCertificate":"dKkkirWmnWXbj9T/UWZYB2oK0z5...",
            "kmipAssignedProviderIsActive":true
        }
    }
}
----


== 自版本以來的新版本

11.7
