---
permalink: api/reference_element_api_createsnapmirrorrelationship.html 
sidebar: sidebar 
keywords: SnapMirror,relationship,relationships,create,creating,CreateSnapMirrorRelationship 
summary: Element Web UI 使用 CreateSnapMirrorRelationship 方法在來源端點和目標端點之間建立SnapMirror擴充資料保護關係。 
---
= 建立快照鏡像關係
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Element Web UI 使用 `CreateSnapMirrorRelationship`在來源端點和目標端點之間建立SnapMirror擴展資料保護關係的方法。



== 參數

此方法有以下輸入參數：

|===
| Name | 描述 | 類型 | 預設值 | 必需的 


 a| 
snapMirrorEndpointID
 a| 
與 Element 儲存叢集通訊的遠端ONTAP儲存系統的端點 ID。
 a| 
整數
 a| 
沒有任何
 a| 
是的



 a| 
來源磁碟區
 a| 
關係中的源量。
 a| 
xref:reference_element_api_snapmirrorvolumeinfo.adoc[snapMirrorVolumeInfo]
 a| 
沒有任何
 a| 
是的



 a| 
目的地捲
 a| 
該關係中的目的地流量。
 a| 
xref:reference_element_api_snapmirrorvolumeinfo.adoc[snapMirrorVolumeInfo]
 a| 
沒有任何
 a| 
是的



 a| 
關係類型
 a| 
關係類型。在執行 Element 軟體的儲存系統中，此值始終為「`extended_data_protection`」。
 a| 
細繩
 a| 
沒有任何
 a| 
不



 a| 
策略名稱
 a| 
指定關係的ONTAP SnapMirror策略的名稱。如果未指定，則預設策略名稱為 MirrorLatest。
 a| 
細繩
 a| 
沒有任何
 a| 
不



 a| 
計劃名稱
 a| 
ONTAP系統上預先存在的 cron 計畫的名稱，用於更新SnapMirror關係。如果沒有指定更新計劃，snapMirror 更新將不會進行，必須手動更新。
 a| 
細繩
 a| 
沒有任何
 a| 
不



 a| 
最大轉帳費率
 a| 
指定磁碟區之間的最大資料傳輸速率，單位為千字節每秒。預設值 0 表示無限制，允許SnapMirror關係充分利用可用的網路頻寬。
 a| 
整數
 a| 
沒有任何
 a| 
不

|===


== 傳回值

此方法具有以下傳回值：

|===


| Name | 描述 | 類型 


 a| 
snapMirror關係
 a| 
關於新建立的SnapMirror合作關係的資訊。
 a| 
xref:reference_element_api_snapmirrorrelationship.adoc[snapMirror關係]

|===


== 自版本以來的新版本

10.1
