---
permalink: api/reference_element_api_resyncsnapmirrorrelationship.html 
sidebar: sidebar 
keywords: SnapMirror,relationship,resync,resyncing,ResyncSnapMirrorRelationship 
summary: Element 軟體 Web UI 使用 ResyncSnapMirrorRelationship 方法建立或重新建立來源端點和目標端點之間的鏡像關係。重新同步關係時，系統會刪除目標磁碟區上比公開快照副本更新的快照，然後將目標磁碟區掛載為資料保護磁碟區，並將公用快照副本作為匯出的快照副本。 
---
= 重新同步快照鏡像關係
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Element軟體的Web使用者介面使用 `ResyncSnapMirrorRelationship`建立或重新建立來源端點和目標端點之間鏡像關係的方法。重新同步關係時，系統會刪除目標磁碟區上比公開快照副本更新的快照，然後將目標磁碟區掛載為資料保護磁碟區，並將公用快照副本作為匯出的快照副本。



== 參數

此方法有以下輸入參數：

|===
| Name | 描述 | 類型 | 預設值 | 必需的 


 a| 
snapMirrorEndpointID
 a| 
與 Element 儲存叢集通訊的遠端ONTAP儲存系統的端點 ID。
 a| 
整數
 a| 
沒有任何
 a| 
是的



 a| 
目的地捲
 a| 
SnapMirror關係中的目標磁碟區。
 a| 
xref:reference_element_api_snapmirrorvolumeinfo.adoc[snapMirrorVolumeinfo]
 a| 
沒有任何
 a| 
是的



 a| 
最大轉帳費率
 a| 
指定磁碟區之間的最大資料傳輸速率，單位為千字節每秒。預設值 0 表示無限制，允許SnapMirror關係充分利用可用的網路頻寬。
 a| 
整數
 a| 
沒有任何
 a| 
不



 a| 
來源磁碟區
 a| 
SnapMirror關係中的來源磁碟區。
 a| 
xref:reference_element_api_snapmirrorvolumeinfo.adoc[snapMirrorVolumeinfo]
 a| 
沒有任何
 a| 
不

|===


== 傳回值

此方法傳回以下值：

|===


| Name | 描述 | 類型 


 a| 
snapMirror關係
 a| 
包含重新同步的SnapMirror關係的資訊的物件。
 a| 
xref:reference_element_api_snapmirrorrelationship.adoc[snapMirror關係]

|===


== 自版本以來的新版本

10.1
