---
permalink: api/reference_element_api_deletevolumes.html 
sidebar: sidebar 
keywords: volumes,volume,delete,deleting,multiple,DeleteVolumes 
summary: 您可以使用 DeleteVolumes 方法將多個（最多 500 個）活動磁碟區標記為要刪除。標記後，在清理間隔結束後，該磁碟區將被清除（永久刪除）。 
---
= 刪除卷
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
你可以使用 `DeleteVolumes`標記多個（最多 500 個）活動卷以進行刪除的方法。標記後，在清理間隔結束後，該磁碟區將被清除（永久刪除）。

發出刪除磁碟區的請求後，與該磁碟區的任何活動的 iSCSI 連線都會立即終止，並且在該磁碟區處於此狀態期間不允許建立任何進一步的連線。目標發現請求中不會傳回已標記的磁碟區。

任何已標記為刪除的磁碟區的快照均不受影響。快照會一直保留到該磁碟區從系統中清除為止。如果磁碟區被標記為要刪除，並且正在進行批次磁碟區讀取或批次磁碟區寫入操作，則停止批次磁碟區讀取或寫入操作。

如果要刪除的磁碟區與某個磁碟區配對，則配對磁碟區之間的複製將暫停，並且在刪除狀態下不會向這些磁碟區傳輸任何資料或從這些磁碟區傳輸任何資料。與已刪除卷配對的遠端卷進入 PausedMisconfigured 狀態，資料不再傳送到這些遠端卷，也不再從已刪除卷發送資料。在已刪除的磁碟區被徹底清除之前，它們可以被恢復，資料傳輸也可以繼續進行。如果從系統中清除已刪除的捲，則與其配對的捲將進入「已停止但配置錯誤的」狀態，並且磁碟區配對狀態將被移除。被清除的磁碟區將永久無法存取。



== 參數

此方法有以下輸入參數。


NOTE: 以下參數中至少需要選擇一個，並且只能使用其中一個參數（它們彼此互斥）。

|===
| Name | 描述 | 類型 | 預設值 | 必需的 


 a| 
卷 ID
 a| 
要從系統中刪除的磁碟區的 ID 清單。
 a| 
整數數組
 a| 
沒有任何
 a| 
參見註釋。



 a| 
磁碟區存取群組 ID
 a| 
磁碟區存取群組 ID 清單。您在此清單中指定的所有磁碟區存取群組中的所有磁碟區將從系統中刪除。
 a| 
整數數組
 a| 
沒有任何
 a| 
參見註釋。



 a| 
帳戶ID
 a| 
帳戶ID列表。這些帳戶中的所有磁碟區都已從系統中刪除。
 a| 
整數數組
 a| 
沒有任何
 a| 
參見註釋。

|===


== 傳回值

此方法具有以下傳回值：

|===


| Name | 描述 | 類型 


 a| 
卷
 a| 
關於新刪除卷的資訊。
 a| 
xref:reference_element_api_volume.adoc[體積]



 a| 
曲線
 a| 
曲線是一組鍵值對。關鍵訊息是 I/O 大小（以位元組為單位）。這些數值代表在特定 I/O 尺寸下進行 IOP 的成本。此曲線是相對於 4096 位元組操作，IOPS 設定為 100 的計算結果。
 a| 
JSON 物件

|===


== 請求範例

該方法的請求類似於以下範例：

[listing]
----
{
   "method": "DeleteVolumes",
   "params": {
      "accountIDs" : [1, 2, 3]
   },
   "id" : 1
}
----


== 回應範例

此方法傳回類似以下範例的回應：

[listing]
----

{
  "id" : 1,
  "result": {
    "volumes" : [ {
      "access": "readWrite",
      "accountID": 1,
      "attributes": {},
      "blockSize": 4096,
      "createTime": "2015-03-06T18:50:56Z",
      "deleteTime": "",
      "enable512e": False,
      "iqn": "iqn.2010-01.com.solidfire:pzsr.vclient-030-v00001.1",
      "name": "vclient-030-v00001",
      "qos": {
        "burstIOPS": 15000,
        "burstTime": 60,
        "curve": {},
        "maxIOPS": 15000,
        "minIOPS": 100
      },
      "purgeTime": "",
      "sliceCount": 1,
      "scsiEUIDeviceID": "707a737200000001f47acc0100000000",
      "scsiNAADeviceID": "6f47acc100000000707a737200000001",
      "status": "active",
      "totalSize": 10000003072,
      "virtualVolumeID": 5,
      "volumeAccessGroups": [],
      "volumePairs": [],
      "volumeID": 1
    } ]
  }
}
----


== 自版本以來的新版本

9.6
