---
permalink: api/reference_element_api_modifyvolumes.html 
sidebar: sidebar 
keywords: volume,volumes,modifying,modify,change,changing,edit,editing,modifyvolumes 
summary: 您可以使用 ModifyVolumes 方法一次配置多達 500 個現有磁碟區。變化立即發生。如果 ModifyVolumes 無法修改任何指定的捲，則所有指定的捲都不會變更。 
---
= 修改卷
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
你可以使用 `ModifyVolumes`一次配置多達 500 個現有磁碟區的方法。變化立即發生。如果 `ModifyVolumes`未能修改任何指定的捲，所有指定的捲均未更改。

如果在修改磁碟區時未指定 QoS 值，則每個磁碟區的 QoS 值保持不變。您可以透過執行以下命令來檢索新建立磁碟區的預設 QoS 值： `GetDefaultQoS`方法。

當您需要增加正在複製的磁碟區的大小時，請按以下順序操作，以防止複製錯誤：

. 使用 replicationTarget 存取權增加磁碟區的大小。
. 增加具有讀寫存取權限的來源或磁碟區的大小。


確保目標磁碟區和來源磁碟區的大小相同。


NOTE: 如果將存取狀態變更為 locked 或 replicationTarget，則所有現有的 iSCSI 連線都會終止。



== 參數

此方法有以下輸入參數：

|===
| Name | 描述 | 類型 | 預設值 | 必需的 


 a| 
使用權
 a| 
允許存取這些卷。可能的值：

* `readOnly`只允許讀取操作。
* `readWrite`允許讀寫操作。
* `locked`不允許任何讀取或寫入操作。如果未指定，則存取值不會改變。
* `replicationTarget`求一組成對體積的目標體積。如果磁碟區未配對，則存取狀態將被鎖定。如果未指定值，則存取值不會改變。

 a| 
細繩
 a| 
沒有任何
 a| 
不



 a| 
帳戶ID
 a| 
磁碟區被重新指派給的帳號 ID。如果沒有指定，則使用先前的帳戶名稱。
 a| 
整數
 a| 
沒有任何
 a| 
不



 a| 
與QoS策略關聯
 a| 
將磁碟區與指定的QoS策略關聯起來。可能的值：

* `true`將磁碟區與 QoSPolicyID 參數中指定的 QoS 策略關聯。
* `false`請勿將磁碟區與 QoSPolicyID 參數中指定的 QoS 策略關聯。如果為 false，則會刪除任何現有的政策關聯，無論是否在 QoSPolicy 參數中指定 QoS 策略。

 a| 
布林值
 a| 
沒有任何
 a| 
不



 a| 
屬性
 a| 
JSON 物件格式的名稱-值對清單。
 a| 
JSON 物件
 a| 
沒有任何
 a| 
不



 a| 
創建時間
 a| 
若要設定為新磁碟區建立日期的 ISO 8601 日期字串。如果 setCreateTime 設定為 true，則此參數為必填項。
 a| 
ISO 8601字串
 a| 
沒有任何
 a| 
不



 a| 
不要移動 Iops 重新平衡
 a| 
使用實際 IOPS 進行負載平衡時，防止磁碟區移動。此設定從 Element 12.8 版本開始可用，僅在以下情況下生效：link:reference_element_api_enablefeature.html["VolumeLoadBalanceOnActualIOPS"]已啟用。可能的值：

* `true`磁碟區不會根據實際 IOPS 進行負載平衡。
* `false`卷會根據實際 IOPS 進行負載平衡。


*注意*：高可用性（節點故障）的負載平衡優先於 `VolumeLoadBalanceOnActualIOPS`和 `dontMoveforIopsRebalance`。
| 布林值 | 錯誤的 | 不 


 a| 
啟用 SnapMirror 複製
 a| 
確定該磁碟區是否可用於與SnapMirror端點進行複製。可能的值：

* `true`
* `false`

 a| 
布林值
 a| 
錯誤的
 a| 
不



| 先進先出大小 | 指定磁碟區支援的最大先進先出 (FIFO) 快照數。請注意，FIFO 快照和非 FIFO 快照都使用磁碟區上相同的可用快照槽池。使用此選項可限制 FIFO 快照對可用快照插槽的消耗。請注意，您不能將此值修改為小於目前 FIFO 快照計數。 | 整數 | 沒有任何 | 不 


| 最小FIFO大小 | 指定僅用於先進先出 (FIFO) 快照的快照槽數量。由於 FIFO 和非 FIFO 快照共用同一個池，因此 minFifoSize 參數會將可能的非 FIFO 快照的總數減少相同的數量。請注意，您不能修改此值，使其與目前的非 FIFO 快照計數衝突。 | 整數 | 沒有任何 | 不 


 a| 
模式
 a| 
卷複製模式。可能的值：

* `asynch`等待系統確認資料已儲存在來源端後再寫入目標端。
* `sync`：不等待來源端的資料傳輸確認，即開始向目標端寫入資料。

 a| 
細繩
 a| 
沒有任何
 a| 
不



 a| 
服務品質
 a| 
新的音量服務品質設定。如果未指定，則 QoS 設定不會變更。可能的值：

* `minIOPS`
* `maxIOPS`
* `burstIOPS`

 a| 
xref:reference_element_api_qos.adoc[服務品質]
 a| 
沒有任何
 a| 
不



 a| 
qosPolicyID
 a| 
若要將 QoS 設定套用至指定磁碟區的策略的 ID。此參數與 QoS 參數互斥。
 a| 
整數
 a| 
沒有任何
 a| 
不



 a| 
設定創建時間
 a| 
設定為 true 可變更磁碟區建立記錄日期。
 a| 
布林值
 a| 
沒有任何
 a| 
不



 a| 
總大小
 a| 
卷的新大小（以位元組為單位）。 1000000000 等於 1GB。檔案大小向上取整到最接近的兆位元組。此參數只能用於增加體積的大小。
 a| 
整數
 a| 
沒有任何
 a| 
不



 a| 
卷 ID
 a| 
要修改的磁碟區的 volumeID 清單。
 a| 
整數數組
 a| 
沒有任何
 a| 
是的

|===


== 傳回值

此方法傳回以下值：

|===
| Name | 描述 | 類型 


 a| 
體積
 a| 
包含每個新修改磁碟區資訊的陣列物件。
 a| 
xref:reference_element_api_volume.adoc[體積]大批

|===


== 請求範例

該方法的請求類似於以下範例：

[listing]
----
{
  "method": "ModifyVolumes",
  "params": {
    "volumeIDs": [319,22],
    "access": "readWrite",
    "dontMoveForIopsRebalance": false
  },
  "id": 1
}
----


== 回應範例

此方法傳回類似以下範例的回應：

[listing]
----
{
  "id": 1,
  "result": {
    "volumes":
      {
        "access":  "readWrite,
        "accountID": 22,
        "attributes": {},
        "blockSize": 4096,
        "createTime": "2024-04-01T19:39:40Z",
        "currentProtectionScheme": "doubleHelix",
        "deleteTime": "",
        "dontMoveForIopsRebalance": false,
        "enable512e": false,
        "enableSnapMirrorReplication": false,
        "fifoSize": 24,
        "iqn": "iqn.2010-01.com.solidfire:3eeu.suite40.319",
        "lastAccessTime": "2024-04-02T12:41:34Z",
        "lastAccessTimeIO": "2024-04-01T20:41:19Z",
        "minFifoSize": 0,
        "name": "suite40",
        "previousProtectionScheme": null,
        "purgeTime": "",
        "qos": {
          "burstIOPS": 27000,
          "burstTime": 60,
          "curve": {
            "1048576": 15000,
            "131072": 1950,
            "16384": 270,
            "262144": 3900,
            "32768": 500,
            "4096": 100,
            "524288": 7600,
            "65536": 1000,
            "8192": 160
          },
          "maxIOPS": 27000,
          "minIOPS": 500
        },
        "qosPolicyID": null,
        "scsiEUIDeviceID": "336565750000013ff47acc0100000000",
        "scsiNAADeviceID": "6f47acc100000000336565750000013f",
        "sliceCount": 1,
        "status": "active",
        "totalSize": 1000000716800,
        "virtualVolumeID": null,
        "volumeAccessGroups": [
        22
        ],
        "volumeConsistencyGroupUUID": "3003109e-6e75-444c-8cee-470d641a09c3",
        "volumeID": 319,
        "volumePairs": [],
        "
      }
  }
}
----


== 自版本以來的新版本

9.6



== 查找更多信息

xref:reference_element_api_getdefaultqos.adoc[取得預設服務質量]
