---
permalink: api/reference_element_api_creategroupsnapshot.html 
sidebar: sidebar 
keywords: volume,volumes,snapshot,snapshots,CreateGroupSnapshot,group,create,creating 
summary: 您可以使用 CreateGroupSnapshot 建立一組磁碟區的某個時間點的副本。 
---
= 建立群組快照
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 `CreateGroupSnapshot`建立一組磁碟區的某個時間點的副本。

您可以稍後使用此快照作為備份或回滾，以確保磁碟區組上的資料在您建立快照的時間點保持一致。

*集群滿度*


NOTE: 如果叢集容量處於第 1、2 或 3 階段，則可以建立快照。當叢集容量達到 4 或 5 級時，無法建立快照。



== 參數

此方法有以下輸入參數：

|===
| Name | 描述 | 類型 | 預設值 | 必需的 


 a| 
`attributes`
 a| 
JSON 物件格式的名稱-值對清單。
 a| 
JSON 物件
 a| 
沒有任何
 a| 
不



 a| 
`enableRemoteReplication`
 a| 
指定是否將快照複製到遠端儲存。可能的值：

* `true`快照將被複製到遠端儲存。
* `false`快照不會複製到遠端儲存。

 a| 
布林值
 a| 
錯誤的
 a| 
不



| `ensureSerialCreation`  a| 
指定如果先前的快照複製正在進行中，則不應建立快照。可能的值有：

* `true`這樣可以確保一次只複製一個快照。如果先前的快照複製仍在進行中，則建立新快照將會失敗。
* `false`: 預設.如果另一個快照複製仍在進行中，則允許建立此快照。

| 布林值 | `false` | 不 


 a| 
`expirationTime`
 a| 
指定快照可以刪除的時間。不能與…一起使用 `retention`。如果兩者都不是 `expirationTime`， 或者 `retention`如果指定了快照，則快照將不會過期。時間格式為 ISO 8601 日期字串，用於基於時間的過期，否則將不會過期。一個值 `null`導致快照永久保留。一個值 `fifo`使得快照依照先進先出 (FIFO) 原則相對於磁碟區上的其他 FIFO 快照進行儲存。如果沒有可用的FIFO空間，API將會失敗。
 a| 
ISO 8601 日期字串
 a| 
沒有任何
 a| 
不



 a| 
`name`
 a| 
群組快照的名稱。如果沒有輸入姓名，則使用拍攝群組快照的日期和時間。名稱長度上限為 255 個字元。
 a| 
細繩
 a| 
沒有任何
 a| 
不



 a| 
`retention`
 a| 
此參數與以下參數相同： `expirationTime`參數，但時間格式為 HH:mm:ss。如果兩者都不是 `expirationTime`也不 `retention`如果指定了快照，則快照將不會過期。
 a| 
細繩
 a| 
沒有任何
 a| 
不



 a| 
`snapMirrorLabel`
 a| 
SnapMirror軟體用於指定SnapMirror端點上的快照保留策略的標籤。
 a| 
細繩
 a| 
沒有任何
 a| 
不



 a| 
`volumes`
 a| 
要從中複製的磁碟區映像的唯一 ID。
 a| 
volumeID 數組
 a| 
沒有任何
 a| 
是的

|===


== 傳回值

此方法具有以下傳回值：

|===


| Name | 描述 | 類型 


 a| 
成員
 a| 
列出群組內每個成員的校驗和、磁碟區 ID 和快照 ID。有效值：

* 校驗和：儲存快照中資料的簡短字串表示形式。之後可以使用此校驗和來比較其他快照，以偵測資料中的錯誤。  （細繩）
* snapshotID：用於建立新快照的快照的唯一 ID。  snapshotID 必須來自給定磁碟區上的快照。  （整數）
* volumeID：快照的來源磁碟區 ID。  （整數）

 a| 
JSON 物件數組



 a| 
群組快照ID
 a| 
新群組快照的唯一 ID。
 a| 
群組快照 ID



 a| 
群組快照
 a| 
包含有關新建立的群組快照資訊的物件。
 a| 
xref:reference_element_api_groupsnapshot.adoc[群組快照]

|===


== 請求範例

該方法的請求類似於以下範例：

[listing]
----
{
   "method": "CreateGroupSnapshot",
   "params": {
      "volumes": [1,2]
   },
   "id": 1
}
----


== 回應範例

此方法傳回類似以下範例的回應：

[listing]
----
{
  "id": 1,
  "result": {
    "groupSnapshot": {
      "attributes": {},
      "createTime": "2016-04-04T22:43:29Z",
      "groupSnapshotID": 45,
      "groupSnapshotUUID": "473b78a3-ef85-4541-9438-077306b2d3ca",
      "members": [
        {
          "attributes": {},
          "checksum": "0x0",
          "createTime": "2016-04-04T22:43:29Z",
          "enableRemoteReplication": false,
          "expirationReason": "None",
          "expirationTime": null,
          "groupID": 45,
          "groupSnapshotUUID": "473b78a3-ef85-4541-9438-077306b2d3ca",
          "name": "2016-04-04T22:43:29Z",
          "snapshotID": 3323,
          "snapshotUUID": "7599f200-0092-4b41-b362-c431551937d1",
          "status": "done",
          "totalSize": 5000658944,
          "virtualVolumeID": null,
          "volumeID": 1
        },
        {
          "attributes": {},
          "checksum": "0x0",
          "createTime": "2016-04-04T22:43:29Z",
          "enableRemoteReplication": false,
          "expirationReason": "None",
          "expirationTime": null,
          "groupID": 45,
          "groupSnapshotUUID": "473b78a3-ef85-4541-9438-077306b2d3ca",
          "name": "2016-04-04T22:43:29Z",
          "snapshotID": 3324,
          "snapshotUUID": "a0776a48-4142-451f-84a6-5315dc37911b",
          "status": "done",
          "totalSize": 6001000448,
          "virtualVolumeID": null,
          "volumeID": 2
        }
      ],
      "name": "2016-04-04T22:43:29Z",
      "status": "done"
    },
    "groupSnapshotID": 45,
    "members": [
      {
        "checksum": "0x0",
        "snapshotID": 3323,
        "snapshotUUID": "7599f200-0092-4b41-b362-c431551937d1",
        "volumeID": 1
      },
      {
        "checksum": "0x0",
        "snapshotID": 3324,
        "snapshotUUID": "a0776a48-4142-451f-84a6-5315dc37911b",
        "volumeID": 2
      }
    ]
  }
}
----


== 自版本以來的新版本

9.6
