---
permalink: api/reference_element_api_modifykeyserverkmip.html 
sidebar: sidebar 
keywords: KMIP,key server,modifying,modify,change,edit 
summary: '您可以使用 ModifyKeyServerKmip 方法將現有的金鑰管理互通協定 (KMIP) 金鑰伺服器修改為指定的屬性。雖然唯一必要的參數是 keyServerID，但僅包含 keyServerID 的請求不會執行任何操作，也不會回傳任何錯誤。您指定的任何其他參數將用指定的 keyServerID 取代金鑰伺服器的現有值。操作過程中會聯繫關鍵伺服器，以確保其正常運作。您可以使用 kmipKeyServerHostnames 參數提供多個主機名稱或 IP 位址，但前提是金鑰伺服器處於叢集配置中。' 
---
= 修改金鑰伺服器Kmip
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
你可以使用 `ModifyKeyServerKmip`修改現有金鑰管理互通協定 (KMIP) 金鑰伺服器以使其具有指定屬性的方法。雖然唯一必要的參數是 keyServerID，但僅包含 keyServerID 的請求不會執行任何操作，也不會回傳任何錯誤。您指定的任何其他參數將用指定的 keyServerID 取代金鑰伺服器的現有值。操作過程中會聯繫關鍵伺服器，以確保其正常運作。您可以使用 kmipKeyServerHostnames 參數提供多個主機名稱或 IP 位址，但前提是金鑰伺服器處於叢集配置中。



== 參數

此方法有以下輸入參數：

|===


| Name | 描述 | 類型 | 預設值 | 必需的 


 a| 
密鑰伺服器ID
 a| 
要修改的KMIP金鑰伺服器的ID。
 a| 
整數
 a| 
沒有任何
 a| 
是的



 a| 
kmipCa證書
 a| 
外部金鑰伺服器根 CA 的公鑰憑證。這將用於驗證外部金鑰伺服器在 TLS 通訊中提供的憑證。對於關鍵伺服器集群，如果各個伺服器使用不同的 CA，則提供包含所有 CA 根憑證的連接字串。
 a| 
細繩
 a| 
沒有任何
 a| 
不



 a| 
kmipClientCertificate
 a| 
Solidfire KMIP 用戶端使用的 PEM 格式 Base64 編碼 PKCS#10 X.509 憑證。
 a| 
細繩
 a| 
沒有任何
 a| 
不



 a| 
kmipKeyServerHostnames
 a| 
與此 KMIP 金鑰伺服器關聯的主機名稱或 IP 位址陣列。只有當關鍵伺服器處於叢集配置時，才需要提供多個主機名稱或 IP 位址。
 a| 
字串數組
 a| 
沒有任何
 a| 
不



 a| 
kmipKeyServerName
 a| 
KMIP密鑰伺服器的名稱。此名稱僅用於顯示目的，無需唯一。
 a| 
細繩
 a| 
沒有任何
 a| 
不



 a| 
kmipKeyServerPort
 a| 
與此 KMIP 金鑰伺服器關聯的連接埠號碼（通常為 5696）。
 a| 
整數
 a| 
沒有任何
 a| 
不

|===


== 傳回值

此方法具有以下傳回值：

|===


| Name | 描述 | 類型 


 a| 
kmip金鑰伺服器
 a| 
包含有關新修改的密鑰伺服器詳細資訊的物件。
 a| 
link:reference_element_api_keyserverkmip.html["金鑰伺服器Kmip"]

|===


== 請求範例

該方法的請求類似於以下範例：

[listing]
----
{
  "method": "ModifyKeyServerKmip",
  "params": {
    "keyServerID": 15
    "kmipCaCertificate": "CPDCCAaUCEDyRMcsf9tAbDpq40ES/E...",
    "kmipClientCertificate": "kirWmnWXbj9T/UWZYB2oK0z5...",
    "kmipKeyServerHostnames" : ["server1.hostname.com", "server2.hostname.com"],
    "kmipKeyServerName" : "keyserverName",
    "kmipKeyServerPort" : 5696
  },
"id": 1
}
----


== 回應範例

此方法傳回類似以下範例的回應：

[listing]
----
{
   "id": 1,
   "result":
      {
        "kmipKeyServer": {
            "kmipCaCertificate":"CPDCCAaUCEDyRMcsf9tAbDpq40ES/E...",
            "kmipKeyServerHostnames":[
                "server1.hostname.com", "server2.hostname.com"
            ],
            "keyProviderID":1,
            "kmipKeyServerName":"keyserverName",
            "keyServerID":1
            "kmipKeyServerPort":1,
            "kmipClientCertificate":"kirWmnWXbj9T/UWZYB2oK0z5...",
            "kmipAssignedProviderIsActive":true
        }
    }
}
----


== 自版本以來的新版本

11.7
