---
permalink: api/reference_element_api_drive.html 
sidebar: sidebar 
keywords: objects,object,drive 
summary: 驅動器物件包含有關叢集活動節點中各個磁碟機的資訊。此物件包含有關已新增為磁碟區元資料或區塊磁碟機的磁碟機的詳細信息，以及尚未新增但可用的磁碟機的詳細資訊。您可以使用 ListDrives API 方法檢索此資訊。 
---
= 駕駛
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
驅動器物件包含有關叢集活動節點中各個磁碟機的資訊。此物件包含有關已新增為磁碟區元資料或區塊磁碟機的磁碟機的詳細信息，以及尚未新增但可用的磁碟機的詳細資訊。您可以使用以下方式檢索此資訊： `ListDrives` API 方法。



== 對象成員

該物件包含以下成員：

|===
| Name | 描述 | 類型 


 a| 
屬性
 a| 
JSON 物件格式的名稱-值對清單。該物件始終為空且不可修改。
 a| 
JSON 物件



 a| 
容量
 a| 
驅動器的總容量，以位元組為單位。
 a| 
整數



 a| 
底盤插槽
 a| 
對於 HCI 平台，此值為伺服器機箱中該磁碟機所在的節點字母和插槽號。對於儲存平台而言，插槽號碼是「插槽」整數的字串表示形式。
 a| 
細繩



 a| 
驅動器故障詳情
 a| 
如果磁碟機的狀態為“失敗”，則此欄位提供有關磁碟機被標記為失敗原因的更多詳細資訊。
 a| 
細繩



 a| 
磁碟機ID
 a| 
此磁碟機的 ID。
 a| 
整數



 a| 
驅動安全故障原因
 a| 
如果啟用或停用驅動器安全功能失敗，請說明失敗原因。如果值為“none”，則表示沒有發生故障。
 a| 
細繩



 a| 
金鑰ID
 a| 
金鑰提供者用於取得解鎖此磁碟機的身份驗證金鑰的金鑰 ID。
 a| 
唯一識別符



 a| 
密鑰提供者ID
 a| 
確定用於解鎖此磁碟機的身份驗證金鑰的提供者。
 a| 
整數



 a| 
節點ID
 a| 
包含此磁碟機的節點的 ID。
 a| 
整數



 a| 
分段檔案大小
 a| 
驅動器的段檔案大小，以位元組為單位。
 a| 
整數



 a| 
序號
 a| 
硬碟序號。
 a| 
細繩



 a| 
投幣口
 a| 
伺服器機箱中該驅動器所在的插槽編號，如果使用 SATADimm 設備作為內部元資料驅動器，則為 -1。
 a| 
整數



 a| 
地位
 a| 
驅動器的狀態。可能的值：

* 可用：一個可用的驅動器。
* 活動：一個正在活動的驅動器。
* 擦除：驅動器正在被安全擦除。該硬碟上的所有資料都將永久刪除。
* 失敗：硬碟發生故障。先前儲存在該磁碟機上的所有資料都已遷移到叢集中的其他磁碟機。
* 移除：正在移除一個磁碟機。驅動器上先前的所有資料都將遷移到叢集中的其他驅動器。

 a| 
細繩



 a| 
類型
 a| 
驅動類型。可能的值：

* 卷：儲存卷元資料。
* 塊：儲存塊資料。
* 未知：驅動器類型尚未激活，尚待確定。

 a| 
細繩



 a| 
可用容量
 a| 
硬碟的可用容量，以位元組為單位。
 a| 
整數

|===


== 查找更多信息

xref:reference_element_api_listdrives.adoc[清單驅動器]
