---
permalink: api/reference_element_api_listkeyserverskmip.html 
sidebar: sidebar 
keywords: KMIP,key server,key,server,listing,list,listkeyserverskmip 
summary: '您可以使用 ListKeyServersKmip 方法列出所有已建立的金鑰管理互通協定 (KMIP) 金鑰伺服器。您可以透過指定其他參數來篩選結果。' 
---
= ListKeyServersKmip
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
你可以使用 `ListKeyServersKmip`列出所有已建立的金鑰管理互通協定 (KMIP) 金鑰伺服器的方法。您可以透過指定其他參數來篩選結果。



== 參數

此方法有以下輸入參數：

|===
| Name | 描述 | 類型 | 預設值 | 必需的 


 a| 
密鑰提供者ID
 a| 
如果指定了該方法，則該方法僅傳回指派給指定 KMIP 金鑰提供者的 KMIP 金鑰伺服器。如果省略，則傳回的 KMIP 金鑰伺服器將不會根據它們是否指派給指定的 KMIP 金鑰提供者進行篩選。
 a| 
整數
 a| 
沒有任何
 a| 
不



 a| 
kmipAssignedProviderIsActive
 a| 
過濾器根據 KMIP 密鑰伺服器物件是否處於活動狀態傳回這些物件。可能的值：

* true：僅傳回處於活動狀態的 KMIP 金鑰伺服器（提供目前正在使用的金鑰）。
* false：僅傳回不活躍的 KMIP 金鑰伺服器（不提供任何金鑰且可以刪除）。


如果省略，則傳回的 KMIP 金鑰伺服器不會根據其是否處於活動狀態進行篩選。
 a| 
布林值
 a| 
沒有任何
 a| 
不



 a| 
kmipHasProviderAssigned
 a| 
根據是否已指派 KMIP 金鑰提供程序，篩選出 KMIP 金鑰伺服器。可能的值：

* true：僅傳回已指派 KMIP 金鑰提供者的 KMIP 金鑰伺服器。
* false：僅傳回未指派 KMIP 金鑰提供者的 KMIP 金鑰伺服器。


如果省略，則傳回的 KMIP 金鑰伺服器不會根據其是否已指派 KMIP 金鑰提供者進行篩選。
 a| 
布林值
 a| 
沒有任何
 a| 
不

|===


== 傳回值

此方法具有以下傳回值：

|===


| Name | 描述 | 類型 


 a| 
kmip金鑰伺服器
 a| 
已建立的 KMIP 金鑰伺服器完整清單。
 a| 
link:reference_element_api_keyserverkmip.html["金鑰伺服器Kmip"]大批

|===


== 請求範例

該方法的請求類似於以下範例：

[listing]
----
{
  "method": "ListKeyServersKmip",
  "params": {},
"id": 1
}
----


== 回應範例

此方法傳回類似以下範例的回應：

[listing]
----
{
    "kmipKeyServers": [
        {
            "kmipKeyServerName": "keyserverName",
            "kmipClientCertificate": "dKkkirWmnWXbj9T/UWZYB2oK0z5...",
            "keyServerID": 15,
            "kmipAssignedProviderIsActive": true,
            "kmipKeyServerPort": 5696,
            "kmipCaCertificate": "MIICPDCCAaUCEDyRMcsf9tAbDpq40ES/E...",
            "kmipKeyServerHostnames": [
                "server1.hostname.com", "server2.hostname.com"
            ],
            "keyProviderID": 1
        }
    ]
}
----


== 自版本以來的新版本

11.7
