---
permalink: api/reference_element_api_modifyvirtualnetwork.html 
sidebar: sidebar 
keywords: virtual,network,modify,modifying,change,changing,edit,editing,modifyvirtualnetwork 
summary: 您可以使用 ModifyVirtualNetwork 方法來變更現有虛擬網路的屬性。 
---
= 修改虛擬網絡
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
你可以使用 `ModifyVirtualNetwork`更改現有虛擬網路屬性的方法。

此方法可讓您新增或刪除位址區塊、變更子網路遮罩或修改虛擬網路的名稱或描述。您也可以使用它來啟用或停用命名空間，以及在虛擬網路上啟用命名空間時新增或刪除網關。


NOTE: 此方法需要 virtualNetworkID 或 virtualNetworkTag 作為參數，但不能同時使用兩者。

警告：

透過變更命名空間參數來啟用或停用現有虛擬網路的可路由儲存 VLAN 功能，會中斷虛擬網路處理的任何流量。最好在計劃維護視窗期間變更命名空間參數。



== 參數

此方法有以下輸入參數：

|===


| Name | 描述 | 類型 | 預設值 | 必需的 


 a| 
虛擬網路 ID
 a| 
要修改的虛擬網路的唯一識別碼。這是叢集分配的虛擬網路 ID。
 a| 
整數
 a| 
沒有任何
 a| 
不



 a| 
虛擬網路標籤
 a| 
用於標識要修改的虛擬網路的網路標籤。
 a| 
整數
 a| 
沒有任何
 a| 
不



 a| 
地址區塊
 a| 
要為此虛擬網路設定的新位址區塊。這可能包括向現有物件新增新的位址區塊，或省略需要刪除的未使用的位址區塊。或者，您可以擴充或縮小現有位址區塊的大小。對於虛擬網路對象，您只能增加起始位址區塊的大小；您永遠無法減少它。此物件必需的成員：

* 起始位址：IP 位址範圍的起始位址。  （細繩）
* 大小：要包含在區塊中的 IP 位址數量。  （整數）

 a| 
JSON 物件
 a| 
沒有任何
 a| 
不



 a| 
閘道
 a| 
虛擬網路網關的IP位址。僅當命名空間參數設為 true 時，此參數才有效。
 a| 
細繩
 a| 
沒有任何
 a| 
不



 a| 
屬性
 a| 
JSON 物件格式的名稱-值對清單。
 a| 
JSON 物件
 a| 
沒有任何
 a| 
不



 a| 
姓名
 a| 
虛擬網路的新名稱。
 a| 
細繩
 a| 
沒有任何
 a| 
不



 a| 
命名空間
 a| 
設定為 true 時，透過重新建立虛擬網路並配置命名空間來啟用可路由儲存 VLAN 功能。設定為 false 時，停用虛擬網路的 VRF 功能。變更此值會中斷通過此虛擬網路的流量。
 a| 
布林值
 a| 
沒有任何
 a| 
不



 a| 
網路遮罩
 a| 
為此虛擬網路建立新的網路遮罩。
 a| 
細繩
 a| 
沒有任何
 a| 
不



 a| 
svip
 a| 
此虛擬網路的儲存虛擬 IP 位址。虛擬網路的 SVIP 無法變更。要使用不同的 SVIP 位址，必須建立一個新的虛擬網路。
 a| 
細繩
 a| 
沒有任何
 a| 
不

|===


== 傳回值

此方法沒有傳回值。



== 請求範例

該方法的請求類似於以下範例：

[listing]
----
{
  "method": "ModifyVirtualNetwork",
  "params": {
    "virtualNetworkID": 2,
    "name": "ESX-VLAN-3112",
    "addressBlocks": [
     {
      "start": "10.1.112.1",
      "size": 20
     },
     {
      "start": "10.1.112.100",
      "size": 20
     }
   ],
    "netmask": "255.255.255.0",
    "gateway": "10.0.1.254",
    "svip": "10.1.112.200",
    "attributes": {}
  },
  "id":1
}
----


== 回應範例

此方法傳回類似以下範例的回應：

[listing]
----
{
  "id": 1,
  "result": {
  }
}
----


== 自版本以來的新版本

9.6
