---
permalink: api/reference_element_api_modifyinitiators.html 
sidebar: sidebar 
keywords: modify,modifying,edit,editing,change,changing,initiators,initiator,attribute,attributes,modifyinitiators 
summary: 您可以使用 ModifyInitiators 方法來變更一個或多個現有啟動器的屬性。 
---
= 修改啟動器
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
你可以使用 `ModifyInitiators`更改一個或多個現有啟動器屬性的方法。

您無法變更現有發起者的名稱。如果需要更改發起者的名稱，請先使用以下命令將其刪除：xref:reference_element_api_deleteinitiators.adoc[刪除發起者]並使用該方法創建一個新的xref:reference_element_api_createinitiators.adoc[建立啟動器]方法。

如果 ModifyInitiators 無法變更參數中提供的啟動器之一，則該方法傳回錯誤，並且不會修改任何啟動器（不可能部分完成）。



== 範圍

此方法具有以下輸入參數：

|===


| Name | 描述 | 類型 | 預設值 | 必需的 


 a| 
發起者
 a| 
包含每個啟動器特徵的物件列表，用於修改。可能的對象：

* `alias`（可選）要指派給發起者的新友善名稱。  （細繩）
* `attributes`（可選）要指派給發起者的一組新的 JSON 屬性。  （JSON 對象）
* `chapUsername`（可選）此發起者的新的唯一 CHAP 使用者名稱。  （細繩）
* `forceDuringUpgrade`在升級過程中完成啟動器修改。
* `initiatorID`（必填）要修改的發起者的 ID。  （整數）
* `initiatorSecret`（可選）用於驗證發起者身分的新 CHAP 金鑰。  （細繩）
* `requireChap`（可選）如果此發起程序需要 CHAP，則為 True。  （布林值）
* `targetSecret`（可選）用於驗證目標身分的新 CHAP 金鑰（在使用相互 CHAP 驗證時）。  （細繩）
* `virtualNetworkIDs`（可選）與此啟動器關聯的虛擬網路識別碼清單。如果您定義了一個或多個虛擬網絡，則此發起程式只能登入這些虛擬網路。如果沒有定義任何虛擬網絡，則此發起程序可以登入所有網路。
* `volumeAccessGroupID`（可選）要將發起程序新增至的磁碟區存取群組的 ID。如果發起程序之前位於不同的磁碟區存取群組中，則會將其從舊的磁碟區存取群組中移除。如果此金鑰存在但為空，則啟動器將從其目前磁碟區存取群組中移除，但不會放入任何新的磁碟區存取群組中。  （整數）

 a| 
JSON 物件數組
 a| 
沒有任何
 a| 
是的

|===


== 傳回值

此方法傳回以下值：

|===


| Name | 描述 | 類型 


 a| 
發起者
 a| 
描述新修改的啟動器的物件清單。
 a| 
xref:reference_element_api_initiator.adoc[發起者]大批

|===


== 請求範例

該方法的請求類似於以下範例：

[listing]
----
{
  "id": 6683,
  "method": "ModifyInitiators",
  "params": {
    "initiators": [
      {
        "initiatorID": 2,
        "alias": "alias1",
        "volumeAccessGroupID": null
      },
      {
        "initiatorID": 3,
        "alias": "alias2",
        "volumeAccessGroupID": 1
      }
    ]
  }
}
----


== 回應範例

此方法傳回類似以下範例的回應：

[listing]
----
{
  "id": 6683,
  "result": {
    "initiators": [
      {
        "alias": "alias1",
        "attributes": {},
        "initiatorID": 2,
        "initiatorName": "iqn.1993-08.org.debian:01:395543635",
        "volumeAccessGroups": []
      },
      {
        "alias": "alias2",
        "attributes": {},
        "initiatorID": 3,
        "initiatorName": "iqn.1993-08.org.debian:01:935573135",
        "volumeAccessGroups": [
          1
        ]
      }
    ]
  }
}
----


== 自版本以來的新版本

9.6



== 查找更多信息

* xref:reference_element_api_createinitiators.adoc[建立啟動器]
* xref:reference_element_api_deleteinitiators.adoc[刪除發起者]

