---
permalink: api/reference_element_api_listkeyproviderskmip.html 
sidebar: sidebar 
keywords: KMIP,key providers,key,provider,retrieving,listing,list,retrieve,listkeyproviderskmip 
summary: '您可以使用 ListKeyProvidersKmip 方法檢索所有現有的金鑰管理互通性協定 (KMIP) 金鑰提供者的清單。您可以透過指定其他參數來篩選清單。' 
---
= ListKeyProvidersKmip
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
你可以使用 `ListKeyProvidersKmip`檢索所有現有金鑰管理互通協定 (KMIP) 金鑰提供者清單的方法。您可以透過指定其他參數來篩選清單。



== 參數

此方法有以下輸入參數：

|===
| Name | 描述 | 類型 | 預設值 | 必需的 


 a| 
keyProviderIsActive
 a| 
過濾器根據 KMIP 密鑰伺服器物件是否處於活動狀態傳回這些物件。可能的值：

* true：僅傳回處於活動狀態的 KMIP 金鑰提供者（提供目前正在使用的金鑰）。
* false：僅傳回不活躍的 KMIP 金鑰提供者（不提供任何金鑰且可以刪除）。


如果省略，則傳回的 KMIP 金鑰提供者不會根據其是否處於活動狀態進行篩選。
 a| 
布林值
 a| 
沒有任何
 a| 
不



 a| 
kmipKeyProviderHasServerAssigned
 a| 
根據是否已指派 KMIP 金鑰伺服器，篩選出 KMIP 金鑰提供者。可能的值：

* true：僅傳回已指派 KMIP 金鑰伺服器的 KMIP 金鑰提供者。
* false：僅傳回未指派 KMIP 金鑰伺服器的 KMIP 金鑰提供者。


如果省略，則傳回的 KMIP 金鑰提供者不會根據其是否已指派 KMIP 金鑰伺服器進行篩選。
 a| 
布林值
 a| 
沒有任何
 a| 
不

|===


== 傳回值

此方法具有以下傳回值：

|===


| Name | 描述 | 類型 


 a| 
kmipKeyProviders
 a| 
已建立的 KMIP 金鑰提供者清單。
 a| 
link:reference_element_api_keyproviderkmip.html["金鑰提供者Kmip"]大批

|===


== 請求範例

該方法的請求類似於以下範例：

[listing]
----
{
  "method": "ListKeyProvidersKmip",
  "params": {},
"id": 1
}
----


== 回應範例

此方法傳回類似以下範例的回應：

[listing]
----
{
   "id": 1,
   "result":
    {
    "kmipKeyProviders": [
        {
            "keyProviderID": 15,
            "kmipCapabilities": "SSL",
            "keyProviderIsActive": true,
            "keyServerIDs": [
                1
            ],
            "keyProviderName": "KeyProvider1"
        }
    ]
}
}
----


== 自版本以來的新版本

11.7
