---
permalink: api/reference_element_api_modifyvolumeaccessgroup.html 
sidebar: sidebar 
keywords: volume,access,group,modify,modifying,updating,changing,change,update,edit,editing,modifyvolumeaccessgroup 
summary: 您可以使用 ModifyVolumeAccessGroup 方法更新啟動器，並在磁碟區存取群組中新增或刪除磁碟區。 
---
= 修改卷訪問群組
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
你可以使用 `ModifyVolumeAccessGroup`用於更新啟動器以及向磁碟區存取群組新增或刪除磁碟區的方法。

如果指定的啟動器或磁碟區與目前存在的啟動器或磁碟區重複，則磁碟區存取群組保持不變。如果您不指定磁碟區或啟動器的值，則目前啟動器和磁碟區的清單不會變更。



== 參數

此方法有以下輸入參數：

|===


| Name | 描述 | 類型 | 預設值 | 必需的 


 a| 
卷訪問群組ID
 a| 
要修改的磁碟區存取群組的 ID。
 a| 
整數
 a| 
沒有任何
 a| 
是的



 a| 
姓名
 a| 
該卷訪問組的新名稱。
 a| 
細繩
 a| 
沒有任何
 a| 
不



 a| 
屬性
 a| 
JSON 物件格式的名稱-值對清單。
 a| 
JSON 物件
 a| 
沒有任何
 a| 
不



 a| 
發起者
 a| 
若要包含在磁碟區存取群組中的發起程序 ID 或名稱（IQN 和 WWPN）清單。如果傳遞一個啟動器名稱列表，則當啟動器尚不存在時，將建立這些啟動器。如果傳遞一個發起者 ID 列表，則如果其中任何發起者尚不存在，則該方法將傳回錯誤。傳遞發起者名稱已被棄用；應盡可能使用發起者 ID。
 a| 
整數數組（建議）或字串數組（已棄用）
 a| 
沒有任何
 a| 
不



 a| 
刪除孤兒發起者
 a| 
指定在從磁碟區存取群組中刪除啟動器物件後是否將其刪除。可能的值：

* true：從磁碟區存取群組中移除啟動器物件後，將其刪除。
* false：從磁碟區存取群組中刪除啟動器物件後，請勿將其刪除。這是預設值。

 a| 
布林值
 a| 
錯誤的
 a| 
不



 a| 
卷
 a| 
要修改的磁碟區的磁碟區 ID 清單。
 a| 
整數數組
 a| 
沒有任何
 a| 
xref:reference_element_api_volumeaccessgroup.adoc[卷訪問群組]

|===


== 傳回值

此方法傳回以下值：

|===


| Name | 描述 | 類型 


 a| 
卷訪問群組
 a| 
包含有關新修改的磁碟區存取群組資訊的物件。
 a| 
xref:reference_element_api_volumeaccessgroup.adoc[卷訪問群組]

|===


== 請求範例

該方法的請求類似於以下範例：

[listing]
----
{
   "method": "ModifyVolumeAccessGroup",
   "params": {
      "volumeAccessGroupID": 96,
      "name": "accessgrouptest",
      "initiators": [115,114],
      "volumes": [
         346
    ],
      "attributes": {}
   }
}
----


== 回應範例

此方法傳回類似以下範例的回應：

[listing]
----
{
  "id": null,
  "result": {
    "volumeAccessGroup": {
      "attributes": {},
      "deletedVolumes": [
        327
      ],
      "initiatorIDs": [
        114,
        115
      ],
      "initiators": [
        "iqn.1998-01.com.vmware:desk1-esx1-577b283a",
        "iqn.1998-01.com.vmware:donesq-esx1-421b281b"
      ],
      "name": "accessgrouptest",
      "volumeAccessGroupID": 96,
      "volumes": [
        346
      ]
    }
  }
}
----


== 自版本以來的新版本

9.6



== 查找更多信息

* xref:reference_element_api_addinitiatorstovolumeaccessgroup.adoc[將發起者新增至磁碟區存取群組]
* xref:reference_element_api_addvolumestovolumeaccessgroup.adoc[將磁碟區新增至磁碟區存取群組]
* xref:reference_element_api_removeinitiatorsfromvolumeaccessgroup.adoc[從磁碟區存取群組中刪除發起程式]
* xref:reference_element_api_removevolumesfromvolumeaccessgroup.adoc[從卷宗訪問群組移除卷]

