---
permalink: api/reference_element_api_testconnectmvip.html 
sidebar: sidebar 
keywords: management,connection,test,testing,mvip,testconnectmvip 
summary: 您可以使用 TestConnectMvip 方法測試與儲存叢集的管理連線。此測試會向 MVIP 發送 ping 請求，並執行簡單的 API 方法來驗證連線性。 
---
= TestConnectMvip
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
你可以使用 `TestConnectMvip`測試與儲存叢集的管理連接的方法。此測試會向 MVIP 發送 ping 請求，並執行簡單的 API 方法來驗證連線性。



== 範圍

此方法具有以下輸入參數：

|===
| Name | 描述 | 類型 | 預設值 | 必需的 


| 貴賓 | 您可以傳遞此值來測試不同 MVIP 的管理連線。測試與目標群集的連線時，不需要使用此值。 | 細繩 | 沒有任何 | 不 
|===


== 傳回值

此方法傳回以下值：

|===
| Name | 描述 | 類型 


| 細節  a| 
測試操作資訊（JSON 物件）：

* `connected`：指示測試是否可以連接到MVIP（布林值）
* `mvip`：針對（字串）測試的 MVIP
* `pingBytes`：56 位元組和 1500 位元組（物件）的 ping 測試詳情
+
** `56`56 位元組 ping 測試結果（JSON 物件）：
+
*** `individualResponseTimes`：每個整合節點的回應時間列表（字串陣列）
*** `individualStatus`：來自每個叢集節點的 ping 狀態清單（布林數組）
*** `responseTime`平均 ping 回應時間（字串）
*** `successful`：指示 ping 測試是否成功（布林值）


** `1500`1500 位元組 ping 測試結果（JSON 物件）：
+
*** `individualResponseTimes`：每個整合節點的回應時間列表（字串陣列）
*** `individualStatus`：來自每個叢集節點的 ping 狀態清單（布林數組）
*** `responseTime`平均 ping 回應時間（字串）
*** `successful`ping 測試是否成功（布林值）


** `duration`：運行測試所需的時間（字串）
** `result`測試的整體結果（字串）



| JSON 物件 
|===


== 請求範例

該方法的請求類似於以下範例：

[listing]
----
{
   "method": "TestConnectMvip",
   "params": {
       "mvip" : "172.27.62.50"
       },
    "id":1
}
----


== 回應範例

此方法傳回類似以下範例的回應：

[listing]
----
{
  "id": 1,
  "result": {
    "details": {
      "connected": true,
      "mvip": "172.27.62.50",
      "pingBytes": {
        "1500": {
          "individualResponseTimes": [
            "00:00:00.000250",
            "00:00:00.000206",
            "00:00:00.000200",
            "00:00:00.000199",
            "00:00:00.000199"
         ],
          "individualStatus": [
             true,
             true,
             true,
             true,
             true
         ],
         "responseTime": "00:00:00.000211",
         "successful": true
       },
       "56": {
          "individualResponseTimes": [
            "00:00:00.000217",
            "00:00:00.000122",
            "00:00:00.000117",
            "00:00:00.000119",
            "00:00:00.000121"
         ],
         "individualStatus": [
            true,
            true,
            true,
            true,
            true
         ],
         "responseTime": "00:00:00.000139",
         "successful": true
        }
      }
    },
    "duration": "00:00:00.271244",
    "result": "Passed"
  }
}
----


== 自版本以來的新版本

9.6
