---
permalink: api/reference_element_api_deleteauthsessionsbyusername.html 
sidebar: sidebar 
keywords: auth sessions,username,delete,authentication sessions 
summary: 您可以使用 DeleteAuthSessionsByUsername 方法刪除給定使用者的所有驗證會話。不在 AccessGroup ClusterAdmins/Administrator 中的呼叫者只能刪除自己的會話。擁有 ClusterAdmins/Administrator 權限的呼叫者可以刪除屬於任何使用者的會話。若要查看可以刪除的會話列表，請使用相同的參數呼叫 ListAuthSessionsByUsername。若要查看可刪除的會話列表，請使用相同的參數呼叫 ListAuthSessionsByUsername 方法。 
---
= 按使用者名稱刪除身份驗證會話
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
你可以使用 `DeleteAuthSessionsByUsername`刪除給定使用者的所有身份驗證會話的方法。不在 AccessGroup ClusterAdmins/Administrator 中的呼叫者只能刪除自己的會話。擁有 ClusterAdmins/Administrator 權限的呼叫者可以刪除屬於任何使用者的會話。若要查看可以刪除的會話列表，請使用 `ListAuthSessionsByUsername`參數相同。若要查看可刪除的會話列表，請使用下列方法： `ListAuthSessionsByUsername`使用相同參數的方法。



== 參數

此方法有以下輸入參數：

|===
| Name | 描述 | 類型 | 預設值 | 必需的 


 a| 
認證方法
 a| 
要刪除的使用者會話的身份驗證方法。只有屬於 ClusterAdmins/Administrator AccessGroup 的呼叫者才能提供此參數。可能的值有：

* *authMethod=Cluster* 指定叢集管理員使用者名稱。
* *authMethod=Ldap* 指定使用者的 LDAP DN。
* *authMethod=Idp* 指定使用者的 IdP UUID 或 NameID。如果 IdP 未配置為傳回任一選項，則此設定會指定在建立工作階段時所發出的隨機 UUID。

 a| 
認證方法
 a| 
沒有任何
 a| 
不



 a| 
使用者名稱
 a| 
用戶的唯一識別碼。
 a| 
細繩
 a| 
沒有任何
 a| 
不

|===


== 傳回值

此方法傳回以下值：

|===


| Name | 描述 | 類型 


 a| 
會議
 a| 
已刪除身份驗證會話的會話資訊。
 a| 
link:reference_element_api_authsessioninfo.html["authSessionInfo"]

|===


== 請求範例

該方法的請求類似於以下範例：

[listing]
----
{
  "method": "DeleteAuthSessionsByUsername",
  "params": {
    "authMethod": "Cluster",
    "username": "admin"
  }
}
----


== 回應範例

此方法傳回類似以下範例的回應：

[listing]
----
{
"sessions": [
      {
        "accessGroupList": [
          "administrator"
        ],
        "authMethod": "Cluster",
        "clusterAdminIDs": [
          1
        ],
        "finalTimeout": "2020-03-14T19:21:24Z",
        "idpConfigVersion": 0,
        "lastAccessTimeout": "2020-03-11T19:51:24Z",
        "sessionCreationTime": "2020-03-11T19:21:24Z",
        "sessionID": "b12bfc64-f233-44df-8b9f-6fb6c011abf7",
        "username": "admin"
      }
    ]
}
----


== 自版本以來的新版本

12.0
