---
permalink: api/reference_element_api_authsessioninfo.html 
sidebar: sidebar 
keywords: objects,object,authSessionInfo 
summary: authSessionInfo 物件包含有關驗證會話的資訊。 
---
= authSessionInfo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
這 `authSessionInfo`物件包含有關身份驗證會話的資訊。



== 對象成員

該物件包含以下成員：

|===
| Name | 描述 | 類型 


 a| 
`accessGroupList`
 a| 
使用者存取群組列表。
 a| 
字串數組



 a| 
`authMethod`
 a| 
叢集管理員使用者擁有的授權類型。可能的值：

* LDAP - 透過 LDAP 進行身份驗證。
* 叢集 - 透過儲存在叢集資料庫中的使用者名稱和密碼進行身份驗證。
* IdP - 透過第三方身分提供者進行身分驗證。

 a| 
細繩



 a| 
`clusterAdminIDs`
 a| 
與此會話關聯的群集管理員 ID 清單。對於與 LDAP 或第三方身分提供者 (IdP) 相關的會話，這將是與此會話關聯的匹配群集管理員 ID 的總計清單。
 a| 
整數數組



 a| 
`finalTimeout`
 a| 
會話失效的時間。此值在建立會話時設置，無法變更。
 a| 
細繩



 a| 
`idpConfigVersion`
 a| 
建立會話時的身分提供者配置版本。
 a| 
整數



 a| 
`lastAccessTimeout`
 a| 
會話因不活動而失效的時間。當會話被存取使用時，它會被設定為一個新值，直到會話因 finalTimeout 達到而失效為止。
 a| 
細繩



 a| 
`sessionCreationTime`
 a| 
會話創建時間。
 a| 
細繩



 a| 
`sessionID`
 a| 
此會話的 UUID。
 a| 
唯一識別符



 a| 
`username`
 a| 
與此會話關聯的使用者名稱。對於與 LDAP 相關的會話，這將是使用者的 LDAP DN。對於與第三方身分提供者相關的會話，這將是一個任意的名稱-值對，用於審計會話內的操作。它不一定與叢集上的叢集管理員名稱相符。例如，SAML 主題名稱 ID，但這取決於 IdP 的配置和 SAML 斷言的最終內容。
 a| 
細繩

|===